Stride Reference Manual: proto::GeoGrid Class Reference
proto::GeoGrid Class Reference
#include <geogrid.pb.h>
Public Types
typedef GeoGrid_Location Location
typedef GeoGrid_Person Person
Public Member Functions
GeoGrid ()
virtual ~GeoGrid ()
GeoGrid (const GeoGrid &from)
GeoGrid & operator= (const GeoGrid &from)
const
::google::protobuf::UnknownFieldSet & unknown_fields () const
inline::google::protobuf::UnknownFieldSet * mutable_unknown_fields ()
void Swap (GeoGrid *other)
GeoGrid * New () const PROTOBUF_FINAL
GeoGrid * New (::google::protobuf::Arena *arena) const PROTOBUF_FINAL
void CopyFrom (const ::google::protobuf::Message &from) PROTOBUF_FINAL
void MergeFrom (const ::google::protobuf::Message &from) PROTOBUF_FINAL
void CopyFrom (const GeoGrid &from)
void MergeFrom (const GeoGrid &from)
void Clear () PROTOBUF_FINAL
bool IsInitialized () const PROTOBUF_FINAL
size_t ByteSizeLong () const PROTOBUF_FINAL
bool MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream *input) PROTOBUF_FINAL
void SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream *output) const PROTOBUF_FINAL
::google::protobuf::uint8 * InternalSerializeWithCachedSizesToArray (bool deterministic,::google::protobuf::uint8 *target) const PROTOBUF_FINAL
int GetCachedSize () const PROTOBUF_FINAL
::google::protobuf::Metadata GetMetadata () const PROTOBUF_FINAL
int locations_size () const
void clear_locations ()
const ::proto::GeoGrid_Location & locations (int index) const
::proto::GeoGrid_Location * mutable_locations (int index)
::proto::GeoGrid_Location * add_locations ()
::google::protobuf::RepeatedPtrField
< ::proto::GeoGrid_Location > * mutable_locations ()
const
::google::protobuf::RepeatedPtrField
< ::proto::GeoGrid_Location > & locations () const
int persons_size () const
void clear_persons ()
const ::proto::GeoGrid_Person & persons (int index) const
::proto::GeoGrid_Person * mutable_persons (int index)
::proto::GeoGrid_Person * add_persons ()
::google::protobuf::RepeatedPtrField
< ::proto::GeoGrid_Person > * mutable_persons ()
const
::google::protobuf::RepeatedPtrField
< ::proto::GeoGrid_Person > & persons () const
Static Public Member Functions
static const
::google::protobuf::Descriptor * descriptor ()
static const GeoGrid & default_instance ()
static void InitAsDefaultInstance ()
static const GeoGrid * internal_default_instance ()
Static Public Attributes
static PROTOBUF_CONSTEXPR int const kIndexInFileMessages
static const int kLocationsFieldNumber = 1
static const int kPersonsFieldNumber = 2
Private Member Functions
void SharedCtor ()
void SharedDtor ()
void SetCachedSize (int size) const PROTOBUF_FINAL
void InternalSwap (GeoGrid *other)
inline::google::protobuf::Arena * GetArenaNoVirtual () const
void * MaybeArenaPtr () const
friend void::protobuf_geogrid_2eproto::InitDefaultsGeoGridImpl ()
Private Attributes
::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_
::google::protobuf::internal::HasBits< 1 > _has_bits_
int _cached_size_
::google::protobuf::RepeatedPtrField
< ::proto::GeoGrid_Location > locations_
::google::protobuf::RepeatedPtrField
< ::proto::GeoGrid_Person > persons_
Friends
struct ::protobuf_geogrid_2eproto::TableStruct
void swap (GeoGrid &a, GeoGrid &b)
Detailed Description
Definition at line 1011 of file geogrid.pb.h.
Member Typedef Documentation
typedef GeoGrid_Location proto::GeoGrid::Location
Definition at line 1098 of file geogrid.pb.h.
typedef GeoGrid_Person proto::GeoGrid::Person
Definition at line 1099 of file geogrid.pb.h.
Constructor & Destructor Documentation
proto::GeoGrid::GeoGrid ()
virtual proto::GeoGrid::~GeoGrid () virtual
proto::GeoGrid::GeoGrid (const GeoGrid & from)
Member Function Documentation
GeoGrid& proto::GeoGrid::operator= (const GeoGrid & from) inline
Definition at line 1018 of file geogrid.pb.h.
References proto::GeoGrid_Location_Coordinate::CopyFrom().
const ::google::protobuf::UnknownFieldSet& proto::GeoGrid::unknown_fields () const inline
Definition at line 1037 of file geogrid.pb.h.
inline ::google::protobuf::UnknownFieldSet* proto::GeoGrid::mutable_unknown_fields () inline
Definition at line 1040 of file geogrid.pb.h.
static const ::google::protobuf::Descriptor* proto::GeoGrid::descriptor () static
static const GeoGrid& proto::GeoGrid::default_instance () static
static void proto::GeoGrid::InitAsDefaultInstance () static
static const GeoGrid* proto::GeoGrid::internal_default_instance () inline static
Definition at line 1048 of file geogrid.pb.h.
References proto::_GeoGrid_default_instance_.
void proto::GeoGrid::Swap (GeoGrid * other)
GeoGrid* proto::GeoGrid::New () const inline
Definition at line 1062 of file geogrid.pb.h.
References New().
Referenced by New().
GeoGrid* proto::GeoGrid::New (::google::protobuf::Arena * arena) const
void proto::GeoGrid::CopyFrom (const ::google::protobuf::Message & from)
void proto::GeoGrid::MergeFrom (const ::google::protobuf::Message & from)
void proto::GeoGrid::CopyFrom (const GeoGrid & from)
void proto::GeoGrid::MergeFrom (const GeoGrid & from)
void proto::GeoGrid::Clear ()
bool proto::GeoGrid::IsInitialized () const
size_t proto::GeoGrid::ByteSizeLong () const
bool proto::GeoGrid::MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream * input)
void proto::GeoGrid::SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream * output) const
::google::protobuf::uint8* proto::GeoGrid::InternalSerializeWithCachedSizesToArray (bool deterministic, ::google::protobuf::uint8 * target) const
int proto::GeoGrid::GetCachedSize () const inline
Definition at line 1079 of file geogrid.pb.h.
References proto::GeoGrid_Location_Coordinate::_cached_size_.
void proto::GeoGrid::SharedCtor () private
void proto::GeoGrid::SharedDtor () private
void proto::GeoGrid::SetCachedSize (int size) const private
void proto::GeoGrid::InternalSwap (GeoGrid * other) private
inline ::google::protobuf::Arena* proto::GeoGrid::GetArenaNoVirtual () const inline private
Definition at line 1086 of file geogrid.pb.h.
void* proto::GeoGrid::MaybeArenaPtr () const inline private
Definition at line 1089 of file geogrid.pb.h.
::google::protobuf::Metadata proto::GeoGrid::GetMetadata () const
int proto::GeoGrid::locations_size () const inline
Definition at line 1793 of file geogrid.pb.h.
Referenced by gengeopop::GeoGridProtoReader::Read().
void proto::GeoGrid::clear_locations () inline
Definition at line 1796 of file geogrid.pb.h.
const ::proto::GeoGrid_Location & proto::GeoGrid::locations (int index) const inline
Definition at line 1799 of file geogrid.pb.h.
Referenced by gengeopop::GeoGridProtoReader::Read().
proto::GeoGrid_Location * proto::GeoGrid::mutable_locations (int index) inline
Definition at line 1803 of file geogrid.pb.h.
proto::GeoGrid_Location * proto::GeoGrid::add_locations () inline
Definition at line 1807 of file geogrid.pb.h.
Referenced by gengeopop::GeoGridProtoWriter::Write().
google::protobuf::RepeatedPtrField<::proto::GeoGrid_Location > * proto::GeoGrid::mutable_locations () inline
Definition at line 1812 of file geogrid.pb.h.
const ::google::protobuf::RepeatedPtrField<::proto::GeoGrid_Location > & proto::GeoGrid::locations () const inline
Definition at line 1817 of file geogrid.pb.h.
int proto::GeoGrid::persons_size () const inline
Definition at line 1823 of file geogrid.pb.h.
Referenced by gengeopop::GeoGridProtoReader::Read().
void proto::GeoGrid::clear_persons () inline
Definition at line 1826 of file geogrid.pb.h.
const ::proto::GeoGrid_Person & proto::GeoGrid::persons (int index) const inline
Definition at line 1829 of file geogrid.pb.h.
Referenced by gengeopop::GeoGridProtoReader::Read().
proto::GeoGrid_Person * proto::GeoGrid::mutable_persons (int index) inline
Definition at line 1833 of file geogrid.pb.h.
proto::GeoGrid_Person * proto::GeoGrid::add_persons () inline
Definition at line 1837 of file geogrid.pb.h.
Referenced by gengeopop::GeoGridProtoWriter::Write().
google::protobuf::RepeatedPtrField<::proto::GeoGrid_Person > * proto::GeoGrid::mutable_persons () inline
Definition at line 1842 of file geogrid.pb.h.
const ::google::protobuf::RepeatedPtrField<::proto::GeoGrid_Person > & proto::GeoGrid::persons () const inline
Definition at line 1847 of file geogrid.pb.h.
proto::GeoGrid::void::protobuf_geogrid_2eproto::InitDefaultsGeoGridImpl () private
Friends And Related Function Documentation
friend struct ::protobuf_geogrid_2eproto::TableStruct friend
Definition at line 1135 of file geogrid.pb.h.
void swap (GeoGrid & a, GeoGrid & b) friend
Definition at line 1056 of file geogrid.pb.h.
Member Data Documentation
PROTOBUF_CONSTEXPR int const proto::GeoGrid::kIndexInFileMessages static
Initial value:
=
    6
Definition at line 1052 of file geogrid.pb.h.
const int proto::GeoGrid::kLocationsFieldNumber = 1 static
Definition at line 1106 of file geogrid.pb.h.
const int proto::GeoGrid::kPersonsFieldNumber = 2 static
Definition at line 1118 of file geogrid.pb.h.
::google::protobuf::internal::InternalMetadataWithArena proto::GeoGrid::_internal_metadata_ private
Definition at line 1130 of file geogrid.pb.h.
::google::protobuf::internal::HasBits<1> proto::GeoGrid::_has_bits_ private
Definition at line 1131 of file geogrid.pb.h.
int proto::GeoGrid::_cached_size_ mutable private
Definition at line 1132 of file geogrid.pb.h.
::google::protobuf::RepeatedPtrField< ::proto::GeoGrid_Location > proto::GeoGrid::locations_ private
Definition at line 1133 of file geogrid.pb.h.
::google::protobuf::RepeatedPtrField< ::proto::GeoGrid_Person > proto::GeoGrid::persons_ private
Definition at line 1134 of file geogrid.pb.h.
The documentation for this class was generated from the following file:
geogrid.pb.h