Stride Reference Manual: gengeopop::CommutesCSVReader Class Reference
gengeopop::CommutesCSVReader Class Reference
Create a Reader which fills a GeoGrid with the Commutes found in a given CSV file.
#include <CommutesCSVReader.h>
Public Member Functions
CommutesCSVReader (std::unique_ptr< std::istream > istream)
Construct the CommutesCSVReader with an istream containing the CSV data.
void FillGeoGrid (std::shared_ptr< GeoGrid > geoGrid) const override
Add the found Commutes to the provided GeoGrid.
Public Member Functions inherited from gengeopop::CommutesReader
CommutesReader (std::unique_ptr< std::istream > inputStream)
Construct the CommutesReader with an istream containing the file content.
virtual ~CommutesReader ()=default
Default destructor.
Private Member Functions
double MunicipalityTotal (std::shared_ptr< Location > loc) const
Find the relative total populution in the submunicipalities. If it doesn't have any, it will return 0.
void AddCommute (std::shared_ptr< Location > from, std::shared_ptr< Location > to, double proportion) const
Add the provided commute symmetrically to the locations.
void AddCommuteFrom (std::shared_ptr< Location > from, std::shared_ptr< Location > to, double proportion) const
Add commutes by splitting the 'from' into submunicipalities if necessary.
void AddCommuteTo (std::shared_ptr< Location > from, std::shared_ptr< Location > to, double proportion) const
Add commutes by splitting the 'to' into submunicipalities if necessary.
Private Attributes
stride::util::CSV m_reader
The pure CSV reader.
Additional Inherited Members
Protected Attributes inherited from gengeopop::CommutesReader
std::unique_ptr< std::istream > m_inputStream
The istream containing the file content.
Detailed Description
Create a Reader which fills a GeoGrid with the Commutes found in a given CSV file.
Definition at line 14 of file CommutesCSVReader.h.
Constructor & Destructor Documentation
gengeopop::CommutesCSVReader::CommutesCSVReader (std::unique_ptr< std::istream > istream) explicit
Construct the CommutesCSVReader with an istream containing the CSV data.
Definition at line 8 of file CommutesCSVReader.cpp.
Member Function Documentation
void gengeopop::CommutesCSVReader::FillGeoGrid (std::shared_ptr< GeoGrid > geoGrid) const override virtual
Add the found Commutes to the provided GeoGrid.
Implements gengeopop::CommutesReader.
Definition at line 59 of file CommutesCSVReader.cpp.
References AddCommuteFrom(), stride::util::CSV::GetColumnCount(), stride::util::CSV::GetLabels(), and m_reader.
double gengeopop::CommutesCSVReader::MunicipalityTotal (std::shared_ptr< Location > loc) const private
Find the relative total populution in the submunicipalities. If it doesn't have any, it will return 0.
Definition at line 13 of file CommutesCSVReader.cpp.
Referenced by AddCommuteTo().
void gengeopop::CommutesCSVReader::AddCommute (std::shared_ptr< Location > from, std::shared_ptr< Location > to, double proportion) const private
Add the provided commute symmetrically to the locations.
Definition at line 22 of file CommutesCSVReader.cpp.
Referenced by AddCommuteTo().
void gengeopop::CommutesCSVReader::AddCommuteFrom (std::shared_ptr< Location > from, std::shared_ptr< Location > to, double proportion) const private
Add commutes by splitting the 'from' into submunicipalities if necessary.
Definition at line 29 of file CommutesCSVReader.cpp.
References AddCommuteTo().
Referenced by FillGeoGrid().
void gengeopop::CommutesCSVReader::AddCommuteTo (std::shared_ptr< Location > from, std::shared_ptr< Location > to, double proportion) const private
Add commutes by splitting the 'to' into submunicipalities if necessary.
Definition at line 40 of file CommutesCSVReader.cpp.
References AddCommute(), and MunicipalityTotal().
Referenced by AddCommuteFrom().
Member Data Documentation
stride::util::CSV gengeopop::CommutesCSVReader::m_reader private
The pure CSV reader.
Definition at line 37 of file CommutesCSVReader.h.
Referenced by FillGeoGrid().
The documentation for this class was generated from the following files:
CommutesCSVReader.h
CommutesCSVReader.cpp