Stride Reference Manual: stride::Immunizer< profile > Class Template Reference
stride::Immunizer< profile > Class Template Reference
Deals with immunization strategies.
#include <Immunizer.h>
Public Member Functions
Immunizer (util::RNManager &rnManager)
Constructor.
void Random (const util::SegmentedVector< ContactPool > &pools, std::vector< double > &immunityDistribution, double immunityLinkProbability)
Random immunization.
void Cocoon (const util::SegmentedVector< ContactPool > &pools, std::vector< double > &immunityDistribution, double immunityLinkProbability)
Cocoon immunization.
Static Public Member Functions
static void Administer (const std::vector< ContactPool > &, std::vector< double > &, double, util::RNManager &)
Private Attributes
util::RNManager & m_rn_manager
Random number manager.
Detailed Description
template<ImmunizationProfile profile>
class stride::Immunizer< profile >
Deals with immunization strategies.
Primary immunization profile: do nothing.
Definition at line 36 of file disease/Immunizer.h.
Constructor & Destructor Documentation
template<ImmunizationProfile profile> stride::Immunizer< profile >::Immunizer (util::RNManager & rnManager) explicit
Constructor.
Definition at line 33 of file Immunizer.cpp.
Member Function Documentation
template<ImmunizationProfile profile> void stride::Immunizer< profile >::Random (const util::SegmentedVector< ContactPool > & pools, std::vector< double > & immunityDistribution, double immunityLinkProbability)
Random immunization.
Definition at line 35 of file Immunizer.cpp.
References stride::Person::GetAge(), stride::util::RNManager::GetGenerator(), stride::Person::GetHealth(), stride::ContactPool::GetMember(), stride::ContactPool::GetSize(), stride::Health::IsImmune(), stride::Immunizer< profile >::m_rn_manager, stride::util::RNManager::RandomShuffle(), and stride::Health::SetSusceptible().
Referenced by stride::DiseaseSeeder::Vaccinate().
template<ImmunizationProfile profile> void stride::Immunizer< profile >::Cocoon (const util::SegmentedVector< ContactPool > & pools, std::vector< double > & immunityDistribution, double immunityLinkProbability)
Cocoon immunization.
Definition at line 94 of file Immunizer.cpp.
Referenced by stride::DiseaseSeeder::Vaccinate().
template<ImmunizationProfile profile> static void stride::Immunizer< profile >::Administer (const std::vector< ContactPool > & , std::vector< double > & , double , util::RNManager &) inline static
Definition at line 41 of file immunity/Immunizer.h.
Member Data Documentation
template<ImmunizationProfile profile> util::RNManager& stride::Immunizer< profile >::m_rn_manager private
Random number manager.
Definition at line 51 of file disease/Immunizer.h.
Referenced by stride::Immunizer< profile >::Random().
The documentation for this class was generated from the following files:
disease/Immunizer.h
Immunizer.cpp