Stride Reference Manual: gengeopop::ReaderFactory Class Reference
gengeopop::ReaderFactory Class Reference
A Factory for creating the correct implementation of the different Readers which parse the information needed to construct a GeoGrid, based on the file extension.
#include <ReaderFactory.h>
Public Member Functions
std::shared_ptr< CitiesReader > CreateCitiesReader (const boost::filesystem::path &path)
Create a CitiesReader based on an absolute Boost Filesystem Path pointing to the input file.
std::shared_ptr< CitiesReader > CreateCitiesReader (const std::string &filename)
Create a CitiesReader based on the filename of the input file, relative to the data directory.
std::shared_ptr< CommutesReader > CreateCommutesReader (const std::string &filename)
Create a CommutesReader based on an absolute Boost Filesystem Path pointing to the input file.
std::shared_ptr< CommutesReader > CreateCommutesReader (const boost::filesystem::path &path)
Create a CommutesReader based on the filename of the input file, relative to the data directory.
std::shared_ptr< HouseholdReader > CreateHouseholdReader (const std::string &filename)
Create a HouseholdReader based on the filename of the input file, relative to the data directory.
std::shared_ptr< HouseholdReader > CreateHouseholdReader (const boost::filesystem::path &path)
Create a HouseholdReader based on an absolute Boost Filesystem Path pointing to the input file.
std::shared_ptr
< SubMunicipalitiesReader > CreateSubMunicipalitiesReader (const std::string &filename)
Create a SubMunicipalitiesReader based on the filename of the input file, relative to the data directory.
std::shared_ptr
< SubMunicipalitiesReader > CreateSubMunicipalitiesReader (const boost::filesystem::path &path)
Create a SubMunicipalitiesReader based on an absolute Boost Filesystem Path pointing to the input file.
Private Member Functions
std::unique_ptr< std::istream > OpenFile (const boost::filesystem::path &path) const
Create an istream based on the provided Boost Filesystem Path.
Detailed Description
A Factory for creating the correct implementation of the different Readers which parse the information needed to construct a GeoGrid, based on the file extension.
Currently only CSV Readers are implemented.
Definition at line 16 of file ReaderFactory.h.
Member Function Documentation
std::shared_ptr< CitiesReader > gengeopop::ReaderFactory::CreateCitiesReader (const boost::filesystem::path & path)
Create a CitiesReader based on an absolute Boost Filesystem Path pointing to the input file.
Definition at line 18 of file ReaderFactory.cpp.
References OpenFile().
Referenced by CreateCitiesReader(), and gengeopop::GenGeoPopController::ReadDataFiles().
std::shared_ptr< CitiesReader > gengeopop::ReaderFactory::CreateCitiesReader (const std::string & filename)
Create a CitiesReader based on the filename of the input file, relative to the data directory.
Definition at line 13 of file ReaderFactory.cpp.
References CreateCitiesReader(), and stride::util::FileSys::GetDataDir().
std::shared_ptr< CommutesReader > gengeopop::ReaderFactory::CreateCommutesReader (const std::string & filename)
Create a CommutesReader based on an absolute Boost Filesystem Path pointing to the input file.
Definition at line 23 of file ReaderFactory.cpp.
References stride::util::FileSys::GetDataDir().
Referenced by gengeopop::GenGeoPopController::ReadDataFiles().
std::shared_ptr< CommutesReader > gengeopop::ReaderFactory::CreateCommutesReader (const boost::filesystem::path & path)
Create a CommutesReader based on the filename of the input file, relative to the data directory.
Definition at line 28 of file ReaderFactory.cpp.
References OpenFile().
std::shared_ptr< HouseholdReader > gengeopop::ReaderFactory::CreateHouseholdReader (const std::string & filename)
Create a HouseholdReader based on the filename of the input file, relative to the data directory.
Definition at line 33 of file ReaderFactory.cpp.
References stride::util::FileSys::GetDataDir().
Referenced by gengeopop::GenGeoPopController::ReadDataFiles().
std::shared_ptr< HouseholdReader > gengeopop::ReaderFactory::CreateHouseholdReader (const boost::filesystem::path & path)
Create a HouseholdReader based on an absolute Boost Filesystem Path pointing to the input file.
Definition at line 38 of file ReaderFactory.cpp.
References OpenFile().
std::shared_ptr< SubMunicipalitiesReader > gengeopop::ReaderFactory::CreateSubMunicipalitiesReader (const std::string & filename)
Create a SubMunicipalitiesReader based on the filename of the input file, relative to the data directory.
Definition at line 43 of file ReaderFactory.cpp.
References stride::util::FileSys::GetDataDir().
Referenced by gengeopop::GenGeoPopController::ReadDataFiles().
std::shared_ptr< SubMunicipalitiesReader > gengeopop::ReaderFactory::CreateSubMunicipalitiesReader (const boost::filesystem::path & path)
Create a SubMunicipalitiesReader based on an absolute Boost Filesystem Path pointing to the input file.
Definition at line 48 of file ReaderFactory.cpp.
References OpenFile().
std::unique_ptr< std::istream > gengeopop::ReaderFactory::OpenFile (const boost::filesystem::path & path) const private
Create an istream based on the provided Boost Filesystem Path.
Definition at line 54 of file ReaderFactory.cpp.
Referenced by CreateCitiesReader(), CreateCommutesReader(), CreateHouseholdReader(), and CreateSubMunicipalitiesReader().
The documentation for this class was generated from the following files:
ReaderFactory.h
ReaderFactory.cpp