# This is a sample build configuration for C++ – Make.
# Only use spaces to indent your .yml configuration.
# -----
# You can use any Docker image from Docker Hub, or your own container registry, as your build environment.
#
#image: vcatechnology/ubuntu-toolchain  they boost 1.58
image: broeckho/jbuntu-stride-artful
pipelines:
  default:
    - step:
        services:
        - docker
        caches:
          - docker
        script: # Modify the commands below to build your repository.
          - make -e FORCE_NO_OPENMP=TRUE -e FORCE_NO_PYTHON=TRUE -e FORCE_NO_HDF5=TRUE all
          - make -e FORCE_NO_OPENMP=TRUE -e FORCE_NO_PYTHON=TRUE -e FORCE_NO_HDF5=TRUE test

