Stride Reference Manual: stride::Person Class Reference
stride::Person Class Reference
Store and handle person data.
#include <Person.h>
Public Member Functions
Person ()
Default construction (for population vector).
Person (unsigned int id, double age, unsigned int householdId, unsigned int k12SchoolId, unsigned int collegeId, unsigned int workId, unsigned int primaryCommunityId, unsigned int secondaryCommunityId, std::size_t region, Health health=Health(), double=0, Belief *bp=nullptr)
Constructor: set the person data.
bool operator!= (const Person &p) const
Is this person not equal to the given person?
double GetAge () const
Get the age.
Belief * GetBelief ()
Return belief info.
const Belief * GetBelief () const
Return belief info.
unsigned int GetPoolId (const ContactPoolType::Id &poolType) const
Get ID of contactpool_type.
char GetGender () const
Return person's gender.
Health & GetHealth ()
Return person's health status.
const Health & GetHealth () const
Return person's health status.
unsigned int GetId () const
Get the id.
void SetId (unsigned int id)
Set the id.
bool IsInPool (const ContactPoolType::Id poolType, unsigned int poolId) const
Check if a person is present today in a given contactpool.
bool IsSurveyParticipant () const
Does this person participates in the social contact study?
void ParticipateInSurvey ()
Participate in social contact study and log person details.
void SetBelief (Belief *belief)
Set the beliefs. Pointer into Population's beliefcontainer.
void Update (bool isWorkOff, bool isSchoolOff, std::shared_ptr< TravellerProfile > travellerProfile, std::shared_ptr< Population > population, std::size_t)
Update the health status and presence in contactpools.
void Update (Person *p)
void SetAge (unsigned int newAge)
Set the age of the person.
unsigned int GetHouseholdId ()
void SetHouseholdId (unsigned int household_id)
unsigned int GetK12SchoolId () const
Returns the id of the K12School CP.
void SetK12SchoolId (unsigned int k12school_id)
Sets the id of the K12School CP.
unsigned int GetCollegeId () const
Returns the id of the College CP.
void SetCollegeId (unsigned int college_id)
Sets the id of the College CP.
unsigned int GetWorkId () const
Gets the id of the Work CP.
void SetWorkId (unsigned int work_id)
Sets the id of the Work CP.
unsigned int GetPrimaryCommunityId () const
Returns the id of the PrimaryCommunity CP.
void SetPrimaryCommunityId (unsigned int primary_community_id)
Sets the id of the PrimaryCommunity CP.
unsigned int GetSecondaryCommunityId () const
Returns the id of the SecondaryCommunity CP.
void SetSecondaryCommunityId (unsigned int secondary_community_id)
Sets the id of the SecondaryCommunity CP.
void SetPoolId (ContactPoolType::Id type, unsigned int poolId)
Sets the id of the type CP.
bool IsStudentCandidate () const
Returns whether this person may be a K12School student.
bool IsCollegeStudentCandidate () const
Returns whether this person may be a college student.
bool IsWorkableCandidate () const
Returns whether this person may be a college worker.
bool IsTravelling () const
Returns whether this person is travelling.
void SetTravelling (bool travelling)
Set the whether the person is travelling.
Public Attributes
friend TravellerIndex
Private Attributes
unsigned int m_id
The id.
double m_age
The age.
char m_gender
The gender.
Health m_health
Health info for this person.
bool m_is_participant
Is participating in the social contact study.
std::size_t m_region
The region.
ContactPoolType::IdSubscriptArray
< unsigned int > m_pool_ids
Is person present/absent in pools of each of the types (school, work, etc)?
ContactPoolType::IdSubscriptArray
< bool > m_in_pools
Belief * m_belief
Health beliefs related data (raw pointer intentional).
bool m_isTravelling = false
Whether this person is travelling.
Detailed Description
Store and handle person data.
Definition at line 39 of file Person.h.
Constructor & Destructor Documentation
stride::Person::Person () inline
Default construction (for population vector).
Definition at line 43 of file Person.h.
stride::Person::Person (unsigned int id, double age, unsigned int householdId, unsigned int k12SchoolId, unsigned int collegeId, unsigned int workId, unsigned int primaryCommunityId, unsigned int secondaryCommunityId, std::size_t region, Health health = Health(), double = 0, Belief * bp = nullptr) inline
Constructor: set the person data.
Definition at line 50 of file Person.h.
Member Function Documentation
bool stride::Person::operator!= (const Person & p) const inline
Is this person not equal to the given person?
Definition at line 61 of file Person.h.
References m_id.
double stride::Person::GetAge () const inline
Get the age.
Definition at line 64 of file Person.h.
References m_age.
Referenced by stride::LOG_POLICY< ContactLogMode::Id::All >::Contact(), stride::Immunizer< profile >::Random(), stride::DiseaseSeeder::Seed(), stride::SurveySeeder::Seed(), gengeopop::GeoGridJSONWriter::WritePerson(), and gengeopop::GeoGridProtoWriter::WritePerson().
Belief* stride::Person::GetBelief () inline
Return belief info.
Definition at line 67 of file Person.h.
References m_belief.
const Belief* stride::Person::GetBelief () const inline
Return belief info.
Definition at line 70 of file Person.h.
References m_belief.
unsigned int stride::Person::GetPoolId (const ContactPoolType::Id & poolType) const inline
Get ID of contactpool_type.
Definition at line 73 of file Person.h.
References m_pool_ids.
Referenced by GetCollegeId(), GetHouseholdId(), GetK12SchoolId(), GetPrimaryCommunityId(), GetSecondaryCommunityId(), GetWorkId(), stride::SurveySeeder::Seed(), and stride::ContactPool::Swap().
char stride::Person::GetGender () const inline
Return person's gender.
Definition at line 76 of file Person.h.
References m_gender.
Referenced by stride::SurveySeeder::Seed(), gengeopop::GeoGridJSONWriter::WritePerson(), and gengeopop::GeoGridProtoWriter::WritePerson().
Health& stride::Person::GetHealth () inline
Return person's health status.
Definition at line 79 of file Person.h.
References m_health.
Referenced by stride::LOG_POLICY< ContactLogMode::Id::Susceptibles >::Contact(), stride::Infector< LL, TIC, LIP, TO >::Exec(), stride::Infector< LL, TIC, NoLocalInformation, true >::Exec(), stride::Immunizer< profile >::Random(), and stride::DiseaseSeeder::Seed().
const Health& stride::Person::GetHealth () const inline
Return person's health status.
Definition at line 82 of file Person.h.
References m_health.
unsigned int stride::Person::GetId () const inline
Get the id.
Definition at line 85 of file Person.h.
References m_id.
Referenced by stride::LOG_POLICY< ContactLogMode::Id::All >::Contact(), stride::LOG_POLICY< ContactLogMode::Id::Susceptibles >::Contact(), gengeopop::GeoGridJSONReader::Read(), gengeopop::GeoGridProtoReader::Read(), stride::TravellerIndex::ReturnTravelers(), stride::DiseaseSeeder::Seed(), stride::SurveySeeder::Seed(), stride::TravellerIndex::StartTravel(), stride::LOG_POLICY< ContactLogMode::Id::Transmissions >::Trans(), stride::LOG_POLICY< ContactLogMode::Id::All >::Trans(), gengeopop::GeoGridProtoWriter::WritePerson(), and gengeopop::GeoGridJSONWriter::WritePerson().
void stride::Person::SetId (unsigned int id) inline
Set the id.
Definition at line 88 of file Person.h.
References m_id.
bool stride::Person::IsInPool (const ContactPoolType::Id poolType, unsigned int poolId) const
Check if a person is present today in a given contactpool.
When travelling we can't remove this person from it's original CP, since there is no efficient way to get a CP by its id. Hence this person will be in two CP's of type Work or PrimaryCommunity. When travelling the m_pool_ids[Work] or m_pool_ids[PrimaryCommunity] will be updated to the new CP in the other region. The m_in_pools will be set to false for all other CP's. This way the normal behaviour for m_in_pools can be used for Work or PrimaryCommunity. In order to simulate the removal of the original CP for work and PrimaryCommunity it's checked that the the CP is the CP this person is currently in. (Thus when travelling at the other region)
Definition at line 73 of file Person.cpp.
Referenced by stride::Infector< LL, TIC, LIP, TO >::Exec(), and stride::Infector< LL, TIC, NoLocalInformation, true >::Exec().
bool stride::Person::IsSurveyParticipant () const inline
Does this person participates in the social contact study?
Definition at line 94 of file Person.h.
References m_is_participant.
Referenced by stride::LOG_POLICY< ContactLogMode::Id::All >::Contact(), stride::LOG_POLICY< ContactLogMode::Id::Susceptibles >::Contact(), and stride::SurveySeeder::Seed().
void stride::Person::ParticipateInSurvey () inline
Participate in social contact study and log person details.
Definition at line 97 of file Person.h.
References m_is_participant.
Referenced by stride::SurveySeeder::Seed().
void stride::Person::SetBelief (Belief * belief) inline
Set the beliefs. Pointer into Population's beliefcontainer.
Definition at line 100 of file Person.h.
References m_belief.
void stride::Person::Update (bool isWorkOff, bool isSchoolOff, std::shared_ptr< TravellerProfile > travellerProfile, std::shared_ptr< Population > population, std::size_t currentDay)
Update the health status and presence in contactpools.
Definition at line 33 of file Person.cpp.
References stride::MinAdultAge().
void stride::Person::Update (Person * p)
Definition at line 64 of file Person.cpp.
void stride::Person::SetAge (unsigned int newAge)
Set the age of the person.
Definition at line 69 of file Person.cpp.
Referenced by gengeopop::HouseholdCSVReader::HouseholdCSVReader().
unsigned int stride::Person::GetHouseholdId () inline
Definition at line 112 of file Person.h.
References GetPoolId(), and stride::ContactPoolType::Household.
Referenced by gengeopop::GeoGridJSONWriter::WritePerson().
void stride::Person::SetHouseholdId (unsigned int household_id) inline
Definition at line 114 of file Person.h.
References stride::ContactPoolType::Household, and SetPoolId().
unsigned int stride::Person::GetK12SchoolId () const inline
Returns the id of the K12School CP.
Definition at line 117 of file Person.h.
References GetPoolId(), and stride::ContactPoolType::K12School.
Referenced by gengeopop::GeoGridJSONWriter::WritePerson().
void stride::Person::SetK12SchoolId (unsigned int k12school_id) inline
Sets the id of the K12School CP.
Definition at line 120 of file Person.h.
References stride::ContactPoolType::K12School, and SetPoolId().
unsigned int stride::Person::GetCollegeId () const inline
Returns the id of the College CP.
Definition at line 123 of file Person.h.
References stride::ContactPoolType::College, and GetPoolId().
Referenced by gengeopop::GeoGridJSONWriter::WritePerson().
void stride::Person::SetCollegeId (unsigned int college_id) inline
Sets the id of the College CP.
Definition at line 126 of file Person.h.
References stride::ContactPoolType::College, and SetPoolId().
unsigned int stride::Person::GetWorkId () const inline
Gets the id of the Work CP.
Definition at line 129 of file Person.h.
References GetPoolId(), and stride::ContactPoolType::Work.
Referenced by stride::TravellerProfile::PersonWillTravel(), and gengeopop::GeoGridJSONWriter::WritePerson().
void stride::Person::SetWorkId (unsigned int work_id) inline
Sets the id of the Work CP.
Definition at line 132 of file Person.h.
References SetPoolId(), and stride::ContactPoolType::Work.
Referenced by gengeopop::WorkplacePopulator::AssignActive().
unsigned int stride::Person::GetPrimaryCommunityId () const inline
Returns the id of the PrimaryCommunity CP.
Definition at line 135 of file Person.h.
References GetPoolId(), and stride::ContactPoolType::PrimaryCommunity.
Referenced by gengeopop::GeoGridJSONWriter::WritePerson().
void stride::Person::SetPrimaryCommunityId (unsigned int primary_community_id) inline
Sets the id of the PrimaryCommunity CP.
Definition at line 138 of file Person.h.
References stride::ContactPoolType::PrimaryCommunity, and SetPoolId().
unsigned int stride::Person::GetSecondaryCommunityId () const inline
Returns the id of the SecondaryCommunity CP.
Definition at line 144 of file Person.h.
References GetPoolId(), and stride::ContactPoolType::SecondaryCommunity.
Referenced by gengeopop::GeoGridJSONWriter::WritePerson().
void stride::Person::SetSecondaryCommunityId (unsigned int secondary_community_id) inline
Sets the id of the SecondaryCommunity CP.
Definition at line 147 of file Person.h.
References stride::ContactPoolType::SecondaryCommunity, and SetPoolId().
void stride::Person::SetPoolId (ContactPoolType::Id type, unsigned int poolId) inline
Sets the id of the type CP.
Definition at line 153 of file Person.h.
References m_in_pools, and m_pool_ids.
Referenced by SetCollegeId(), SetHouseholdId(), SetK12SchoolId(), SetPrimaryCommunityId(), SetSecondaryCommunityId(), and SetWorkId().
bool stride::Person::IsStudentCandidate () const inline
Returns whether this person may be a K12School student.
Definition at line 160 of file Person.h.
bool stride::Person::IsCollegeStudentCandidate () const inline
Returns whether this person may be a college student.
Definition at line 163 of file Person.h.
References m_age.
bool stride::Person::IsWorkableCandidate () const inline
Returns whether this person may be a college worker.
Definition at line 166 of file Person.h.
References m_age.
bool stride::Person::IsTravelling () const inline
Returns whether this person is travelling.
Definition at line 169 of file Person.h.
Referenced by stride::ContactPool::Swap().
void stride::Person::SetTravelling (bool travelling)
Set the whether the person is travelling.
Definition at line 71 of file Person.cpp.
Member Data Documentation
friend stride::Person::TravellerIndex
Definition at line 169 of file Person.h.
unsigned int stride::Person::m_id private
The id.
Definition at line 177 of file Person.h.
Referenced by GetId(), operator!=(), and SetId().
double stride::Person::m_age private
The age.
Definition at line 178 of file Person.h.
Referenced by GetAge(), IsCollegeStudentCandidate(), and IsWorkableCandidate().
char stride::Person::m_gender private
The gender.
Definition at line 179 of file Person.h.
Referenced by GetGender().
Health stride::Person::m_health private
Health info for this person.
Definition at line 180 of file Person.h.
Referenced by GetHealth().
bool stride::Person::m_is_participant private
Is participating in the social contact study.
Definition at line 181 of file Person.h.
Referenced by IsSurveyParticipant(), and ParticipateInSurvey().
std::size_t stride::Person::m_region private
The region.
Ids (school, work, etc) of pools you belong to Id value 0 means you do not belong to any pool of that type (e.g. school and work are mutually exclusive.
Definition at line 182 of file Person.h.
ContactPoolType::IdSubscriptArray<unsigned int> stride::Person::m_pool_ids private
Is person present/absent in pools of each of the types (school, work, etc)?
Definition at line 186 of file Person.h.
Referenced by GetPoolId(), stride::TravellerIndex::ReturnTravelers(), SetPoolId(), and stride::TravellerIndex::StartTravel().
ContactPoolType::IdSubscriptArray<bool> stride::Person::m_in_pools private
Definition at line 189 of file Person.h.
Referenced by stride::TravellerIndex::ReturnTravelers(), SetPoolId(), and stride::TravellerIndex::StartTravel().
Belief* stride::Person::m_belief private
Health beliefs related data (raw pointer intentional).
Definition at line 191 of file Person.h.
Referenced by GetBelief(), and SetBelief().
bool stride::Person::m_isTravelling = false private
Whether this person is travelling.
Definition at line 192 of file Person.h.
Referenced by stride::TravellerIndex::ReturnTravelers().
The documentation for this class was generated from the following files:
Person.h
Person.cpp