Stride Reference Manual: stride::viewers::MapViewer Class Reference
stride::viewers::MapViewer Class Reference
A Viewer that visually shows the GeoGrids and associated information with Qt.
#include <MapViewer.h>
Public Member Functions
MapViewer (std::shared_ptr< SimRunner > runner, std::shared_ptr< spdlog::logger > logger, QQmlApplicationEngine *engine=nullptr)
Instantiate cli viewer.
~MapViewer ()
Destructor.
void Update (const sim_event::Id id)
Let viewer perform update.
Private Attributes
std::shared_ptr< spdlog::logger > m_logger
The logger used for notifying that the MapViewer was updated.
bool m_first = true
A variable used to see if it was the first time the "Update" method was called.
std::unique_ptr< Map > m_vis
The Map to display.
std::shared_ptr< SimRunner > m_runner
The runner for the current simulation.
Detailed Description
A Viewer that visually shows the GeoGrids and associated information with Qt.
Definition at line 11 of file MapViewer.h.
Constructor & Destructor Documentation
stride::viewers::MapViewer::MapViewer (std::shared_ptr< SimRunner > runner, std::shared_ptr< spdlog::logger > logger, QQmlApplicationEngine * engine = nullptr) inline
Instantiate cli viewer.
Definition at line 15 of file MapViewer.h.
References m_runner, Update(), and ~MapViewer().
stride::viewers::MapViewer::~MapViewer ()
Destructor.
Definition at line 33 of file MapViewer.cpp.
Referenced by MapViewer().
Member Function Documentation
void stride::viewers::MapViewer::Update (const sim_event::Id id)
Let viewer perform update.
Definition at line 9 of file MapViewer.cpp.
References m_first, m_logger, m_runner, and m_vis.
Referenced by MapViewer().
Member Data Documentation
std::shared_ptr<spdlog::logger> stride::viewers::MapViewer::m_logger private
The logger used for notifying that the MapViewer was updated.
Definition at line 28 of file MapViewer.h.
Referenced by Update().
bool stride::viewers::MapViewer::m_first = true private
A variable used to see if it was the first time the "Update" method was called.
Definition at line 29 of file MapViewer.h.
Referenced by Update().
std::unique_ptr<Map> stride::viewers::MapViewer::m_vis private
The Map to display.
Definition at line 30 of file MapViewer.h.
Referenced by Update().
std::shared_ptr<SimRunner> stride::viewers::MapViewer::m_runner private
The runner for the current simulation.
Definition at line 31 of file MapViewer.h.
Referenced by MapViewer(), and Update().
The documentation for this class was generated from the following files:
MapViewer.h
MapViewer.cpp