Stride Reference Manual: stride::ContactPool Class Reference
stride::ContactPool Class Reference
Represents a group of Persons that potentially have contacts.
#include <ContactPool.h>
Public Types
using iterator = std::vector< stride::Person * >::iterator
using const_iterator = std::vector< stride::Person * >::const_iterator
Public Member Functions
ContactPool (std::size_t pool_id, ContactPoolType::Id type)
Initializing constructor.
ContactPool ()
void AddMember (const Person *p)
Add the given Person.
void AddExpat (const Person *p)
Add the given Person as an expat.
Person * GetMember (unsigned int index) const
Get member at index.
void RemoveMember (Person *pPerson)
Remove a member from the contactpool.
void RemoveExpat (Person *Person)
Remove an expat from the contactpool.
const std::vector< Person * > & GetPool () const
Get the entire pool of members.
std::size_t GetSize () const
Get size (number of members).
std::size_t GetId () const
Get the pool id.
std::size_t GetCapacity () const
Get the pool capacity.
std::size_t GetUsedCapacity () const
Get the pool used capacity, i.e. amount of members.
ContactPoolType::Id GetType () const
Get the type of ContactPool, used for logging and tests.
std::pair< std::size_t,
std::size_t > GetPopulationAndInfectedCount () const
Returns the amount of persons and amount of infected persons in this pool.
iterator begin ()
Iterator to first person.
iterator end ()
Iterator to end of persons.
const_iterator begin () const
Iterator to first person.
const_iterator end () const
Iterator to end of persons.
const_iterator cbegin () const
Iterator to first person.
const_iterator cend () const
Iterator to end of persons.
std::tuple< bool, size_t > SortMembers ()
Sort w.r.t. health status: order: exposed/infected/recovered, susceptible, immune.
Private Member Functions
void UpdateExpatsAfterRemoval (std::vector< Person * >::iterator itAfterRemovedPerson)
Update the m_expats data after removing a element from m_members itAfterRemovedPerson is the iterator returned by std::find or std::erase.
void Swap (std::size_t person1, std::size_t person2)
Swaps persons in m_members with the given index and updates the expats data if necessary.
Private Attributes
std::size_t m_pool_id
The ID of the ContactPool (for logging purposes).
ContactPoolType::Id m_pool_type
The type of the ContactPool (for logging purposes).
std::size_t m_index_immune
Index of the first immune member in the ContactPool.
std::vector< Person * > m_members
Pointers to contactpool members (raw pointers intentional).
std::size_t m_capacity
std::unordered_map< const
Person *, std::size_t > m_expats
Helper data structure for fast deletions of expats from m_members Can't keep them in the end of m_members and do a pop_back() since SortMembers will sort the members.
Friends
template<ContactLogMode::Id LL, bool TIC, typename LIP , bool TO>
class Infector
Infector calculates contacts and transmissions.
Detailed Description
Represents a group of Persons that potentially have contacts.
Definition at line 38 of file ContactPool.h.
Member Typedef Documentation
using stride::ContactPool::iterator = std::vector<stride::Person*>::iterator
Definition at line 41 of file ContactPool.h.
using stride::ContactPool::const_iterator = std::vector<stride::Person*>::const_iterator
Definition at line 42 of file ContactPool.h.
Constructor & Destructor Documentation
stride::ContactPool::ContactPool (std::size_t pool_id, ContactPoolType::Id type)
Initializing constructor.
Definition at line 32 of file ContactPool.cpp.
stride::ContactPool::ContactPool ()
Definition at line 37 of file ContactPool.cpp.
Member Function Documentation
void stride::ContactPool::AddMember (const Person * p)
Add the given Person.
Definition at line 39 of file ContactPool.cpp.
References m_index_immune, and m_members.
Referenced by AddExpat(), gengeopop::HouseholdPopulator::Apply(), gengeopop::HouseholdCSVReader::HouseholdCSVReader(), and gengeopop::GeoGridProtoReader::ParseContactPool().
void stride::ContactPool::AddExpat (const Person * p)
Add the given Person as an expat.
Definition at line 121 of file ContactPool.cpp.
References AddMember(), m_expats, and m_members.
Referenced by stride::TravellerIndex::StartTravel().
Person* stride::ContactPool::GetMember (unsigned int index) const inline
Get member at index.
Definition at line 56 of file ContactPool.h.
References m_members.
Referenced by stride::Immunizer< profile >::Random().
void stride::ContactPool::RemoveMember (Person * pPerson)
Remove a member from the contactpool.
Definition at line 99 of file ContactPool.cpp.
References m_members, and UpdateExpatsAfterRemoval().
void stride::ContactPool::RemoveExpat (Person * Person)
Remove an expat from the contactpool.
Definition at line 129 of file ContactPool.cpp.
References m_expats, m_members, and UpdateExpatsAfterRemoval().
Referenced by stride::TravellerIndex::ReturnTravelers().
const std::vector<Person*>& stride::ContactPool::GetPool () const inline
Get the entire pool of members.
Definition at line 65 of file ContactPool.h.
References m_members.
std::size_t stride::ContactPool::GetSize () const inline
Get size (number of members).
Definition at line 68 of file ContactPool.h.
References m_members.
Referenced by stride::Immunizer< profile >::Random().
std::size_t stride::ContactPool::GetId () const
Get the pool id.
Definition at line 81 of file ContactPool.cpp.
References m_pool_id.
Referenced by gengeopop::HouseholdPopulator::Apply(), stride::Infector< LL, TIC, LIP, TO >::Exec(), stride::Infector< LL, TIC, NoLocalInformation, true >::Exec(), gengeopop::GeoGridProtoReader::ParseContactPool(), stride::TravellerIndex::ReturnTravelers(), stride::TravellerIndex::StartTravel(), gengeopop::GeoGridProtoWriter::WriteContactPool(), and gengeopop::GeoGridJSONWriter::WriteContactPool().
std::size_t stride::ContactPool::GetCapacity () const
Get the pool capacity.
Definition at line 83 of file ContactPool.cpp.
References m_capacity.
std::size_t stride::ContactPool::GetUsedCapacity () const
Get the pool used capacity, i.e. amount of members.
Definition at line 85 of file ContactPool.cpp.
References m_members.
ContactPoolType::Id stride::ContactPool::GetType () const inline
Get the type of ContactPool, used for logging and tests.
Definition at line 80 of file ContactPool.h.
References m_pool_type.
std::pair< std::size_t, std::size_t > stride::ContactPool::GetPopulationAndInfectedCount () const
Returns the amount of persons and amount of infected persons in this pool.
Definition at line 87 of file ContactPool.cpp.
References m_members.
iterator stride::ContactPool::begin () inline
Iterator to first person.
Definition at line 86 of file ContactPool.h.
References m_members.
iterator stride::ContactPool::end () inline
Iterator to end of persons.
Definition at line 89 of file ContactPool.h.
References m_members.
const_iterator stride::ContactPool::begin () const inline
Iterator to first person.
Definition at line 92 of file ContactPool.h.
References cbegin().
const_iterator stride::ContactPool::end () const inline
Iterator to end of persons.
Definition at line 95 of file ContactPool.h.
References cend().
const_iterator stride::ContactPool::cbegin () const inline
Iterator to first person.
Definition at line 98 of file ContactPool.h.
References m_members.
Referenced by begin().
const_iterator stride::ContactPool::cend () const inline
Iterator to end of persons.
Definition at line 101 of file ContactPool.h.
References m_members.
Referenced by end().
std::tuple< bool, size_t > stride::ContactPool::SortMembers ()
Sort w.r.t. health status: order: exposed/infected/recovered, susceptible, immune.
Definition at line 45 of file ContactPool.cpp.
References m_index_immune, m_members, and Swap().
Referenced by stride::Infector< LL, TIC, NoLocalInformation, true >::Exec().
void stride::ContactPool::UpdateExpatsAfterRemoval (std::vector< Person * >::iterator itAfterRemovedPerson) private
Update the m_expats data after removing a element from m_members itAfterRemovedPerson is the iterator returned by std::find or std::erase.
Definition at line 110 of file ContactPool.cpp.
References m_expats, and m_members.
Referenced by RemoveExpat(), and RemoveMember().
void stride::ContactPool::Swap (std::size_t person1, std::size_t person2) private
Swaps persons in m_members with the given index and updates the expats data if necessary.
Definition at line 139 of file ContactPool.cpp.
References stride::Person::GetPoolId(), stride::Person::IsTravelling(), m_expats, m_members, m_pool_id, and m_pool_type.
Referenced by SortMembers().
Friends And Related Function Documentation
template<ContactLogMode::Id LL, bool TIC, typename LIP , bool TO> friend class Infector friend
Infector calculates contacts and transmissions.
Definition at line 109 of file ContactPool.h.
Member Data Documentation
std::size_t stride::ContactPool::m_pool_id private
The ID of the ContactPool (for logging purposes).
Definition at line 112 of file ContactPool.h.
Referenced by GetId(), and Swap().
ContactPoolType::Id stride::ContactPool::m_pool_type private
The type of the ContactPool (for logging purposes).
Definition at line 113 of file ContactPool.h.
Referenced by stride::Infector< LL, TIC, LIP, TO >::Exec(), stride::Infector< LL, TIC, NoLocalInformation, true >::Exec(), GetType(), and Swap().
std::size_t stride::ContactPool::m_index_immune private
Index of the first immune member in the ContactPool.
Definition at line 114 of file ContactPool.h.
Referenced by AddMember(), stride::Infector< LL, TIC, NoLocalInformation, true >::Exec(), and SortMembers().
std::vector<Person*> stride::ContactPool::m_members private
Pointers to contactpool members (raw pointers intentional).
Definition at line 115 of file ContactPool.h.
Referenced by AddExpat(), AddMember(), begin(), cbegin(), cend(), end(), stride::Infector< LL, TIC, LIP, TO >::Exec(), stride::Infector< LL, TIC, NoLocalInformation, true >::Exec(), GetMember(), GetPool(), GetPopulationAndInfectedCount(), GetSize(), GetUsedCapacity(), RemoveExpat(), RemoveMember(), SortMembers(), Swap(), and UpdateExpatsAfterRemoval().
std::size_t stride::ContactPool::m_capacity private
Definition at line 116 of file ContactPool.h.
Referenced by GetCapacity().
std::unordered_map<const Person*, std::size_t> stride::ContactPool::m_expats private
Helper data structure for fast deletions of expats from m_members Can't keep them in the end of m_members and do a pop_back() since SortMembers will sort the members.
Also can't prevent this from happening in SortMembers, since this would break the logic in Infector Will be updated in SortMembers.
Definition at line 122 of file ContactPool.h.
Referenced by AddExpat(), RemoveExpat(), Swap(), and UpdateExpatsAfterRemoval().
The documentation for this class was generated from the following files:
ContactPool.h
ContactPool.cpp