Stride Reference Manual: gengeopop::HouseholdCSVReader Class Reference
gengeopop::HouseholdCSVReader Class Reference
Create a Reader that retrieves the different Household profiles from a given CSV file.
#include <HouseholdCSVReader.h>
Public Member Functions
HouseholdCSVReader (std::unique_ptr< std::istream > inputStream)
Construct the HouseholdCSVReader with an istream containing the CSV data.
Public Member Functions inherited from gengeopop::HouseholdReader
HouseholdReader ()
Construct the HouseholdReader.
const std::vector
< std::shared_ptr< Household > > & GetHouseHolds () const
Return the Households found in the inputfile.
double GetFractionCompulsoryPupils () const
Returns the fraction of the population which are still of an age where they attend school.
double GetFraction1826Years () const
Returns the fraction of the population which are between 18 and 26 years of age.
double GetFraction1865Years () const
Returns the fraction of the population which are between 18 and 65 years of age.
unsigned int GetTotalPersonsInHouseholds () const
Returns the total amount of people in the found Households.
double AverageHouseholdSize () const
Returns the average size of a Household.
virtual ~HouseholdReader ()=default
Default destructor.
Private Attributes
stride::util::SegmentedVector
< stride::Person > m_persons
< Persons used in this Household, segmented vector to be able to have working pointers to it
stride::util::SegmentedVector
< stride::ContactPool > m_contactPools
Additional Inherited Members
Protected Attributes inherited from gengeopop::HouseholdReader
std::vector< std::shared_ptr
< Household > > m_households
The households which are (being) found.
unsigned int m_totalCompulsory = 0
The total amount of compulsory pupils.
unsigned int m_total1826Years = 0
The total amount of people between 18 and 26 years of age.
unsigned int m_total1865Years = 0
The total amount of people between 18 and 65 years of age.
unsigned int m_total = 0
The total population.
Detailed Description
Create a Reader that retrieves the different Household profiles from a given CSV file.
Definition at line 11 of file HouseholdCSVReader.h.
Constructor & Destructor Documentation
gengeopop::HouseholdCSVReader::HouseholdCSVReader (std::unique_ptr< std::istream > inputStream) explicit
Construct the HouseholdCSVReader with an istream containing the CSV data.
Definition at line 4 of file HouseholdCSVReader.cpp.
References stride::ContactPool::AddMember(), stride::util::SegmentedVector< T, N, Safe >::back(), stride::util::SegmentedVector< T, N, Safe >::emplace_back(), stride::ContactPoolType::Household, m_contactPools, gengeopop::HouseholdReader::m_households, m_persons, gengeopop::HouseholdReader::m_total, gengeopop::HouseholdReader::m_total1826Years, gengeopop::HouseholdReader::m_total1865Years, gengeopop::HouseholdReader::m_totalCompulsory, stride::util::SegmentedVector< T, N, Safe >::push_back(), and stride::Person::SetAge().
Member Data Documentation
stride::util::SegmentedVector<stride::Person> gengeopop::HouseholdCSVReader::m_persons private
< Persons used in this Household, segmented vector to be able to have working pointers to it
Contactpools used in this Household, segmented vector to be able to have working pointers to it
Definition at line 19 of file HouseholdCSVReader.h.
Referenced by HouseholdCSVReader().
stride::util::SegmentedVector<stride::ContactPool> gengeopop::HouseholdCSVReader::m_contactPools private
Definition at line 22 of file HouseholdCSVReader.h.
Referenced by HouseholdCSVReader().
The documentation for this class was generated from the following files:
HouseholdCSVReader.h
HouseholdCSVReader.cpp