Stride Reference Manual: GuiControllerBackend Class Reference
GuiControllerBackend Class Reference
A class used as a backend for the QML to provide simulation functionality.
#include <GuiControllerBackend.h>
Signals
void Stepped (unsigned int infectedCount, unsigned int day)
Signals QML components that a step in the simulation was completed.
Public Member Functions
GuiControllerBackend ()
Constructor.
~GuiControllerBackend ()
void SetRunner (std::shared_ptr< stride::SimRunner > runner)
Set the simulation runner. This is necessary for the GuiControllerBackend to operpat.
Q_INVOKABLE void StepDay ()
Step a day in the simulator, this will be done on a separate thread.
Q_INVOKABLE unsigned int GetInfectedCount ()
Query the simulation for the current infected count.
Q_INVOKABLE unsigned int GetDay ()
Get the current day in the simulation.
Private Slots
void UpdateViews (unsigned int infectedCount)
Called by the SimWorker to notify the backend that a step in the simulation was completed.
Private Attributes
std::shared_ptr
< stride::SimRunner > m_runner
The simulation runner.
std::shared_ptr< QThread > m_thread
A thread for the SimWorker to run in.
unsigned int m_day
The current day in the simulation.
Detailed Description
A class used as a backend for the QML to provide simulation functionality.
Definition at line 9 of file GuiControllerBackend.h.
Constructor & Destructor Documentation
GuiControllerBackend::GuiControllerBackend ()
Constructor.
Definition at line 8 of file GuiControllerBackend.cpp.
GuiControllerBackend::~GuiControllerBackend ()
Definition at line 37 of file GuiControllerBackend.cpp.
References m_thread.
Member Function Documentation
void GuiControllerBackend::SetRunner (std::shared_ptr< stride::SimRunner > runner)
Set the simulation runner. This is necessary for the GuiControllerBackend to operpat.
Definition at line 10 of file GuiControllerBackend.cpp.
References m_runner.
Referenced by stride::GuiController::GuiController().
void GuiControllerBackend::StepDay ()
Step a day in the simulator, this will be done on a separate thread.
Definition at line 12 of file GuiControllerBackend.cpp.
References m_day, m_runner, m_thread, UpdateViews(), stride::SimWorker::Work(), and stride::SimWorker::Worked().
unsigned int GuiControllerBackend::GetInfectedCount ()
Query the simulation for the current infected count.
Definition at line 28 of file GuiControllerBackend.cpp.
References m_runner.
unsigned int GuiControllerBackend::GetDay ()
Get the current day in the simulation.
Definition at line 34 of file GuiControllerBackend.cpp.
References m_day.
void GuiControllerBackend::UpdateViews (unsigned int infectedCount) private slot
Called by the SimWorker to notify the backend that a step in the simulation was completed.
Definition at line 36 of file GuiControllerBackend.cpp.
References m_day, and Stepped().
Referenced by StepDay().
void GuiControllerBackend::Stepped (unsigned int infectedCount, unsigned int day) signal
Signals QML components that a step in the simulation was completed.
Referenced by UpdateViews().
Member Data Documentation
std::shared_ptr<stride::SimRunner> GuiControllerBackend::m_runner private
The simulation runner.
Definition at line 38 of file GuiControllerBackend.h.
Referenced by GetInfectedCount(), SetRunner(), and StepDay().
std::shared_ptr<QThread> GuiControllerBackend::m_thread private
A thread for the SimWorker to run in.
Definition at line 39 of file GuiControllerBackend.h.
Referenced by StepDay(), and ~GuiControllerBackend().
unsigned int GuiControllerBackend::m_day private
The current day in the simulation.
Definition at line 40 of file GuiControllerBackend.h.
Referenced by GetDay(), StepDay(), and UpdateViews().
The documentation for this class was generated from the following files:
GuiControllerBackend.h
GuiControllerBackend.cpp