#pragma once

#include "PartialPopulator.h"

namespace gengeopop {

/// Add population to a GeoGrid out of PartionPopulators (analog to GeoGridGenerator)
class GeoGridPopulator
{
public:
        /// Construct with a config and a target GeoGrid
        GeoGridPopulator(GeoGridConfig& geoGridConfig, std::shared_ptr<GeoGrid> geoGrid);

        /// Add a PartialPopulator to use when populating
        void AddPartialPopulator(std::shared_ptr<PartialPopulator> gen);

        /**
         * @param filename Filename with the config of the wanted geogrid.
         * @return The GeoGrid that was generated by applying all partial populators onto an empty GeoGrid object.
         */
        void PopulateGeoGrid();

        /// Get the target GeoGrid
        std::shared_ptr<GeoGrid> GetGeoGrid();

private:
        std::vector<std::shared_ptr<PartialPopulator>> m_partialPopulators; ///< Our PartialPopulators
        std::shared_ptr<GeoGrid>                       m_geoGrid;           ///< The target
        GeoGridConfig                                  m_geoGridConfig;     ///< The config
};
} // namespace gengeopop
