Stride Reference Manual: Launcher Class Reference
Launcher Class Reference
Represents the current set data for the launch.
#include <Launcher.h>
Public Member Functions
Launcher ()
Create a Launcher.
Launcher (const Launcher &b)=delete
Launcher & operator= (const Launcher &b)=delete
Q_INVOKABLE void SetConfigPath (QString string)
Load the configuration from the provided path.
Q_INVOKABLE void SaveConfig (QString string)
Save the configuration stored in the ConfigForm to the provided filename.
Q_INVOKABLE void SetConfig (bool showMapViewer, bool showAdoptedViewer, bool showCliViewer, bool showInfectedViewer, bool showPersonsViewer, bool showSummaryViewer)
Set the enabled and disabled Viewers to be used in the simulation.
Q_INVOKABLE void SetController (int index)
Sets the controller type we will use after launch.
Q_INVOKABLE void Launch ()
Launch the simulation with the stored configuration.
void SetRootObject (QObject *rootObject)
Set the Qt RootObject.
Q_INVOKABLE void SetToLaunch ()
Set if the Launcher has to actually launch or not.
Q_INVOKABLE void UpdatePtree ()
Updates the locally stored Boost Property Tree with the information in the QML forms.
Private Member Functions
void UpdateConfigForm ()
Updates the information in the QML forms with what is stored in the Boost Property Tree.
void LoadComboBox (QObject *comboBox, const char *value)
Sets the value of the provided ComboBox to the provided value.
Private Attributes
std::string m_configPath
The path of the configuration file.
bool m_showMapViewer = false
Show the MapViewer?
bool m_showAdoptedViewer = false
Show the AdoptedViewer?
bool m_showCliViewer = false
Show the CliViewer?
bool m_showInfectedViewer = false
Show the InfectedViewer?
bool m_showPersonsViewer = false
Show the PersonsViewer?
bool m_showSummaryViewer = false
Show the SummaryViewer?
int m_controller = 0
boost::property_tree::ptree m_configPt
The Property Tree loaded from m_configPath.
QObject * m_rootObject = nullptr
The Gui RootObject, for querying QML objects.
bool m_setToLaunch = false
Does the simulation have to launch?
struct {
QObject * ageContactMatrixFile = nullptr
QObject * behaviourPolicy = nullptr
QObject * beliefPolicy = nullptr
QObject * contactLogLevel = nullptr
QObject * diseaseConfigFile = nullptr
QObject * globalInformationPolicy = nullptr
QObject * holidaysFile = nullptr
QObject * immunityProfile = nullptr
QObject * immunityRate = nullptr
QObject * localInformationPolicy = nullptr
QObject * numDays = nullptr
QObject * numberParticipantsSurvey = nullptr
QObject * outputAdopted = nullptr
QObject * outputCases = nullptr
QObject * outputPersons = nullptr
QObject * outputPrefix = nullptr
QObject * outputSummary = nullptr
QObject * numThreads = nullptr
QObject * populationFile = nullptr
QObject * rngSeed = nullptr
QObject * rngType = nullptr
QObject * r0 = nullptr
QObject * seedingAgeMax = nullptr
QObject * seedingAgeMin = nullptr
QObject * seedingRate = nullptr
QObject * startDate = nullptr
QObject * strideLogLevel = nullptr
QObject * trackIndexCase = nullptr
QObject * vaccineLinkProbability = nullptr
QObject * vaccineProfile = nullptr
QObject * vaccineRate = nullptr
QObject * geopopType = nullptr
QObject * geopopFile = nullptr
QObject * geopopPopulationSize = nullptr
QObject * geopopFraction1826Students = nullptr
QObject * geopopFractionActiveCommuting = nullptr
QObject * geopopFactionStudentCommuting = nullptr
QObject * geopopFraction1865YearsActive = nullptr
QObject * geopopCities = nullptr
QObject * geopopCommuting = nullptr
QObject * geopopHousehold = nullptr
QObject * geopopSubmunicipalities = nullptr
} m_configEditor
The form objects in the QML that store the config.
Detailed Description
Represents the current set data for the launch.
Config files etc. It also serves as a backend for loading and storing the configuration from xml files.
Definition at line 11 of file Launcher.h.
Constructor & Destructor Documentation
Launcher::Launcher ()
Create a Launcher.
Definition at line 21 of file Launcher.cpp.
Launcher::Launcher (const Launcher & b) delete
Member Function Documentation
Launcher& Launcher::operator= (const Launcher & b) delete
void Launcher::SetConfigPath (QString string)
Load the configuration from the provided path.
This updates the ConfigForm.
Definition at line 88 of file Launcher.cpp.
References m_configPath, m_configPt, stride::util::FileSys::ReadPtreeFile(), and UpdateConfigForm().
void Launcher::SaveConfig (QString string)
Save the configuration stored in the ConfigForm to the provided filename.
It requires the string to start with file://.
Definition at line 381 of file Launcher.cpp.
References m_configPt, UpdatePtree(), and stride::util::FileSys::WritePtreeFile().
void Launcher::SetConfig (bool showMapViewer, bool showAdoptedViewer, bool showCliViewer, bool showInfectedViewer, bool showPersonsViewer, bool showSummaryViewer)
Set the enabled and disabled Viewers to be used in the simulation.
Definition at line 96 of file Launcher.cpp.
References m_showAdoptedViewer, m_showCliViewer, m_showInfectedViewer, m_showMapViewer, m_showPersonsViewer, and m_showSummaryViewer.
void Launcher::SetController (int index)
Sets the controller type we will use after launch.
Parameters
index 0 = Cli, 1 = GUI
Definition at line 107 of file Launcher.cpp.
References m_controller.
void Launcher::Launch ()
Launch the simulation with the stored configuration.
This requires the QGuiApplication to already be closed
Definition at line 23 of file Launcher.cpp.
References stride::BaseController::Control(), stride::BaseController::GetLogger(), stride::BaseController::GetOutputPrefix(), m_configPt, m_controller, m_setToLaunch, m_showAdoptedViewer, m_showCliViewer, m_showInfectedViewer, m_showMapViewer, m_showPersonsViewer, m_showSummaryViewer, stride::BaseController::RegisterViewer(), and stride::util::TimeStamp::ToTag().
Referenced by LaunchGui().
void Launcher::SetRootObject (QObject * rootObject)
Set the Qt RootObject.
This is needed to interact with the QML forms. This should be set by the owner of this object after loading the QML.
Definition at line 322 of file Launcher.cpp.
References m_configEditor.
Referenced by LaunchGui().
void Launcher::SetToLaunch ()
Set if the Launcher has to actually launch or not.
If Launch() is called without calling this first, nothing happens. This is to make sure the simulation is only launched when actually pressing the "Launch" button in the Gui and not just closing the Launcher.
Definition at line 390 of file Launcher.cpp.
References m_setToLaunch.
void Launcher::UpdatePtree ()
Updates the locally stored Boost Property Tree with the information in the QML forms.
This is called from the QML when changes are detected.
Definition at line 199 of file Launcher.cpp.
References m_configEditor, and m_configPt.
Referenced by SaveConfig().
void Launcher::UpdateConfigForm () private
Updates the information in the QML forms with what is stored in the Boost Property Tree.
Definition at line 109 of file Launcher.cpp.
References LoadComboBox(), m_configEditor, and m_configPt.
Referenced by SetConfigPath().
void Launcher::LoadComboBox (QObject * comboBox, const char * value) private
Sets the value of the provided ComboBox to the provided value.
Definition at line 371 of file Launcher.cpp.
Referenced by UpdateConfigForm().
Member Data Documentation
std::string Launcher::m_configPath private
The path of the configuration file.
Definition at line 89 of file Launcher.h.
Referenced by SetConfigPath().
bool Launcher::m_showMapViewer = false private
Show the MapViewer?
Definition at line 90 of file Launcher.h.
Referenced by Launch(), and SetConfig().
bool Launcher::m_showAdoptedViewer = false private
Show the AdoptedViewer?
Definition at line 91 of file Launcher.h.
Referenced by Launch(), and SetConfig().
bool Launcher::m_showCliViewer = false private
Show the CliViewer?
Definition at line 92 of file Launcher.h.
Referenced by Launch(), and SetConfig().
bool Launcher::m_showInfectedViewer = false private
Show the InfectedViewer?
Definition at line 93 of file Launcher.h.
Referenced by Launch(), and SetConfig().
bool Launcher::m_showPersonsViewer = false private
Show the PersonsViewer?
Definition at line 94 of file Launcher.h.
Referenced by Launch(), and SetConfig().
bool Launcher::m_showSummaryViewer = false private
Show the SummaryViewer?
Definition at line 95 of file Launcher.h.
Referenced by Launch(), and SetConfig().
int Launcher::m_controller = 0 private
Definition at line 97 of file Launcher.h.
Referenced by Launch(), and SetController().
boost::property_tree::ptree Launcher::m_configPt private
The Property Tree loaded from m_configPath.
Definition at line 99 of file Launcher.h.
Referenced by Launch(), SaveConfig(), SetConfigPath(), UpdateConfigForm(), and UpdatePtree().
QObject* Launcher::m_rootObject = nullptr private
The Gui RootObject, for querying QML objects.
Definition at line 101 of file Launcher.h.
bool Launcher::m_setToLaunch = false private
Does the simulation have to launch?
Definition at line 103 of file Launcher.h.
Referenced by Launch(), and SetToLaunch().
QObject* Launcher::ageContactMatrixFile = nullptr
Definition at line 106 of file Launcher.h.
QObject* Launcher::behaviourPolicy = nullptr
Definition at line 107 of file Launcher.h.
QObject* Launcher::beliefPolicy = nullptr
Definition at line 108 of file Launcher.h.
QObject* Launcher::contactLogLevel = nullptr
Definition at line 109 of file Launcher.h.
QObject* Launcher::diseaseConfigFile = nullptr
Definition at line 110 of file Launcher.h.
QObject* Launcher::globalInformationPolicy = nullptr
Definition at line 111 of file Launcher.h.
QObject* Launcher::holidaysFile = nullptr
Definition at line 112 of file Launcher.h.
QObject* Launcher::immunityProfile = nullptr
Definition at line 113 of file Launcher.h.
QObject* Launcher::immunityRate = nullptr
Definition at line 114 of file Launcher.h.
QObject* Launcher::localInformationPolicy = nullptr
Definition at line 115 of file Launcher.h.
QObject* Launcher::numDays = nullptr
Definition at line 116 of file Launcher.h.
QObject* Launcher::numberParticipantsSurvey = nullptr
Definition at line 117 of file Launcher.h.
QObject* Launcher::outputAdopted = nullptr
Definition at line 118 of file Launcher.h.
QObject* Launcher::outputCases = nullptr
Definition at line 119 of file Launcher.h.
QObject* Launcher::outputPersons = nullptr
Definition at line 120 of file Launcher.h.
QObject* Launcher::outputPrefix = nullptr
Definition at line 121 of file Launcher.h.
QObject* Launcher::outputSummary = nullptr
Definition at line 122 of file Launcher.h.
QObject* Launcher::numThreads = nullptr
Definition at line 123 of file Launcher.h.
QObject* Launcher::populationFile = nullptr
Definition at line 124 of file Launcher.h.
QObject* Launcher::rngSeed = nullptr
Definition at line 125 of file Launcher.h.
QObject* Launcher::rngType = nullptr
Definition at line 126 of file Launcher.h.
QObject* Launcher::r0 = nullptr
Definition at line 127 of file Launcher.h.
QObject* Launcher::seedingAgeMax = nullptr
Definition at line 128 of file Launcher.h.
QObject* Launcher::seedingAgeMin = nullptr
Definition at line 129 of file Launcher.h.
QObject* Launcher::seedingRate = nullptr
Definition at line 130 of file Launcher.h.
QObject* Launcher::startDate = nullptr
Definition at line 131 of file Launcher.h.
QObject* Launcher::strideLogLevel = nullptr
Definition at line 132 of file Launcher.h.
QObject* Launcher::trackIndexCase = nullptr
Definition at line 133 of file Launcher.h.
QObject* Launcher::vaccineLinkProbability = nullptr
Definition at line 134 of file Launcher.h.
QObject* Launcher::vaccineProfile = nullptr
Definition at line 135 of file Launcher.h.
QObject* Launcher::vaccineRate = nullptr
Definition at line 136 of file Launcher.h.
QObject* Launcher::geopopType = nullptr
Definition at line 137 of file Launcher.h.
QObject* Launcher::geopopFile = nullptr
Definition at line 138 of file Launcher.h.
QObject* Launcher::geopopPopulationSize = nullptr
Definition at line 139 of file Launcher.h.
QObject* Launcher::geopopFraction1826Students = nullptr
Definition at line 140 of file Launcher.h.
QObject* Launcher::geopopFractionActiveCommuting = nullptr
Definition at line 141 of file Launcher.h.
QObject* Launcher::geopopFactionStudentCommuting = nullptr
Definition at line 142 of file Launcher.h.
QObject* Launcher::geopopFraction1865YearsActive = nullptr
Definition at line 143 of file Launcher.h.
QObject* Launcher::geopopCities = nullptr
Definition at line 144 of file Launcher.h.
QObject* Launcher::geopopCommuting = nullptr
Definition at line 145 of file Launcher.h.
QObject* Launcher::geopopHousehold = nullptr
Definition at line 146 of file Launcher.h.
QObject* Launcher::geopopSubmunicipalities = nullptr
Definition at line 147 of file Launcher.h.
struct { ... } Launcher::m_configEditor
The form objects in the QML that store the config.
Referenced by SetRootObject(), UpdateConfigForm(), and UpdatePtree().
The documentation for this class was generated from the following files:
Launcher.h
Launcher.cpp