Stride Reference Manual: stride::GenPopBuilder Class Reference
stride::GenPopBuilder Class Reference
Initializes Population objects.
#include <GenPopBuilder.h>
Public Member Functions
std::shared_ptr< Population > Build (std::shared_ptr< Population > pop, std::size_t regionId, std::string regionName)
Creates a population by generating it.
Public Member Functions inherited from stride::AbstractPopBuilder
AbstractPopBuilder (const boost::property_tree::ptree &configPt, const boost::property_tree::ptree &regionPt, util::RNManager &rnManager)
Initializing constructor.
virtual ~AbstractPopBuilder ()
Additional Inherited Members
Protected Attributes inherited from stride::AbstractPopBuilder
const boost::property_tree::ptree & m_config_pt
Configuration property tree.
const boost::property_tree::ptree & m_region_pt
Configuration property tree of the region.
util::RNManager & m_rn_manager
Random number generation management.
Detailed Description
Initializes Population objects.
Definition at line 36 of file GenPopBuilder.h.
Member Function Documentation
shared_ptr< Population > stride::GenPopBuilder::Build (std::shared_ptr< Population > pop, std::size_t regionId, std::string regionName) virtual
Creates a population by generating it.
Implements stride::AbstractPopBuilder.
Definition at line 44 of file GenPopBuilder.cpp.
References gengeopop::GenGeoPopController::GenGeo(), gengeopop::GenGeoPopController::GenPop(), gengeopop::GenGeoPopController::GetGeoGrid(), gengeopop::GeoGridConfig::input, gengeopop::GeoGridConfig::populationSize, gengeopop::GenGeoPopController::ReadDataFiles(), and gengeopop::GenGeoPopController::UsePopulation().
Referenced by stride::Population::CreateRegion().
The documentation for this class was generated from the following files:
GenPopBuilder.h
GenPopBuilder.cpp