Stride Reference Manual: proto::GeoGrid_Location_Coordinate Class Reference
proto::GeoGrid_Location_Coordinate Class Reference
#include <geogrid.pb.h>
Public Member Functions
GeoGrid_Location_Coordinate ()
virtual ~GeoGrid_Location_Coordinate ()
GeoGrid_Location_Coordinate (const GeoGrid_Location_Coordinate &from)
GeoGrid_Location_Coordinate & operator= (const GeoGrid_Location_Coordinate &from)
const
::google::protobuf::UnknownFieldSet & unknown_fields () const
inline::google::protobuf::UnknownFieldSet * mutable_unknown_fields ()
void Swap (GeoGrid_Location_Coordinate *other)
GeoGrid_Location_Coordinate * New () const PROTOBUF_FINAL
GeoGrid_Location_Coordinate * New (::google::protobuf::Arena *arena) const PROTOBUF_FINAL
void CopyFrom (const ::google::protobuf::Message &from) PROTOBUF_FINAL
void MergeFrom (const ::google::protobuf::Message &from) PROTOBUF_FINAL
void CopyFrom (const GeoGrid_Location_Coordinate &from)
void MergeFrom (const GeoGrid_Location_Coordinate &from)
void Clear () PROTOBUF_FINAL
bool IsInitialized () const PROTOBUF_FINAL
size_t ByteSizeLong () const PROTOBUF_FINAL
bool MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream *input) PROTOBUF_FINAL
void SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream *output) const PROTOBUF_FINAL
::google::protobuf::uint8 * InternalSerializeWithCachedSizesToArray (bool deterministic,::google::protobuf::uint8 *target) const PROTOBUF_FINAL
int GetCachedSize () const PROTOBUF_FINAL
::google::protobuf::Metadata GetMetadata () const PROTOBUF_FINAL
bool has_x () const
void clear_x ()
double x () const
void set_x (double value)
bool has_y () const
void clear_y ()
double y () const
void set_y (double value)
bool has_longitude () const
void clear_longitude ()
double longitude () const
void set_longitude (double value)
bool has_latitude () const
void clear_latitude ()
double latitude () const
void set_latitude (double value)
Static Public Member Functions
static const
::google::protobuf::Descriptor * descriptor ()
static const
GeoGrid_Location_Coordinate & default_instance ()
static void InitAsDefaultInstance ()
static const
GeoGrid_Location_Coordinate * internal_default_instance ()
Static Public Attributes
static PROTOBUF_CONSTEXPR int const kIndexInFileMessages
static const int kXFieldNumber = 1
static const int kYFieldNumber = 2
static const int kLongitudeFieldNumber = 3
static const int kLatitudeFieldNumber = 4
Private Member Functions
void SharedCtor ()
void SharedDtor ()
void SetCachedSize (int size) const PROTOBUF_FINAL
void InternalSwap (GeoGrid_Location_Coordinate *other)
inline::google::protobuf::Arena * GetArenaNoVirtual () const
void * MaybeArenaPtr () const
void set_has_x ()
void clear_has_x ()
void set_has_y ()
void clear_has_y ()
void set_has_longitude ()
void clear_has_longitude ()
void set_has_latitude ()
void clear_has_latitude ()
size_t RequiredFieldsByteSizeFallback () const
friend void::protobuf_geogrid_2eproto::InitDefaultsGeoGrid_Location_CoordinateImpl ()
Private Attributes
::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_
::google::protobuf::internal::HasBits< 1 > _has_bits_
int _cached_size_
double x_
double y_
double longitude_
double latitude_
Friends
struct ::protobuf_geogrid_2eproto::TableStruct
void swap (GeoGrid_Location_Coordinate &a, GeoGrid_Location_Coordinate &b)
Detailed Description
Definition at line 121 of file geogrid.pb.h.
Constructor & Destructor Documentation
proto::GeoGrid_Location_Coordinate::GeoGrid_Location_Coordinate ()
virtual proto::GeoGrid_Location_Coordinate::~GeoGrid_Location_Coordinate () virtual
proto::GeoGrid_Location_Coordinate::GeoGrid_Location_Coordinate (const GeoGrid_Location_Coordinate & from)
Member Function Documentation
GeoGrid_Location_Coordinate& proto::GeoGrid_Location_Coordinate::operator= (const GeoGrid_Location_Coordinate & from) inline
Definition at line 128 of file geogrid.pb.h.
References CopyFrom().
const ::google::protobuf::UnknownFieldSet& proto::GeoGrid_Location_Coordinate::unknown_fields () const inline
Definition at line 147 of file geogrid.pb.h.
References _internal_metadata_.
inline ::google::protobuf::UnknownFieldSet* proto::GeoGrid_Location_Coordinate::mutable_unknown_fields () inline
Definition at line 150 of file geogrid.pb.h.
References _internal_metadata_.
static const ::google::protobuf::Descriptor* proto::GeoGrid_Location_Coordinate::descriptor () static
static const GeoGrid_Location_Coordinate& proto::GeoGrid_Location_Coordinate::default_instance () static
static void proto::GeoGrid_Location_Coordinate::InitAsDefaultInstance () static
static const GeoGrid_Location_Coordinate* proto::GeoGrid_Location_Coordinate::internal_default_instance () inline static
Definition at line 158 of file geogrid.pb.h.
References proto::_GeoGrid_Location_Coordinate_default_instance_.
void proto::GeoGrid_Location_Coordinate::Swap (GeoGrid_Location_Coordinate * other)
GeoGrid_Location_Coordinate* proto::GeoGrid_Location_Coordinate::New () const inline
Definition at line 172 of file geogrid.pb.h.
References New().
Referenced by New().
GeoGrid_Location_Coordinate* proto::GeoGrid_Location_Coordinate::New (::google::protobuf::Arena * arena) const
void proto::GeoGrid_Location_Coordinate::CopyFrom (const ::google::protobuf::Message & from)
Referenced by operator=(), proto::GeoGrid_Location_ContactCenter_ContactPool::operator=(), proto::GeoGrid_Location_ContactCenter::operator=(), proto::GeoGrid_Location_Commute::operator=(), proto::GeoGrid_Location::operator=(), proto::GeoGrid_Person::operator=(), and proto::GeoGrid::operator=().
void proto::GeoGrid_Location_Coordinate::MergeFrom (const ::google::protobuf::Message & from)
void proto::GeoGrid_Location_Coordinate::CopyFrom (const GeoGrid_Location_Coordinate & from)
void proto::GeoGrid_Location_Coordinate::MergeFrom (const GeoGrid_Location_Coordinate & from)
void proto::GeoGrid_Location_Coordinate::Clear ()
bool proto::GeoGrid_Location_Coordinate::IsInitialized () const
size_t proto::GeoGrid_Location_Coordinate::ByteSizeLong () const
bool proto::GeoGrid_Location_Coordinate::MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream * input)
void proto::GeoGrid_Location_Coordinate::SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream * output) const
::google::protobuf::uint8* proto::GeoGrid_Location_Coordinate::InternalSerializeWithCachedSizesToArray (bool deterministic, ::google::protobuf::uint8 * target) const
int proto::GeoGrid_Location_Coordinate::GetCachedSize () const inline
Definition at line 189 of file geogrid.pb.h.
References _cached_size_.
void proto::GeoGrid_Location_Coordinate::SharedCtor () private
void proto::GeoGrid_Location_Coordinate::SharedDtor () private
void proto::GeoGrid_Location_Coordinate::SetCachedSize (int size) const private
void proto::GeoGrid_Location_Coordinate::InternalSwap (GeoGrid_Location_Coordinate * other) private
inline ::google::protobuf::Arena* proto::GeoGrid_Location_Coordinate::GetArenaNoVirtual () const inline private
Definition at line 196 of file geogrid.pb.h.
Referenced by proto::GeoGrid_Location::set_allocated_coordinate().
void* proto::GeoGrid_Location_Coordinate::MaybeArenaPtr () const inline private
Definition at line 199 of file geogrid.pb.h.
::google::protobuf::Metadata proto::GeoGrid_Location_Coordinate::GetMetadata () const
bool proto::GeoGrid_Location_Coordinate::has_x () const inline
Definition at line 1170 of file geogrid.pb.h.
void proto::GeoGrid_Location_Coordinate::clear_x () inline
Definition at line 1179 of file geogrid.pb.h.
References clear_has_x().
double proto::GeoGrid_Location_Coordinate::x () const inline
Definition at line 1183 of file geogrid.pb.h.
References x_.
Referenced by gengeopop::GeoGridProtoReader::ParseCoordinate().
void proto::GeoGrid_Location_Coordinate::set_x (double value) inline
Definition at line 1187 of file geogrid.pb.h.
References set_has_x().
Referenced by gengeopop::GeoGridProtoWriter::WriteCoordinate().
bool proto::GeoGrid_Location_Coordinate::has_y () const inline
Definition at line 1194 of file geogrid.pb.h.
void proto::GeoGrid_Location_Coordinate::clear_y () inline
Definition at line 1203 of file geogrid.pb.h.
References clear_has_y().
double proto::GeoGrid_Location_Coordinate::y () const inline
Definition at line 1207 of file geogrid.pb.h.
References y_.
Referenced by gengeopop::GeoGridProtoReader::ParseCoordinate().
void proto::GeoGrid_Location_Coordinate::set_y (double value) inline
Definition at line 1211 of file geogrid.pb.h.
References set_has_y().
Referenced by gengeopop::GeoGridProtoWriter::WriteCoordinate().
bool proto::GeoGrid_Location_Coordinate::has_longitude () const inline
Definition at line 1218 of file geogrid.pb.h.
void proto::GeoGrid_Location_Coordinate::clear_longitude () inline
Definition at line 1227 of file geogrid.pb.h.
References clear_has_longitude().
double proto::GeoGrid_Location_Coordinate::longitude () const inline
Definition at line 1231 of file geogrid.pb.h.
References longitude_.
Referenced by gengeopop::GeoGridProtoReader::ParseCoordinate().
void proto::GeoGrid_Location_Coordinate::set_longitude (double value) inline
Definition at line 1235 of file geogrid.pb.h.
References set_has_longitude().
Referenced by gengeopop::GeoGridProtoWriter::WriteCoordinate().
bool proto::GeoGrid_Location_Coordinate::has_latitude () const inline
Definition at line 1242 of file geogrid.pb.h.
void proto::GeoGrid_Location_Coordinate::clear_latitude () inline
Definition at line 1251 of file geogrid.pb.h.
References clear_has_latitude().
double proto::GeoGrid_Location_Coordinate::latitude () const inline
Definition at line 1255 of file geogrid.pb.h.
References latitude_.
Referenced by gengeopop::GeoGridProtoReader::ParseCoordinate().
void proto::GeoGrid_Location_Coordinate::set_latitude (double value) inline
Definition at line 1259 of file geogrid.pb.h.
References set_has_latitude().
Referenced by gengeopop::GeoGridProtoWriter::WriteCoordinate().
void proto::GeoGrid_Location_Coordinate::set_has_x () inline private
Definition at line 1173 of file geogrid.pb.h.
Referenced by set_x().
void proto::GeoGrid_Location_Coordinate::clear_has_x () inline private
Definition at line 1176 of file geogrid.pb.h.
Referenced by clear_x().
void proto::GeoGrid_Location_Coordinate::set_has_y () inline private
Definition at line 1197 of file geogrid.pb.h.
Referenced by set_y().
void proto::GeoGrid_Location_Coordinate::clear_has_y () inline private
Definition at line 1200 of file geogrid.pb.h.
Referenced by clear_y().
void proto::GeoGrid_Location_Coordinate::set_has_longitude () inline private
Definition at line 1221 of file geogrid.pb.h.
Referenced by set_longitude().
void proto::GeoGrid_Location_Coordinate::clear_has_longitude () inline private
Definition at line 1224 of file geogrid.pb.h.
Referenced by clear_longitude().
void proto::GeoGrid_Location_Coordinate::set_has_latitude () inline private
Definition at line 1245 of file geogrid.pb.h.
Referenced by set_latitude().
void proto::GeoGrid_Location_Coordinate::clear_has_latitude () inline private
Definition at line 1248 of file geogrid.pb.h.
Referenced by clear_latitude().
size_t proto::GeoGrid_Location_Coordinate::RequiredFieldsByteSizeFallback () const private
proto::GeoGrid_Location_Coordinate::void::protobuf_geogrid_2eproto::InitDefaultsGeoGrid_Location_CoordinateImpl () private
Friends And Related Function Documentation
friend struct ::protobuf_geogrid_2eproto::TableStruct friend
Definition at line 259 of file geogrid.pb.h.
void swap (GeoGrid_Location_Coordinate & a, GeoGrid_Location_Coordinate & b) friend
Definition at line 166 of file geogrid.pb.h.
Member Data Documentation
PROTOBUF_CONSTEXPR int const proto::GeoGrid_Location_Coordinate::kIndexInFileMessages static
Initial value:
=
    0
Definition at line 162 of file geogrid.pb.h.
const int proto::GeoGrid_Location_Coordinate::kXFieldNumber = 1 static
Definition at line 213 of file geogrid.pb.h.
const int proto::GeoGrid_Location_Coordinate::kYFieldNumber = 2 static
Definition at line 220 of file geogrid.pb.h.
const int proto::GeoGrid_Location_Coordinate::kLongitudeFieldNumber = 3 static
Definition at line 227 of file geogrid.pb.h.
const int proto::GeoGrid_Location_Coordinate::kLatitudeFieldNumber = 4 static
Definition at line 234 of file geogrid.pb.h.
::google::protobuf::internal::InternalMetadataWithArena proto::GeoGrid_Location_Coordinate::_internal_metadata_ private
Definition at line 252 of file geogrid.pb.h.
Referenced by mutable_unknown_fields(), and unknown_fields().
::google::protobuf::internal::HasBits<1> proto::GeoGrid_Location_Coordinate::_has_bits_ private
Definition at line 253 of file geogrid.pb.h.
int proto::GeoGrid_Location_Coordinate::_cached_size_ mutable private
Definition at line 254 of file geogrid.pb.h.
Referenced by GetCachedSize(), proto::GeoGrid_Location_ContactCenter_ContactPool::GetCachedSize(), proto::GeoGrid_Location_ContactCenter::GetCachedSize(), proto::GeoGrid_Location_Commute::GetCachedSize(), proto::GeoGrid_Location::GetCachedSize(), proto::GeoGrid_Person::GetCachedSize(), and proto::GeoGrid::GetCachedSize().
double proto::GeoGrid_Location_Coordinate::x_ private
Definition at line 255 of file geogrid.pb.h.
Referenced by x().
double proto::GeoGrid_Location_Coordinate::y_ private
Definition at line 256 of file geogrid.pb.h.
Referenced by y().
double proto::GeoGrid_Location_Coordinate::longitude_ private
Definition at line 257 of file geogrid.pb.h.
Referenced by longitude().
double proto::GeoGrid_Location_Coordinate::latitude_ private
Definition at line 258 of file geogrid.pb.h.
Referenced by latitude().
The documentation for this class was generated from the following file:
geogrid.pb.h