Stride Reference Manual: stride::util Namespace Reference
stride::util Namespace Reference
Utilities for the project.
Classes
class Any
A RAII void*, for type erasure, that can point to anything.
class ConfigInfo
Config information.
class CSV
A collection of CSVRow elements.
class CSVRow
Row in CSV file.
class Exception
Basic exception class.
class FileSys
Utilities for interaction with filesystem.
class LogUtils
Utilities for logging (spdlog).
class RangeIndexer
Datastructure to index a container that supports RandomAccessIterators with subranges.
class RangeIndexer< T, std::size_t >
Datastructure to index a container that supports RandomAccessIterators with subranges.
class RNManager
Manages random number generation in parallel (OpenMP) calculations.
class RunConfigManager
Produce run config ptree.
class SegmentedVector
Container that stores objects "almost contiguously" (in a chain of blocks) and guarantees that pointers/iterators are not invalidated when the container grows.
class SliceIndexer
Datastructure to index a container that supports RandomAccessIterators with slices.
class Stopwatch
Provides a stopwatch interface to time: it accumulates time between start/stop pairs.
class Subject
Template for Subject/Observer (or Publish/Subscribe).
class SVIterator
Implementation of iterator for SegmentedVector.
class TimeStamp
Provides wall-clock time stamp using the time call.
struct TimeToString
Utilities to tag clocks and to reformat number of ticks to a string.
Functions
template<>
std::string CSVRow::GetValue< std::string > (size_t index) const
specialization for string
template<>
std::string CSVRow::GetValue< std::string > (const std::string &label) const
specialization for string
std::ostream & operator<< (std::ostream &os, const CSVRow &row)
template<typename T , std::enable_if_t< std::is_arithmetic< T >::value, int > = 0>
T safe_cast (const std::string &val)
Converts a string to an arithmetic type, in a safe manner.
template<typename T >
RangeIndexer< T > make_range_indexer (T &t)
Traditional helper to activate template type parameter deduction.
template<typename T >
void para_info (stringstream &ss, const vector< T > &engines)
template<typename T >
void para_seed (vector< T > &engines, unsigned int stream_count, unsigned long seed)
template<typename T >
void para_seed (vector< T > &engines, unsigned int stream_count, const string &state)
template<typename T >
SliceIndexer< T > make_slice_indexer (T &t)
template<typename T >
std::ostream & operator<< (std::ostream &oss, Stopwatch< T > const &stopwatch)
Insert accumulated time into output stream without altering stopwatch state.
template<typename T >
T FromString (const std::string &s)
Builds a value of type T representation from a string.
std::vector< std::string > Split (const std::string &str, const std::string &delimiters)
Split a string (in order of occurence) by splitting it on the given delimiters.
std::vector< std::string > Tokenize (const std::string &str, const std::string &delimiters)
Tokenize a string (in order of occurence) with the given delimiters.
template<typename T >
std::string ToString (const T &value)
Builds a string representation of a value of type T.
template<typename T >
std::string ToString (const T &value, int width, char fill= ' ')
Builds a string representation with minimum width of a value of type T.
std::string ToLower (const std::string &source)
Builds a string with lower case characters only.
std::string ToUpper (const std::string &source)
Builds a string with upper case characters only.
std::string TrimRight (const std::string &source, const std::string &t=" ")
Trim characters at right end of string.
std::string TrimLeft (const std::string &source, const std::string &t=" ")
Trim characters at left end of string.
std::string Trim (const std::string &source, const std::string &t=" ")
Trim characters at both ends of string.
template<typename T >
std::string intToDottedString (const T &value)
template<typename T , std::size_t N, bool Safe, typename P = const T*, typename R = const T&, bool is_const_iterator = true>
SVIterator< T, N, Safe, P, R,
is_const_iterator > operator+ (std::ptrdiff_t i, SVIterator< T, N, Safe, P, R, is_const_iterator > p)
template<typename T , std::size_t N, bool Safe, typename P = const T*, typename R = const T&, bool is_const_iterator = true>
SVIterator< T, N, Safe, P, R,
is_const_iterator > operator- (std::ptrdiff_t i, SVIterator< T, N, Safe, P, R, is_const_iterator > p)
std::ostream & operator<< (std::ostream &os, TimeStamp t)
TimeStamp helper inserts string representation in output stream.
Detailed Description
Utilities for the project.
Function Documentation
template<> std::string stride::util::CSVRow::GetValue< std::string > (size_t index) const
specialization for string
Declaration of specialization.
Definition at line 51 of file CSVRow.cpp.
References ToString().
template<> std::string stride::util::CSVRow::GetValue< std::string > (const std::string & label) const
specialization for string
Declaration of specialization.
Definition at line 61 of file CSVRow.cpp.
std::ostream& stride::util::operator<< (std::ostream & os, const CSVRow & row)
Definition at line 69 of file CSVRow.cpp.
References stride::util::CSVRow::m_values.
template<typename T , std::enable_if_t< std::is_arithmetic< T >::value, int > = 0> T stride::util::safe_cast (const std::string & val) inline
Converts a string to an arithmetic type, in a safe manner.
Converts a string to a type.
Exceptions
bad_lexical_cast if val can't be converted to a double or int
bad_numeric_cast if val can't be converted to T
Template Parameters
T the type to safe cast to
Parameters
val the value to cast
Returns
Exceptions
bad_lexical_cast if val can't be converted to T
Template Parameters
T the type to safe cast to
Parameters
val the value to cast
Returns
Definition at line 74 of file CSVRow.h.
Referenced by stride::util::CSVRow::GetValue().
template<typename T > RangeIndexer<T> stride::util::make_range_indexer (T & t)
Traditional helper to activate template type parameter deduction.
Definition at line 140 of file RangeIndexer.h.
template<typename T > void stride::util::para_info (stringstream & ss, const vector< T > & engines)
Definition at line 37 of file RNManager.cpp.
Referenced by stride::util::RNManager::GetInfo().
template<typename T > void stride::util::para_seed (vector< T > & engines, unsigned int stream_count, unsigned long seed)
Definition at line 47 of file RNManager.cpp.
Referenced by stride::util::RNManager::Initialize().
template<typename T > void stride::util::para_seed (vector< T > & engines, unsigned int stream_count, const string & state)
Definition at line 59 of file RNManager.cpp.
template<typename T > SliceIndexer<T> stride::util::make_slice_indexer (T & t)
Definition at line 89 of file SliceIndexer.h.
template<typename T > std::ostream& stride::util::operator<< (std::ostream & oss, Stopwatch< T > const & stopwatch)
Insert accumulated time into output stream without altering stopwatch state.
Definition at line 124 of file Stopwatch.h.
template<typename T > T stride::util::FromString (const std::string & s) inline
Builds a value of type T representation from a string.
Definition at line 36 of file StringUtils.h.
Referenced by stride::util::RunConfigManager::Create(), and stride::Population::Create().
std::vector<std::string> stride::util::Split (const std::string & str, const std::string & delimiters) inline
Split a string (in order of occurence) by splitting it on the given delimiters.
Definition at line 46 of file StringUtils.h.
Referenced by stride::DefaultPopBuilder::MakePersons(), and stride::util::CSV::ReadFromStream().
std::vector<std::string> stride::util::Tokenize (const std::string & str, const std::string & delimiters) inline
Tokenize a string (in order of occurence) with the given delimiters.
Multiple consecutive delimiters do NOT define "empty" tokens; they are skipped.
Definition at line 55 of file StringUtils.h.
Referenced by main().
template<typename T > std::string stride::util::ToString (const T & value) inline
Builds a string representation of a value of type T.
Definition at line 78 of file StringUtils.h.
Referenced by stride::util::CSV::AddRow(), stride::util::CSVRow::CSVRow(), CSVRow::GetValue< std::string >(), and stride::util::RNManager::GetInfo().
template<typename T > std::string stride::util::ToString (const T & value, int width, char fill = ' ') inline
Builds a string representation with minimum width of a value of type T.
Definition at line 87 of file StringUtils.h.
std::string stride::util::ToLower (const std::string & source) inline
Builds a string with lower case characters only.
Definition at line 95 of file StringUtils.h.
Referenced by stride::util::FileSys::Initialize(), and stride::DiseaseSeeder::Vaccinate().
std::string stride::util::ToUpper (const std::string & source) inline
Builds a string with upper case characters only.
Definition at line 104 of file StringUtils.h.
std::string stride::util::TrimRight (const std::string & source, const std::string & t = " ") inline
Trim characters at right end of string.
Definition at line 113 of file StringUtils.h.
Referenced by Trim().
std::string stride::util::TrimLeft (const std::string & source, const std::string & t = " ") inline
Trim characters at left end of string.
Definition at line 120 of file StringUtils.h.
Referenced by Trim().
std::string stride::util::Trim (const std::string & source, const std::string & t = " ") inline
Trim characters at both ends of string.
Definition at line 127 of file StringUtils.h.
References TrimLeft(), and TrimRight().
Referenced by stride::util::CSVRow::CSVRow(), and stride::util::CSV::ReadFromStream().
template<typename T > std::string stride::util::intToDottedString (const T & value) inline
Definition at line 133 of file StringUtils.h.
Referenced by gengeopop::operator<<().
template<typename T , std::size_t N, bool Safe, typename P = const T*, typename R = const T&, bool is_const_iterator = true> SVIterator<T, N, Safe, P, R, is_const_iterator> stride::util::operator+ (std::ptrdiff_t i, SVIterator< T, N, Safe, P, R, is_const_iterator > p)
Definition at line 244 of file SVIterator.h.
template<typename T , std::size_t N, bool Safe, typename P = const T*, typename R = const T&, bool is_const_iterator = true> SVIterator<T, N, Safe, P, R, is_const_iterator> stride::util::operator- (std::ptrdiff_t i, SVIterator< T, N, Safe, P, R, is_const_iterator > p)
Definition at line 252 of file SVIterator.h.
std::ostream& stride::util::operator<< (std::ostream & os, TimeStamp t) inline
TimeStamp helper inserts string representation in output stream.
Definition at line 79 of file TimeStamp.h.
References stride::util::TimeStamp::ToString().