Stride Reference Manual: gengeopop::GeoGrid Class Reference
gengeopop::GeoGrid Class Reference
#include <GeoGrid.h>
Public Types
using iterator = std::vector< std::shared_ptr< Location >>::iterator
using const_iterator = std::vector< std::shared_ptr< Location >>::const_iterator
Public Member Functions
GeoGrid (std::shared_ptr< stride::Population > population, std::size_t regionId, std::string regionName)
GeoGrid ()
void AddLocation (std::shared_ptr< Location > location)
Adds a location to this GeoGrid.
void Finalize ()
Disables the addLocation method and builds the kdtree.
std::vector< std::shared_ptr
< Location > > FindLocationsInRadius (std::shared_ptr< Location > start, double radius) const
Search for locations in radius around start.
std::vector< std::shared_ptr
< Location > > TopK (size_t k) const
Gets the K biggest Location of this GeoGrid.
std::set< std::shared_ptr
< Location > > InBox (double long1, double lat1, double long2, double lat2) const
Gets the locations in a rectangle determined by the two coordinates (long1, lat1) and (long2, lat2).
std::set< std::shared_ptr
< Location > > InBox (const std::shared_ptr< Location > &loc1, const std::shared_ptr< Location > &loc2) const
Gets the location in a rectangle defined by the two locations.
iterator begin ()
Iterator to first Location.
iterator end ()
Iterator to the end of the Location storage.
const_iterator cbegin () const
Const Iterator to first Location.
const_iterator cend () const
Const iterator to the end of the Location storage.
size_t size () const
Gets amount of Location.
void remove (const std::shared_ptr< Location > &location)
Remove element of GeoGrid.
std::shared_ptr< Location > operator[] (size_t index)
Gets a Location by index, doesn't performs a range check.
std::shared_ptr< Location > Get (size_t index)
Gets a Location by index, doesn't performs a range check.
std::shared_ptr< Location > GetById (unsigned int id)
Gets a Location by id and check if the id exists.
std::string GetRegionName () const
Gets the region name of this GeoGrid.
template<typename... Args>
stride::Person * CreatePerson (Args &&...args)
Create and store a Person in the GeoGrid and return a pointer to it, which works until deletion of the GeoGrid.
stride::ContactPool * CreateContactPool (stride::ContactPoolType::Id type)
Create a ContactPool of the given type and return a non-owning pointer.
std::shared_ptr
< stride::Population > GetPopulation ()
Get the population of this GeoGrid.
template<typename Policy , typename F >
GeoAggregator< Policy, F > BuildAggregator (F functor, typename Policy::Args &&args) const
template<typename Policy >
GeoAggregator< Policy > BuildAggregator (typename Policy::Args &&args) const
Private Member Functions
void CheckFinalized (const std::string &functionName) const
Checks whether the GeoGrid is finalized and thus certain operations can(not) be used.
Private Attributes
std::vector< std::shared_ptr
< Location > > m_locations
Locations in this geoGrid.
std::unordered_map< unsigned
int, std::shared_ptr< Location > > m_locationsToIdIndex
Locations in this geoGrid indexed by Id.
std::shared_ptr
< stride::Population > m_population
Stores and Owns the population of this GeoGrid.
bool m_finalized
KdTree
< geogrid_detail::KdTree2DPoint > m_tree
std::size_t m_regionId
RegionId, used to create persons.
std::string m_regionName
Region name of this GeoGrid.
Detailed Description
Definition at line 85 of file GeoGrid.h.
Member Typedef Documentation
using gengeopop::GeoGrid::iterator = std::vector<std::shared_ptr<Location>>::iterator
Definition at line 88 of file GeoGrid.h.
using gengeopop::GeoGrid::const_iterator = std::vector<std::shared_ptr<Location>>::const_iterator
Definition at line 89 of file GeoGrid.h.
Constructor & Destructor Documentation
gengeopop::GeoGrid::GeoGrid (std::shared_ptr< stride::Population > population, std::size_t regionId, std::string regionName)
Definition at line 16 of file GeoGrid.cpp.
gengeopop::GeoGrid::GeoGrid ()
Definition at line 10 of file GeoGrid.cpp.
Member Function Documentation
void gengeopop::GeoGrid::AddLocation (std::shared_ptr< Location > location)
Adds a location to this GeoGrid.
Definition at line 27 of file GeoGrid.cpp.
References m_finalized, m_locations, and m_locationsToIdIndex.
void gengeopop::GeoGrid::Finalize ()
Disables the addLocation method and builds the kdtree.
Definition at line 81 of file GeoGrid.cpp.
References begin(), gengeopop::KdTree< P >::Build(), end(), m_finalized, and m_tree.
std::vector< std::shared_ptr< Location > > gengeopop::GeoGrid::FindLocationsInRadius (std::shared_ptr< Location > start, double radius) const
Search for locations in radius around start.
Definition at line 104 of file GeoGrid.cpp.
References CheckFinalized(), and gengeopop::MakeCollector().
std::vector< std::shared_ptr< Location > > gengeopop::GeoGrid::TopK (size_t k) const
Gets the K biggest Location of this GeoGrid.
Definition at line 40 of file GeoGrid.cpp.
References cbegin(), and cend().
std::set< std::shared_ptr< Location > > gengeopop::GeoGrid::InBox (double long1, double lat1, double long2, double lat2) const
Gets the locations in a rectangle determined by the two coordinates (long1, lat1) and (long2, lat2).
The coordinates must be position on the diagonal, i.e:
p1 --—+ +----—p1 | | | | | | or | | | | | | +----—p2 p2---—+
Definition at line 92 of file GeoGrid.cpp.
References CheckFinalized(), and gengeopop::MakeCollector().
std::set<std::shared_ptr<Location> > gengeopop::GeoGrid::InBox (const std::shared_ptr< Location > & loc1, const std::shared_ptr< Location > & loc2) const inline
Gets the location in a rectangle defined by the two locations.
Definition at line 122 of file GeoGrid.h.
GeoGrid::iterator gengeopop::GeoGrid::begin ()
Iterator to first Location.
Definition at line 23 of file GeoGrid.cpp.
References m_locations.
Referenced by Finalize(), and operator[]().
GeoGrid::iterator gengeopop::GeoGrid::end ()
Iterator to the end of the Location storage.
Definition at line 25 of file GeoGrid.cpp.
References m_locations.
Referenced by Finalize().
GeoGrid::const_iterator gengeopop::GeoGrid::cbegin () const
Const Iterator to first Location.
Definition at line 67 of file GeoGrid.cpp.
References m_locations.
Referenced by TopK().
GeoGrid::const_iterator gengeopop::GeoGrid::cend () const
Const iterator to the end of the Location storage.
Definition at line 69 of file GeoGrid.cpp.
References m_locations.
Referenced by TopK().
size_t gengeopop::GeoGrid::size () const
Gets amount of Location.
Definition at line 71 of file GeoGrid.cpp.
References m_locations.
void gengeopop::GeoGrid::remove (const std::shared_ptr< Location > & location)
Remove element of GeoGrid.
Definition at line 75 of file GeoGrid.cpp.
References m_locations, and m_locationsToIdIndex.
std::shared_ptr< Location > gengeopop::GeoGrid::operator[] (size_t index)
Gets a Location by index, doesn't performs a range check.
Definition at line 37 of file GeoGrid.cpp.
References begin().
std::shared_ptr< Location > gengeopop::GeoGrid::Get (size_t index)
Gets a Location by index, doesn't performs a range check.
Definition at line 38 of file GeoGrid.cpp.
std::shared_ptr< Location > gengeopop::GeoGrid::GetById (unsigned int id)
Gets a Location by id and check if the id exists.
Definition at line 73 of file GeoGrid.cpp.
References m_locationsToIdIndex.
std::string gengeopop::GeoGrid::GetRegionName () const
Gets the region name of this GeoGrid.
Definition at line 133 of file GeoGrid.cpp.
References m_regionName.
template<typename... Args> stride::Person* gengeopop::GeoGrid::CreatePerson (Args &&... args) inline
Create and store a Person in the GeoGrid and return a pointer to it, which works until deletion of the GeoGrid.
Definition at line 163 of file GeoGrid.h.
stride::ContactPool * gengeopop::GeoGrid::CreateContactPool (stride::ContactPoolType::Id type)
Create a ContactPool of the given type and return a non-owning pointer.
Definition at line 128 of file GeoGrid.cpp.
References m_population, and m_regionId.
std::shared_ptr< stride::Population > gengeopop::GeoGrid::GetPopulation ()
Get the population of this GeoGrid.
Definition at line 118 of file GeoGrid.cpp.
References m_population.
template<typename Policy , typename F > GeoAggregator< Policy, F > gengeopop::GeoGrid::BuildAggregator (F functor, typename Policy::Args && args) const
Definition at line 205 of file GeoGrid.h.
References m_tree.
template<typename Policy > GeoAggregator< Policy > gengeopop::GeoGrid::BuildAggregator (typename Policy::Args && args) const
Definition at line 211 of file GeoGrid.h.
References m_tree.
void gengeopop::GeoGrid::CheckFinalized (const std::string & functionName) const private
Checks whether the GeoGrid is finalized and thus certain operations can(not) be used.
Definition at line 120 of file GeoGrid.cpp.
References m_finalized.
Referenced by FindLocationsInRadius(), and InBox().
Member Data Documentation
std::vector<std::shared_ptr<Location> > gengeopop::GeoGrid::m_locations private
Locations in this geoGrid.
Definition at line 185 of file GeoGrid.h.
Referenced by AddLocation(), begin(), cbegin(), cend(), end(), remove(), and size().
std::unordered_map<unsigned int, std::shared_ptr<Location> > gengeopop::GeoGrid::m_locationsToIdIndex private
Locations in this geoGrid indexed by Id.
Definition at line 187 of file GeoGrid.h.
Referenced by AddLocation(), GetById(), and remove().
std::shared_ptr<stride::Population> gengeopop::GeoGrid::m_population private
Stores and Owns the population of this GeoGrid.
Definition at line 188 of file GeoGrid.h.
Referenced by CreateContactPool(), and GetPopulation().
bool gengeopop::GeoGrid::m_finalized private
Definition at line 190 of file GeoGrid.h.
Referenced by AddLocation(), CheckFinalized(), and Finalize().
KdTree<geogrid_detail::KdTree2DPoint> gengeopop::GeoGrid::m_tree private
Definition at line 192 of file GeoGrid.h.
Referenced by BuildAggregator(), and Finalize().
std::size_t gengeopop::GeoGrid::m_regionId private
RegionId, used to create persons.
Definition at line 194 of file GeoGrid.h.
Referenced by CreateContactPool().
std::string gengeopop::GeoGrid::m_regionName private
Region name of this GeoGrid.
Definition at line 195 of file GeoGrid.h.
Referenced by GetRegionName().
The documentation for this class was generated from the following files:
GeoGrid.h
GeoGrid.cpp