Stride Reference Manual: gengeopop Namespace Reference
gengeopop Namespace Reference
Namespaces
geogrid_detail
kd
Classes
class College
class Community
class ContactCenter
class CollegeGenerator
class CommunityGenerator
class GeoGridGenerator
class HouseholdGenerator
class K12SchoolGenerator
class PartialGenerator
An interface for generators that provide a partial solution.
class WorkplaceGenerator
class GenGeoPopController
Controls the complete generation and population of a GeoGrid.
class Collector
A functor that aggregates into a vector, if a vector is passed it should remain alive for the usage duration of the Collector.
class GeoAggregator
A GeoAggregator can either be instanciated with a functor, or be called with one every time.
class GeoAggregator< Policy >
A GeoAggregator that has to be called with a functor.
class GeoAggregator< Policy, F >
A GeoAggregator instanciated with a functor.
class RadiusPolicy
A policy for GeoAggregator that aggregates locations within a radius (in km) of a center point.
class BoxPolicy
A GeoAggregator Policy that aggregates over an axis aligned bounding box.
class PolygonPolicy
A GeoAggregator Policy that aggregates over a (clockwise) polygon.
class GeoGrid
class GeoGridConfig
class Household
class CitiesCSVReader
Create a Reader which fills a GeoGrid with the Cities found in a given CSV file.
class CitiesReader
Create an abstract Reader which fills a GeoGrid with the Cities found in a given file.
class CommutesCSVReader
Create a Reader which fills a GeoGrid with the Commutes found in a given CSV file.
class CommutesReader
Create an abstract Reader which fills a GeoGrid with the Commutes found in a given file.
class GeoGridJSONReader
An implementation of the GeoGridReader using JSON This class is used to read a GeoGrid from a JSON file.
class GeoGridJSONWriter
An implementation of the GeoGridWriter using JSON This class is used to write a GeoGrid to a JSON file.
class GeoGridProtoReader
An implementation of the GeoGridReader using Protocol Buffers This class is used to read a GeoGrid from a Proto file.
class GeoGridProtoWriter
An implementation of the GeoGridWriter using Protocol Buffers This class is used to write a GeoGrid to a Proto file.
class GeoGridReader
An abstract base class for creating a GeoGrid that was read from a file, can be implemented using multiple file types (proto and json are currently implemented)
class GeoGridReaderFactory
A Factory for creating the correct implementation of a GeoGridReader based on the filename extension.
class GeoGridWriter
An interface for writing the GeoGrid to a file, can be implemented with multiple file types (protobuf and json are currently implemented)
class GeoGridWriterFactory
A Factory for creating the correct implementation of a GeoGridWriter based on the filename extension.
class HouseholdCSVReader
Create a Reader that retrieves the different Household profiles from a given CSV file.
class HouseholdReader
Create a Reader that retrieves the different Household profiles from a given file This can be implemented using different input file types.
class ReaderFactory
A Factory for creating the correct implementation of the different Readers which parse the information needed to construct a GeoGrid, based on the file extension.
class SubMunicipalitiesCSVReader
Create a Reader which fills a GeoGrid with the SubMunicipalities found in a given CSV file.
class SubMunicipalitiesReader
Create an abstract Reader which fills a GeoGrid with the SubMunicipalities found in a given file.
class ThreadException
Create a wrapper for capturing the exceptions thrown in a multi-threaded environment This caught exception can then later be re-thrown in the main thread.
class K12School
struct AABB
Axis Aligned Bounding Box.
class KdTree
A k-d tree: a k-dimensional generalization of binary search trees This data structure allows for efficient lookup of points and range queries with an Axis-Aligned Bounding Box (when balanced).
class Location
class CollegePopulator
class GeoGridPopulator
class HouseholdPopulator
class K12SchoolPopulator
class PartialPopulator
An interface for populators that provide a partial solution.
class PrimaryCommunityPopulator
class SecondaryCommunityPopulator
class WorkplacePopulator
class PrimaryCommunity
class SecondaryCommunity
class Workplace
Functions
template<typename InsertIter , typename T = typename InsertIter::container_type::value_type>
Collector< InsertIter, T > MakeCollector (const InsertIter &ins)
Build a Collector, useful for type inference.
std::ostream & operator<< (std::ostream &out, const GeoGridConfig &config)
Function Documentation
template<typename InsertIter , typename T = typename InsertIter::container_type::value_type> Collector<InsertIter, T> gengeopop::MakeCollector (const InsertIter & ins)
Build a Collector, useful for type inference.
Definition at line 41 of file GeoAggregator.h.
Referenced by gengeopop::GeoGrid::FindLocationsInRadius(), and gengeopop::GeoGrid::InBox().
std::ostream& gengeopop::operator<< (std::ostream & out, const GeoGridConfig & config)
Definition at line 33 of file GeoGridConfig.cpp.
References gengeopop::GeoGridConfig::_1826_years, gengeopop::GeoGridConfig::_1826_years_and_student, gengeopop::GeoGridConfig::_1865_and_years_active, gengeopop::GeoGridConfig::_1865_years, gengeopop::GeoGridConfig::calculated, gengeopop::GeoGridConfig::compulsoryPupils, gengeopop::GeoGridConfig::fraction_1826_years_WhichAreStudents, gengeopop::GeoGridConfig::fraction_1865_years_active, gengeopop::GeoGridConfig::fraction_active_commutingPeople, gengeopop::GeoGridConfig::fraction_student_commutingPeople, gengeopop::GeoGridConfig::input, stride::util::intToDottedString(), and gengeopop::GeoGridConfig::populationSize.