Stride Reference Manual: proto::GeoGrid_Location_ContactCenter Class Reference
proto::GeoGrid_Location_ContactCenter Class Reference
#include <geogrid.pb.h>
Public Types
typedef
GeoGrid_Location_ContactCenter_ContactPool ContactPool
typedef
GeoGrid_Location_ContactCenter_Type Type
Public Member Functions
GeoGrid_Location_ContactCenter ()
virtual ~GeoGrid_Location_ContactCenter ()
GeoGrid_Location_ContactCenter (const GeoGrid_Location_ContactCenter &from)
GeoGrid_Location_ContactCenter & operator= (const GeoGrid_Location_ContactCenter &from)
const
::google::protobuf::UnknownFieldSet & unknown_fields () const
inline::google::protobuf::UnknownFieldSet * mutable_unknown_fields ()
void Swap (GeoGrid_Location_ContactCenter *other)
GeoGrid_Location_ContactCenter * New () const PROTOBUF_FINAL
GeoGrid_Location_ContactCenter * New (::google::protobuf::Arena *arena) const PROTOBUF_FINAL
void CopyFrom (const ::google::protobuf::Message &from) PROTOBUF_FINAL
void MergeFrom (const ::google::protobuf::Message &from) PROTOBUF_FINAL
void CopyFrom (const GeoGrid_Location_ContactCenter &from)
void MergeFrom (const GeoGrid_Location_ContactCenter &from)
void Clear () PROTOBUF_FINAL
bool IsInitialized () const PROTOBUF_FINAL
size_t ByteSizeLong () const PROTOBUF_FINAL
bool MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream *input) PROTOBUF_FINAL
void SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream *output) const PROTOBUF_FINAL
::google::protobuf::uint8 * InternalSerializeWithCachedSizesToArray (bool deterministic,::google::protobuf::uint8 *target) const PROTOBUF_FINAL
int GetCachedSize () const PROTOBUF_FINAL
::google::protobuf::Metadata GetMetadata () const PROTOBUF_FINAL
int pools_size () const
void clear_pools ()
const
::proto::GeoGrid_Location_ContactCenter_ContactPool & pools (int index) const
::proto::GeoGrid_Location_ContactCenter_ContactPool * mutable_pools (int index)
::proto::GeoGrid_Location_ContactCenter_ContactPool * add_pools ()
::google::protobuf::RepeatedPtrField
< ::proto::GeoGrid_Location_ContactCenter_ContactPool > * mutable_pools ()
const
::google::protobuf::RepeatedPtrField
< ::proto::GeoGrid_Location_ContactCenter_ContactPool > & pools () const
bool has_id () const
void clear_id ()
::google::protobuf::int64 id () const
void set_id (::google::protobuf::int64 value)
bool has_type () const
void clear_type ()
::proto::GeoGrid_Location_ContactCenter_Type type () const
void set_type (::proto::GeoGrid_Location_ContactCenter_Type value)
Static Public Member Functions
static const
::google::protobuf::Descriptor * descriptor ()
static const
GeoGrid_Location_ContactCenter & default_instance ()
static void InitAsDefaultInstance ()
static const
GeoGrid_Location_ContactCenter * internal_default_instance ()
static bool Type_IsValid (int value)
static const
::google::protobuf::EnumDescriptor * Type_descriptor ()
static const ::std::string & Type_Name (Type value)
static bool Type_Parse (const ::std::string &name, Type *value)
Static Public Attributes
static PROTOBUF_CONSTEXPR int const kIndexInFileMessages
static const Type K12School
static const Type Community
static const Type PrimaryCommunity
static const Type SecondaryCommunity
static const Type College
static const Type Household
static const Type Workplace
static const Type Type_MIN
static const Type Type_MAX
static const int Type_ARRAYSIZE
static const int kPoolsFieldNumber = 3
static const int kIdFieldNumber = 1
static const int kTypeFieldNumber = 2
Private Member Functions
void SharedCtor ()
void SharedDtor ()
void SetCachedSize (int size) const PROTOBUF_FINAL
void InternalSwap (GeoGrid_Location_ContactCenter *other)
inline::google::protobuf::Arena * GetArenaNoVirtual () const
void * MaybeArenaPtr () const
void set_has_id ()
void clear_has_id ()
void set_has_type ()
void clear_has_type ()
size_t RequiredFieldsByteSizeFallback () const
friend void::protobuf_geogrid_2eproto::InitDefaultsGeoGrid_Location_ContactCenterImpl ()
Private Attributes
::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_
::google::protobuf::internal::HasBits< 1 > _has_bits_
int _cached_size_
::google::protobuf::RepeatedPtrField
< ::proto::GeoGrid_Location_ContactCenter_ContactPool > pools_
::google::protobuf::int64 id_
int type_
Friends
struct ::protobuf_geogrid_2eproto::TableStruct
void swap (GeoGrid_Location_ContactCenter &a, GeoGrid_Location_ContactCenter &b)
Detailed Description
Definition at line 387 of file geogrid.pb.h.
Member Typedef Documentation
typedef GeoGrid_Location_ContactCenter_ContactPool proto::GeoGrid_Location_ContactCenter::ContactPool
Definition at line 474 of file geogrid.pb.h.
typedef GeoGrid_Location_ContactCenter_Type proto::GeoGrid_Location_ContactCenter::Type
Definition at line 476 of file geogrid.pb.h.
Constructor & Destructor Documentation
proto::GeoGrid_Location_ContactCenter::GeoGrid_Location_ContactCenter ()
virtual proto::GeoGrid_Location_ContactCenter::~GeoGrid_Location_ContactCenter () virtual
proto::GeoGrid_Location_ContactCenter::GeoGrid_Location_ContactCenter (const GeoGrid_Location_ContactCenter & from)
Member Function Documentation
GeoGrid_Location_ContactCenter& proto::GeoGrid_Location_ContactCenter::operator= (const GeoGrid_Location_ContactCenter & from) inline
Definition at line 394 of file geogrid.pb.h.
References proto::GeoGrid_Location_Coordinate::CopyFrom().
const ::google::protobuf::UnknownFieldSet& proto::GeoGrid_Location_ContactCenter::unknown_fields () const inline
Definition at line 413 of file geogrid.pb.h.
inline ::google::protobuf::UnknownFieldSet* proto::GeoGrid_Location_ContactCenter::mutable_unknown_fields () inline
Definition at line 416 of file geogrid.pb.h.
static const ::google::protobuf::Descriptor* proto::GeoGrid_Location_ContactCenter::descriptor () static
static const GeoGrid_Location_ContactCenter& proto::GeoGrid_Location_ContactCenter::default_instance () static
static void proto::GeoGrid_Location_ContactCenter::InitAsDefaultInstance () static
static const GeoGrid_Location_ContactCenter* proto::GeoGrid_Location_ContactCenter::internal_default_instance () inline static
Definition at line 424 of file geogrid.pb.h.
References proto::_GeoGrid_Location_ContactCenter_default_instance_.
void proto::GeoGrid_Location_ContactCenter::Swap (GeoGrid_Location_ContactCenter * other)
GeoGrid_Location_ContactCenter* proto::GeoGrid_Location_ContactCenter::New () const inline
Definition at line 438 of file geogrid.pb.h.
References New().
Referenced by New().
GeoGrid_Location_ContactCenter* proto::GeoGrid_Location_ContactCenter::New (::google::protobuf::Arena * arena) const
void proto::GeoGrid_Location_ContactCenter::CopyFrom (const ::google::protobuf::Message & from)
void proto::GeoGrid_Location_ContactCenter::MergeFrom (const ::google::protobuf::Message & from)
void proto::GeoGrid_Location_ContactCenter::CopyFrom (const GeoGrid_Location_ContactCenter & from)
void proto::GeoGrid_Location_ContactCenter::MergeFrom (const GeoGrid_Location_ContactCenter & from)
void proto::GeoGrid_Location_ContactCenter::Clear ()
bool proto::GeoGrid_Location_ContactCenter::IsInitialized () const
size_t proto::GeoGrid_Location_ContactCenter::ByteSizeLong () const
bool proto::GeoGrid_Location_ContactCenter::MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream * input)
void proto::GeoGrid_Location_ContactCenter::SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream * output) const
::google::protobuf::uint8* proto::GeoGrid_Location_ContactCenter::InternalSerializeWithCachedSizesToArray (bool deterministic, ::google::protobuf::uint8 * target) const
int proto::GeoGrid_Location_ContactCenter::GetCachedSize () const inline
Definition at line 455 of file geogrid.pb.h.
References proto::GeoGrid_Location_Coordinate::_cached_size_.
void proto::GeoGrid_Location_ContactCenter::SharedCtor () private
void proto::GeoGrid_Location_ContactCenter::SharedDtor () private
void proto::GeoGrid_Location_ContactCenter::SetCachedSize (int size) const private
void proto::GeoGrid_Location_ContactCenter::InternalSwap (GeoGrid_Location_ContactCenter * other) private
inline ::google::protobuf::Arena* proto::GeoGrid_Location_ContactCenter::GetArenaNoVirtual () const inline private
Definition at line 462 of file geogrid.pb.h.
void* proto::GeoGrid_Location_ContactCenter::MaybeArenaPtr () const inline private
Definition at line 465 of file geogrid.pb.h.
::google::protobuf::Metadata proto::GeoGrid_Location_ContactCenter::GetMetadata () const
static bool proto::GeoGrid_Location_ContactCenter::Type_IsValid (int value) inline static
Definition at line 491 of file geogrid.pb.h.
References proto::GeoGrid_Location_ContactCenter_Type_IsValid().
static const ::google::protobuf::EnumDescriptor* proto::GeoGrid_Location_ContactCenter::Type_descriptor () inline static
Definition at line 501 of file geogrid.pb.h.
References proto::GeoGrid_Location_ContactCenter_Type_descriptor().
static const ::std::string& proto::GeoGrid_Location_ContactCenter::Type_Name (Type value) inline static
Definition at line 504 of file geogrid.pb.h.
References proto::GeoGrid_Location_ContactCenter_Type_Name().
static bool proto::GeoGrid_Location_ContactCenter::Type_Parse (const ::std::string & name, Type * value) inline static
Definition at line 507 of file geogrid.pb.h.
References proto::GeoGrid_Location_ContactCenter_Type_Parse().
int proto::GeoGrid_Location_ContactCenter::pools_size () const inline
Definition at line 1377 of file geogrid.pb.h.
Referenced by gengeopop::GeoGridProtoReader::ParseContactCenter().
void proto::GeoGrid_Location_ContactCenter::clear_pools () inline
Definition at line 1380 of file geogrid.pb.h.
const ::proto::GeoGrid_Location_ContactCenter_ContactPool & proto::GeoGrid_Location_ContactCenter::pools (int index) const inline
Definition at line 1383 of file geogrid.pb.h.
Referenced by gengeopop::GeoGridProtoReader::ParseContactCenter().
proto::GeoGrid_Location_ContactCenter_ContactPool * proto::GeoGrid_Location_ContactCenter::mutable_pools (int index) inline
Definition at line 1387 of file geogrid.pb.h.
proto::GeoGrid_Location_ContactCenter_ContactPool * proto::GeoGrid_Location_ContactCenter::add_pools () inline
Definition at line 1391 of file geogrid.pb.h.
Referenced by gengeopop::GeoGridProtoWriter::WriteContactCenter().
google::protobuf::RepeatedPtrField<::proto::GeoGrid_Location_ContactCenter_ContactPool > * proto::GeoGrid_Location_ContactCenter::mutable_pools () inline
Definition at line 1396 of file geogrid.pb.h.
const ::google::protobuf::RepeatedPtrField<::proto::GeoGrid_Location_ContactCenter_ContactPool > & proto::GeoGrid_Location_ContactCenter::pools () const inline
Definition at line 1401 of file geogrid.pb.h.
bool proto::GeoGrid_Location_ContactCenter::has_id () const inline
Definition at line 1328 of file geogrid.pb.h.
void proto::GeoGrid_Location_ContactCenter::clear_id () inline
Definition at line 1337 of file geogrid.pb.h.
google::protobuf::int64 proto::GeoGrid_Location_ContactCenter::id () const inline
Definition at line 1341 of file geogrid.pb.h.
Referenced by gengeopop::GeoGridProtoReader::ParseContactCenter().
void proto::GeoGrid_Location_ContactCenter::set_id (::google::protobuf::int64 value) inline
Definition at line 1345 of file geogrid.pb.h.
Referenced by gengeopop::GeoGridProtoWriter::WriteContactCenter().
bool proto::GeoGrid_Location_ContactCenter::has_type () const inline
Definition at line 1352 of file geogrid.pb.h.
void proto::GeoGrid_Location_ContactCenter::clear_type () inline
Definition at line 1361 of file geogrid.pb.h.
proto::GeoGrid_Location_ContactCenter_Type proto::GeoGrid_Location_ContactCenter::type () const inline
Definition at line 1365 of file geogrid.pb.h.
Referenced by gengeopop::GeoGridProtoReader::ParseContactCenter().
void proto::GeoGrid_Location_ContactCenter::set_type (::proto::GeoGrid_Location_ContactCenter_Type value) inline
Definition at line 1369 of file geogrid.pb.h.
References proto::GeoGrid_Location_ContactCenter_Type_IsValid().
Referenced by gengeopop::GeoGridProtoWriter::WriteContactCenter().
void proto::GeoGrid_Location_ContactCenter::set_has_id () inline private
Definition at line 1331 of file geogrid.pb.h.
void proto::GeoGrid_Location_ContactCenter::clear_has_id () inline private
Definition at line 1334 of file geogrid.pb.h.
void proto::GeoGrid_Location_ContactCenter::set_has_type () inline private
Definition at line 1355 of file geogrid.pb.h.
void proto::GeoGrid_Location_ContactCenter::clear_has_type () inline private
Definition at line 1358 of file geogrid.pb.h.
size_t proto::GeoGrid_Location_ContactCenter::RequiredFieldsByteSizeFallback () const private
proto::GeoGrid_Location_ContactCenter::void::protobuf_geogrid_2eproto::InitDefaultsGeoGrid_Location_ContactCenterImpl () private
Friends And Related Function Documentation
friend struct ::protobuf_geogrid_2eproto::TableStruct friend
Definition at line 556 of file geogrid.pb.h.
void swap (GeoGrid_Location_ContactCenter & a, GeoGrid_Location_ContactCenter & b) friend
Definition at line 432 of file geogrid.pb.h.
Member Data Documentation
PROTOBUF_CONSTEXPR int const proto::GeoGrid_Location_ContactCenter::kIndexInFileMessages static
Initial value:
=
    2
Definition at line 428 of file geogrid.pb.h.
const Type proto::GeoGrid_Location_ContactCenter::K12School static
Initial value:
=
    GeoGrid_Location_ContactCenter_Type_K12School
Definition at line 477 of file geogrid.pb.h.
const Type proto::GeoGrid_Location_ContactCenter::Community static
Initial value:
=
    GeoGrid_Location_ContactCenter_Type_Community
Definition at line 479 of file geogrid.pb.h.
const Type proto::GeoGrid_Location_ContactCenter::PrimaryCommunity static
Initial value:
=
    GeoGrid_Location_ContactCenter_Type_PrimaryCommunity
Definition at line 481 of file geogrid.pb.h.
const Type proto::GeoGrid_Location_ContactCenter::SecondaryCommunity static
Initial value:
=
    GeoGrid_Location_ContactCenter_Type_SecondaryCommunity
Definition at line 483 of file geogrid.pb.h.
const Type proto::GeoGrid_Location_ContactCenter::College static
Initial value:
=
    GeoGrid_Location_ContactCenter_Type_College
Definition at line 485 of file geogrid.pb.h.
const Type proto::GeoGrid_Location_ContactCenter::Household static
Initial value:
=
    GeoGrid_Location_ContactCenter_Type_Household
Definition at line 487 of file geogrid.pb.h.
const Type proto::GeoGrid_Location_ContactCenter::Workplace static
Initial value:
=
    GeoGrid_Location_ContactCenter_Type_Workplace
Definition at line 489 of file geogrid.pb.h.
const Type proto::GeoGrid_Location_ContactCenter::Type_MIN static
Initial value:
=
    GeoGrid_Location_ContactCenter_Type_Type_MIN
Definition at line 494 of file geogrid.pb.h.
const Type proto::GeoGrid_Location_ContactCenter::Type_MAX static
Initial value:
=
    GeoGrid_Location_ContactCenter_Type_Type_MAX
Definition at line 496 of file geogrid.pb.h.
const int proto::GeoGrid_Location_ContactCenter::Type_ARRAYSIZE static
Initial value:
=
    GeoGrid_Location_ContactCenter_Type_Type_ARRAYSIZE
Definition at line 498 of file geogrid.pb.h.
const int proto::GeoGrid_Location_ContactCenter::kPoolsFieldNumber = 3 static
Definition at line 517 of file geogrid.pb.h.
const int proto::GeoGrid_Location_ContactCenter::kIdFieldNumber = 1 static
Definition at line 529 of file geogrid.pb.h.
const int proto::GeoGrid_Location_ContactCenter::kTypeFieldNumber = 2 static
Definition at line 536 of file geogrid.pb.h.
::google::protobuf::internal::InternalMetadataWithArena proto::GeoGrid_Location_ContactCenter::_internal_metadata_ private
Definition at line 550 of file geogrid.pb.h.
::google::protobuf::internal::HasBits<1> proto::GeoGrid_Location_ContactCenter::_has_bits_ private
Definition at line 551 of file geogrid.pb.h.
int proto::GeoGrid_Location_ContactCenter::_cached_size_ mutable private
Definition at line 552 of file geogrid.pb.h.
::google::protobuf::RepeatedPtrField< ::proto::GeoGrid_Location_ContactCenter_ContactPool > proto::GeoGrid_Location_ContactCenter::pools_ private
Definition at line 553 of file geogrid.pb.h.
::google::protobuf::int64 proto::GeoGrid_Location_ContactCenter::id_ private
Definition at line 554 of file geogrid.pb.h.
int proto::GeoGrid_Location_ContactCenter::type_ private
Definition at line 555 of file geogrid.pb.h.
The documentation for this class was generated from the following file:
geogrid.pb.h