Stride Reference Manual: stride Namespace Reference
stride Namespace Reference
Main namespace for the project.
Namespaces
ContactLogMode
Enum specifiying the level of logging required:
util
Utilities for the project.
viewers
Namespace for MVC-viewers that may be registered with SimRunner.
output
Utilities for the output files.
ContactPoolType
Namespace to manage types of ContactPool.
sim_event
Namespace to manage events signalled by the SimRunner.
python
RNEngineType
Namespace to manage types of random engines.
Classes
class NoBehaviour
NoBehaviour means that whatever beliefs a person holds, or whatever information they gather, will not result in a change in their behaviour.
class Vaccination
Vaccination beliefs and information have an influence on the vaccination behaviour of an individual.
class Belief
Base class for all belief policies.
class HBM
class Imitation
class NoBelief
No beliefs w.r.t vaccination.
class Threshold
class BeliefSeeder
Seeds the population with Health data.
class LocalDiscussion
Class for local information policy 'LocalDiscussion'.
class NoGlobalInformation
No global information about the disease, number of infected,...
class NoLocalInformation
No information about beliefs or health status is exchanged upon contact.
class Calendar
Class that keeps track of the 'state' of simulated world.
class DaysOffAll
No days off work or school.
class DaysOffInterface
Interface definition.
class DaysOffNone
No days off work or school.
class DaysOffSchool
Schools closed.
class DaysOffStandard
Standard situation for days off from work and school.
class AgeContactProfile
Contact rates as a function of age.
class ContactHandler
Processes the contacts between persons and determines whether transmission occurs.
class Infector
Actual contacts and transmission in contactpool (primary template).
class Infector< LL, TIC, NoLocalInformation, true >
Time-optimized version (For NoLocalInformation && (None || Transmission logging)).
class InfectorMap
Simulator can time step and reveal some of the key data.
class LOG_POLICY
Primary LOG_POLICY policy, implements LogMode::None.
class LOG_POLICY< ContactLogMode::Id::Transmissions >
Specialized LOG_POLICY policy LogMode::Transmissions.
class LOG_POLICY< ContactLogMode::Id::All >
Specialized LOG_POLICY policy LogMode::All.
class LOG_POLICY< ContactLogMode::Id::Susceptibles >
Specialized LOG_POLICY policy LogMode::Susceptibles.
class TransmissionProfile
Transmission rates from disease data.
class DiseaseSeeder
Seeds population w.r.t immunity (natural immunity, vaccination, ...) and infection.
class Health
Holds a person's health data.
class HealthSeeder
Seeds the population with Health data.
class Immunizer
Deals with immunization strategies.
class GuiController
A controller for the simulation that uses Qt to give the user the ability of controlling the steps.
class SimWorker
A worker class used to perform 1 step of the simulation on a different thread.
class Immunizer< ImmunizationProfile::Random >
Random immunization profile.
class Immunizer< ImmunizationProfile::Cocoon >
Profile for cocoon vaccination strategy.
class ContactPool
Represents a group of Persons that potentially have contacts.
class TravellerProfile
Holds the information about travels.
class TravellerProfileBuilder
Builds a TravellerProfile from the values in a configPt (using csv files).
class AbstractPopBuilder
Base Class for PopBuilders.
class DefaultPopBuilder
Initializes Population objects.
class GenPopBuilder
Initializes Population objects.
class ImportPopBuilder
Initializes Population objects.
class Person
Store and handle person data.
class Population
Container for persons in population.
class SurveySeeder
Seeds the population with survey participants.
class BaseController
A base class for Controllers in the MVC model.
class CliController
Controls a simulation run initiated with the command line interface (cli).
class Sim
Simulator can time step and reveal some of the key data.
class SimBuilder
Builds a simulator based a configuration property tree.
class SimRunner
The simulation runner drive simulator throufgh time steps.
Typedefs
using AgeContactProfiles = ContactPoolType::IdSubscriptArray< AgeContactProfile >
typedef void(InfectorExec)(ContactPool &pool, const AgeContactProfile &profile, const TransmissionProfile &trans_profile, ContactHandler &c_handler, unsigned short int sim_day, std::shared_ptr< spdlog::logger > c_logger)
For use in the InfectorMap and Sim.
using ContactPoolSys = ContactPoolType::IdSubscriptArray< util::SegmentedVector< ContactPool >>
ContactPoolSys contains for each of the type of pools (household, school, ...) a util::PartitionedSegmentedVector with for each region a util::SegmentedVector with all contactpools.
Enumerations
enum VariableState { VariableState::Low = 0U, VariableState::High = 1U }
enum HealthStatus : unsigned short int {
HealthStatus::Susceptible = 0U, HealthStatus::Exposed = 1U, HealthStatus::Infectious = 2U, HealthStatus::Symptomatic = 3U,
HealthStatus::InfectiousAndSymptomatic = 4U, HealthStatus::Recovered = 5U, HealthStatus::Immune = 6U
}
Enumerate the various health states with respect to the infection.
enum ImmunizationProfile { ImmunizationProfile::None = 0U, ImmunizationProfile::Random = 1U, ImmunizationProfile::Cocoon = 2U }
Functions
constexpr unsigned int MaximumAge ()
Maximum age for Persons.
constexpr unsigned int MinAdultAge ()
Maximum age for Person's.
unsigned int EffectiveAge (unsigned int age)
Effective age (topping of at maximum).
Detailed Description
Main namespace for the project.
Typedef Documentation
using stride::AgeContactProfiles = typedef ContactPoolType::IdSubscriptArray<AgeContactProfile>
Definition at line 28 of file AgeContactProfiles.h.
typedef void(stride::InfectorExec)(ContactPool &pool, const AgeContactProfile &profile, const TransmissionProfile &trans_profile, ContactHandler &c_handler, unsigned short int sim_day, std::shared_ptr< spdlog::logger > c_logger)
For use in the InfectorMap and Sim.
Definition at line 32 of file InfectorExec.h.
using stride::ContactPoolSys = typedef ContactPoolType::IdSubscriptArray<util::SegmentedVector<ContactPool>>
ContactPoolSys contains for each of the type of pools (household, school, ...) a util::PartitionedSegmentedVector with for each region a util::SegmentedVector with all contactpools.
The ContactPoolSys container is an std::array extended to be subscriptable with the enum class of the pool types.
Definition at line 33 of file ContactPoolSys.h.
Enumeration Type Documentation
enum stride::VariableState strong
Enumerator
Low
High
Definition at line 36 of file HBM.h.
enum stride::HealthStatus : unsigned short int strong
Enumerate the various health states with respect to the infection.
Enumerator
Susceptible
Exposed
Infectious
Symptomatic
InfectiousAndSymptomatic
Recovered
Immune
Definition at line 25 of file Health.h.
enum stride::ImmunizationProfile strong
Enumerator
None
Random
Cocoon
Definition at line 29 of file immunity/Immunizer.h.
Function Documentation
constexpr unsigned int stride::MaximumAge () inline
Maximum age for Persons.
Definition at line 25 of file Age.h.
Referenced by EffectiveAge().
constexpr unsigned int stride::MinAdultAge () inline
Maximum age for Person's.
Definition at line 28 of file Age.h.
Referenced by stride::Person::Update().
unsigned int stride::EffectiveAge (unsigned int age) inline
Effective age (topping of at maximum).
Definition at line 31 of file Age.h.
References MaximumAge().