Stride Reference Manual: proto::GeoGrid_Location Class Reference
proto::GeoGrid_Location Class Reference
#include <geogrid.pb.h>
Public Types
typedef GeoGrid_Location_Coordinate Coordinate
typedef
GeoGrid_Location_ContactCenter ContactCenter
typedef GeoGrid_Location_Commute Commute
Public Member Functions
GeoGrid_Location ()
virtual ~GeoGrid_Location ()
GeoGrid_Location (const GeoGrid_Location &from)
GeoGrid_Location & operator= (const GeoGrid_Location &from)
const
::google::protobuf::UnknownFieldSet & unknown_fields () const
inline::google::protobuf::UnknownFieldSet * mutable_unknown_fields ()
void Swap (GeoGrid_Location *other)
GeoGrid_Location * New () const PROTOBUF_FINAL
GeoGrid_Location * New (::google::protobuf::Arena *arena) const PROTOBUF_FINAL
void CopyFrom (const ::google::protobuf::Message &from) PROTOBUF_FINAL
void MergeFrom (const ::google::protobuf::Message &from) PROTOBUF_FINAL
void CopyFrom (const GeoGrid_Location &from)
void MergeFrom (const GeoGrid_Location &from)
void Clear () PROTOBUF_FINAL
bool IsInitialized () const PROTOBUF_FINAL
size_t ByteSizeLong () const PROTOBUF_FINAL
bool MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream *input) PROTOBUF_FINAL
void SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream *output) const PROTOBUF_FINAL
::google::protobuf::uint8 * InternalSerializeWithCachedSizesToArray (bool deterministic,::google::protobuf::uint8 *target) const PROTOBUF_FINAL
int GetCachedSize () const PROTOBUF_FINAL
::google::protobuf::Metadata GetMetadata () const PROTOBUF_FINAL
int contactcenters_size () const
void clear_contactcenters ()
const
::proto::GeoGrid_Location_ContactCenter & contactcenters (int index) const
::proto::GeoGrid_Location_ContactCenter * mutable_contactcenters (int index)
::proto::GeoGrid_Location_ContactCenter * add_contactcenters ()
::google::protobuf::RepeatedPtrField
< ::proto::GeoGrid_Location_ContactCenter > * mutable_contactcenters ()
const
::google::protobuf::RepeatedPtrField
< ::proto::GeoGrid_Location_ContactCenter > & contactcenters () const
int commutes_size () const
void clear_commutes ()
const
::proto::GeoGrid_Location_Commute & commutes (int index) const
::proto::GeoGrid_Location_Commute * mutable_commutes (int index)
::proto::GeoGrid_Location_Commute * add_commutes ()
::google::protobuf::RepeatedPtrField
< ::proto::GeoGrid_Location_Commute > * mutable_commutes ()
const
::google::protobuf::RepeatedPtrField
< ::proto::GeoGrid_Location_Commute > & commutes () const
int submunicipalities_size () const
void clear_submunicipalities ()
::google::protobuf::int64 submunicipalities (int index) const
void set_submunicipalities (int index,::google::protobuf::int64 value)
void add_submunicipalities (::google::protobuf::int64 value)
const
::google::protobuf::RepeatedField
< ::google::protobuf::int64 > & submunicipalities () const
::google::protobuf::RepeatedField
< ::google::protobuf::int64 > * mutable_submunicipalities ()
bool has_name () const
void clear_name ()
const ::std::string & name () const
void set_name (const ::std::string &value)
void set_name (const char *value)
void set_name (const char *value, size_t size)
::std::string * mutable_name ()
::std::string * release_name ()
void set_allocated_name (::std::string *name)
bool has_coordinate () const
void clear_coordinate ()
const
::proto::GeoGrid_Location_Coordinate & coordinate () const
::proto::GeoGrid_Location_Coordinate * release_coordinate ()
::proto::GeoGrid_Location_Coordinate * mutable_coordinate ()
void set_allocated_coordinate (::proto::GeoGrid_Location_Coordinate *coordinate)
bool has_id () const
void clear_id ()
::google::protobuf::int64 id () const
void set_id (::google::protobuf::int64 value)
bool has_province () const
void clear_province ()
::google::protobuf::int64 province () const
void set_province (::google::protobuf::int64 value)
bool has_population () const
void clear_population ()
::google::protobuf::int64 population () const
void set_population (::google::protobuf::int64 value)
Static Public Member Functions
static const
::google::protobuf::Descriptor * descriptor ()
static const GeoGrid_Location & default_instance ()
static void InitAsDefaultInstance ()
static const GeoGrid_Location * internal_default_instance ()
Static Public Attributes
static PROTOBUF_CONSTEXPR int const kIndexInFileMessages
static const int kContactCentersFieldNumber = 6
static const int kCommutesFieldNumber = 7
static const int kSubmunicipalitiesFieldNumber = 8
static const int kNameFieldNumber = 2
static const int kCoordinateFieldNumber = 5
static const int kIdFieldNumber = 1
static const int kProvinceFieldNumber = 3
static const int kPopulationFieldNumber = 4
Private Member Functions
void SharedCtor ()
void SharedDtor ()
void SetCachedSize (int size) const PROTOBUF_FINAL
void InternalSwap (GeoGrid_Location *other)
inline::google::protobuf::Arena * GetArenaNoVirtual () const
void * MaybeArenaPtr () const
void set_has_id ()
void clear_has_id ()
void set_has_name ()
void clear_has_name ()
void set_has_province ()
void clear_has_province ()
void set_has_population ()
void clear_has_population ()
void set_has_coordinate ()
void clear_has_coordinate ()
size_t RequiredFieldsByteSizeFallback () const
friend void::protobuf_geogrid_2eproto::InitDefaultsGeoGrid_LocationImpl ()
Private Attributes
::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_
::google::protobuf::internal::HasBits< 1 > _has_bits_
int _cached_size_
::google::protobuf::RepeatedPtrField
< ::proto::GeoGrid_Location_ContactCenter > contactcenters_
::google::protobuf::RepeatedPtrField
< ::proto::GeoGrid_Location_Commute > commutes_
::google::protobuf::RepeatedField
< ::google::protobuf::int64 > submunicipalities_
::google::protobuf::internal::ArenaStringPtr name_
::proto::GeoGrid_Location_Coordinate * coordinate_
::google::protobuf::int64 id_
::google::protobuf::int64 province_
::google::protobuf::int64 population_
Friends
struct ::protobuf_geogrid_2eproto::TableStruct
void swap (GeoGrid_Location &a, GeoGrid_Location &b)
Detailed Description
Definition at line 684 of file geogrid.pb.h.
Member Typedef Documentation
typedef GeoGrid_Location_Coordinate proto::GeoGrid_Location::Coordinate
Definition at line 771 of file geogrid.pb.h.
typedef GeoGrid_Location_ContactCenter proto::GeoGrid_Location::ContactCenter
Definition at line 772 of file geogrid.pb.h.
typedef GeoGrid_Location_Commute proto::GeoGrid_Location::Commute
Definition at line 773 of file geogrid.pb.h.
Constructor & Destructor Documentation
proto::GeoGrid_Location::GeoGrid_Location ()
virtual proto::GeoGrid_Location::~GeoGrid_Location () virtual
proto::GeoGrid_Location::GeoGrid_Location (const GeoGrid_Location & from)
Member Function Documentation
GeoGrid_Location& proto::GeoGrid_Location::operator= (const GeoGrid_Location & from) inline
Definition at line 691 of file geogrid.pb.h.
References proto::GeoGrid_Location_Coordinate::CopyFrom().
const ::google::protobuf::UnknownFieldSet& proto::GeoGrid_Location::unknown_fields () const inline
Definition at line 710 of file geogrid.pb.h.
inline ::google::protobuf::UnknownFieldSet* proto::GeoGrid_Location::mutable_unknown_fields () inline
Definition at line 713 of file geogrid.pb.h.
static const ::google::protobuf::Descriptor* proto::GeoGrid_Location::descriptor () static
static const GeoGrid_Location& proto::GeoGrid_Location::default_instance () static
static void proto::GeoGrid_Location::InitAsDefaultInstance () static
static const GeoGrid_Location* proto::GeoGrid_Location::internal_default_instance () inline static
Definition at line 721 of file geogrid.pb.h.
References proto::_GeoGrid_Location_default_instance_.
void proto::GeoGrid_Location::Swap (GeoGrid_Location * other)
GeoGrid_Location* proto::GeoGrid_Location::New () const inline
Definition at line 735 of file geogrid.pb.h.
References New().
Referenced by New().
GeoGrid_Location* proto::GeoGrid_Location::New (::google::protobuf::Arena * arena) const
void proto::GeoGrid_Location::CopyFrom (const ::google::protobuf::Message & from)
void proto::GeoGrid_Location::MergeFrom (const ::google::protobuf::Message & from)
void proto::GeoGrid_Location::CopyFrom (const GeoGrid_Location & from)
void proto::GeoGrid_Location::MergeFrom (const GeoGrid_Location & from)
void proto::GeoGrid_Location::Clear ()
bool proto::GeoGrid_Location::IsInitialized () const
size_t proto::GeoGrid_Location::ByteSizeLong () const
bool proto::GeoGrid_Location::MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream * input)
void proto::GeoGrid_Location::SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream * output) const
::google::protobuf::uint8* proto::GeoGrid_Location::InternalSerializeWithCachedSizesToArray (bool deterministic, ::google::protobuf::uint8 * target) const
int proto::GeoGrid_Location::GetCachedSize () const inline
Definition at line 752 of file geogrid.pb.h.
References proto::GeoGrid_Location_Coordinate::_cached_size_.
void proto::GeoGrid_Location::SharedCtor () private
void proto::GeoGrid_Location::SharedDtor () private
void proto::GeoGrid_Location::SetCachedSize (int size) const private
void proto::GeoGrid_Location::InternalSwap (GeoGrid_Location * other) private
inline ::google::protobuf::Arena* proto::GeoGrid_Location::GetArenaNoVirtual () const inline private
Definition at line 759 of file geogrid.pb.h.
void* proto::GeoGrid_Location::MaybeArenaPtr () const inline private
Definition at line 762 of file geogrid.pb.h.
::google::protobuf::Metadata proto::GeoGrid_Location::GetMetadata () const
int proto::GeoGrid_Location::contactcenters_size () const inline
Definition at line 1652 of file geogrid.pb.h.
Referenced by gengeopop::GeoGridProtoReader::ParseLocation().
void proto::GeoGrid_Location::clear_contactcenters () inline
Definition at line 1655 of file geogrid.pb.h.
const ::proto::GeoGrid_Location_ContactCenter & proto::GeoGrid_Location::contactcenters (int index) const inline
Definition at line 1658 of file geogrid.pb.h.
Referenced by gengeopop::GeoGridProtoReader::ParseLocation().
proto::GeoGrid_Location_ContactCenter * proto::GeoGrid_Location::mutable_contactcenters (int index) inline
Definition at line 1662 of file geogrid.pb.h.
proto::GeoGrid_Location_ContactCenter * proto::GeoGrid_Location::add_contactcenters () inline
Definition at line 1666 of file geogrid.pb.h.
Referenced by gengeopop::GeoGridProtoWriter::WriteLocation().
google::protobuf::RepeatedPtrField<::proto::GeoGrid_Location_ContactCenter > * proto::GeoGrid_Location::mutable_contactcenters () inline
Definition at line 1671 of file geogrid.pb.h.
const ::google::protobuf::RepeatedPtrField<::proto::GeoGrid_Location_ContactCenter > & proto::GeoGrid_Location::contactcenters () const inline
Definition at line 1676 of file geogrid.pb.h.
int proto::GeoGrid_Location::commutes_size () const inline
Definition at line 1682 of file geogrid.pb.h.
Referenced by gengeopop::GeoGridProtoReader::ParseLocation().
void proto::GeoGrid_Location::clear_commutes () inline
Definition at line 1685 of file geogrid.pb.h.
const ::proto::GeoGrid_Location_Commute & proto::GeoGrid_Location::commutes (int index) const inline
Definition at line 1688 of file geogrid.pb.h.
Referenced by gengeopop::GeoGridProtoReader::ParseLocation().
proto::GeoGrid_Location_Commute * proto::GeoGrid_Location::mutable_commutes (int index) inline
Definition at line 1692 of file geogrid.pb.h.
proto::GeoGrid_Location_Commute * proto::GeoGrid_Location::add_commutes () inline
Definition at line 1696 of file geogrid.pb.h.
Referenced by gengeopop::GeoGridProtoWriter::WriteLocation().
google::protobuf::RepeatedPtrField<::proto::GeoGrid_Location_Commute > * proto::GeoGrid_Location::mutable_commutes () inline
Definition at line 1701 of file geogrid.pb.h.
const ::google::protobuf::RepeatedPtrField<::proto::GeoGrid_Location_Commute > & proto::GeoGrid_Location::commutes () const inline
Definition at line 1706 of file geogrid.pb.h.
int proto::GeoGrid_Location::submunicipalities_size () const inline
Definition at line 1712 of file geogrid.pb.h.
Referenced by gengeopop::GeoGridProtoReader::ParseLocation().
void proto::GeoGrid_Location::clear_submunicipalities () inline
Definition at line 1715 of file geogrid.pb.h.
google::protobuf::int64 proto::GeoGrid_Location::submunicipalities (int index) const inline
Definition at line 1718 of file geogrid.pb.h.
Referenced by gengeopop::GeoGridProtoReader::ParseLocation().
void proto::GeoGrid_Location::set_submunicipalities (int index, ::google::protobuf::int64 value) inline
Definition at line 1722 of file geogrid.pb.h.
void proto::GeoGrid_Location::add_submunicipalities (::google::protobuf::int64 value) inline
Definition at line 1726 of file geogrid.pb.h.
Referenced by gengeopop::GeoGridProtoWriter::WriteLocation().
const ::google::protobuf::RepeatedField<::google::protobuf::int64 > & proto::GeoGrid_Location::submunicipalities () const inline
Definition at line 1731 of file geogrid.pb.h.
google::protobuf::RepeatedField<::google::protobuf::int64 > * proto::GeoGrid_Location::mutable_submunicipalities () inline
Definition at line 1736 of file geogrid.pb.h.
bool proto::GeoGrid_Location::has_name () const inline
Definition at line 1487 of file geogrid.pb.h.
void proto::GeoGrid_Location::clear_name () inline
Definition at line 1496 of file geogrid.pb.h.
const ::std::string & proto::GeoGrid_Location::name () const inline
Definition at line 1500 of file geogrid.pb.h.
Referenced by gengeopop::GeoGridProtoReader::ParseLocation().
void proto::GeoGrid_Location::set_name (const ::std::string & value) inline
Definition at line 1504 of file geogrid.pb.h.
Referenced by gengeopop::GeoGridProtoWriter::WriteLocation().
void proto::GeoGrid_Location::set_name (const char * value) inline
Definition at line 1517 of file geogrid.pb.h.
void proto::GeoGrid_Location::set_name (const char * value, size_t size) inline
Definition at line 1523 of file geogrid.pb.h.
std::string * proto::GeoGrid_Location::mutable_name () inline
Definition at line 1529 of file geogrid.pb.h.
std::string * proto::GeoGrid_Location::release_name () inline
Definition at line 1534 of file geogrid.pb.h.
void proto::GeoGrid_Location::set_allocated_name (::std::string * name) inline
Definition at line 1539 of file geogrid.pb.h.
bool proto::GeoGrid_Location::has_coordinate () const inline
Definition at line 1598 of file geogrid.pb.h.
void proto::GeoGrid_Location::clear_coordinate () inline
Definition at line 1607 of file geogrid.pb.h.
const ::proto::GeoGrid_Location_Coordinate & proto::GeoGrid_Location::coordinate () const inline
Definition at line 1611 of file geogrid.pb.h.
References proto::_GeoGrid_Location_Coordinate_default_instance_.
Referenced by gengeopop::GeoGridProtoReader::ParseLocation().
proto::GeoGrid_Location_Coordinate * proto::GeoGrid_Location::release_coordinate () inline
Definition at line 1617 of file geogrid.pb.h.
proto::GeoGrid_Location_Coordinate * proto::GeoGrid_Location::mutable_coordinate () inline
Definition at line 1624 of file geogrid.pb.h.
void proto::GeoGrid_Location::set_allocated_coordinate (::proto::GeoGrid_Location_Coordinate * coordinate) inline
Definition at line 1632 of file geogrid.pb.h.
References proto::GeoGrid_Location_Coordinate::GetArenaNoVirtual().
Referenced by gengeopop::GeoGridProtoWriter::WriteLocation().
bool proto::GeoGrid_Location::has_id () const inline
Definition at line 1463 of file geogrid.pb.h.
void proto::GeoGrid_Location::clear_id () inline
Definition at line 1472 of file geogrid.pb.h.
google::protobuf::int64 proto::GeoGrid_Location::id () const inline
Definition at line 1476 of file geogrid.pb.h.
Referenced by gengeopop::GeoGridProtoReader::ParseLocation().
void proto::GeoGrid_Location::set_id (::google::protobuf::int64 value) inline
Definition at line 1480 of file geogrid.pb.h.
Referenced by gengeopop::GeoGridProtoWriter::WriteLocation().
bool proto::GeoGrid_Location::has_province () const inline
Definition at line 1550 of file geogrid.pb.h.
void proto::GeoGrid_Location::clear_province () inline
Definition at line 1559 of file geogrid.pb.h.
google::protobuf::int64 proto::GeoGrid_Location::province () const inline
Definition at line 1563 of file geogrid.pb.h.
Referenced by gengeopop::GeoGridProtoReader::ParseLocation().
void proto::GeoGrid_Location::set_province (::google::protobuf::int64 value) inline
Definition at line 1567 of file geogrid.pb.h.
Referenced by gengeopop::GeoGridProtoWriter::WriteLocation().
bool proto::GeoGrid_Location::has_population () const inline
Definition at line 1574 of file geogrid.pb.h.
void proto::GeoGrid_Location::clear_population () inline
Definition at line 1583 of file geogrid.pb.h.
google::protobuf::int64 proto::GeoGrid_Location::population () const inline
Definition at line 1587 of file geogrid.pb.h.
Referenced by gengeopop::GeoGridProtoReader::ParseLocation().
void proto::GeoGrid_Location::set_population (::google::protobuf::int64 value) inline
Definition at line 1591 of file geogrid.pb.h.
Referenced by gengeopop::GeoGridProtoWriter::WriteLocation().
void proto::GeoGrid_Location::set_has_id () inline private
Definition at line 1466 of file geogrid.pb.h.
void proto::GeoGrid_Location::clear_has_id () inline private
Definition at line 1469 of file geogrid.pb.h.
void proto::GeoGrid_Location::set_has_name () inline private
Definition at line 1490 of file geogrid.pb.h.
void proto::GeoGrid_Location::clear_has_name () inline private
Definition at line 1493 of file geogrid.pb.h.
void proto::GeoGrid_Location::set_has_province () inline private
Definition at line 1553 of file geogrid.pb.h.
void proto::GeoGrid_Location::clear_has_province () inline private
Definition at line 1556 of file geogrid.pb.h.
void proto::GeoGrid_Location::set_has_population () inline private
Definition at line 1577 of file geogrid.pb.h.
void proto::GeoGrid_Location::clear_has_population () inline private
Definition at line 1580 of file geogrid.pb.h.
void proto::GeoGrid_Location::set_has_coordinate () inline private
Definition at line 1601 of file geogrid.pb.h.
void proto::GeoGrid_Location::clear_has_coordinate () inline private
Definition at line 1604 of file geogrid.pb.h.
size_t proto::GeoGrid_Location::RequiredFieldsByteSizeFallback () const private
proto::GeoGrid_Location::void::protobuf_geogrid_2eproto::InitDefaultsGeoGrid_LocationImpl () private
Friends And Related Function Documentation
friend struct ::protobuf_geogrid_2eproto::TableStruct friend
Definition at line 885 of file geogrid.pb.h.
void swap (GeoGrid_Location & a, GeoGrid_Location & b) friend
Definition at line 729 of file geogrid.pb.h.
Member Data Documentation
PROTOBUF_CONSTEXPR int const proto::GeoGrid_Location::kIndexInFileMessages static
Initial value:
=
    4
Definition at line 725 of file geogrid.pb.h.
const int proto::GeoGrid_Location::kContactCentersFieldNumber = 6 static
Definition at line 780 of file geogrid.pb.h.
const int proto::GeoGrid_Location::kCommutesFieldNumber = 7 static
Definition at line 792 of file geogrid.pb.h.
const int proto::GeoGrid_Location::kSubmunicipalitiesFieldNumber = 8 static
Definition at line 804 of file geogrid.pb.h.
const int proto::GeoGrid_Location::kNameFieldNumber = 2 static
Definition at line 816 of file geogrid.pb.h.
const int proto::GeoGrid_Location::kCoordinateFieldNumber = 5 static
Definition at line 831 of file geogrid.pb.h.
const int proto::GeoGrid_Location::kIdFieldNumber = 1 static
Definition at line 840 of file geogrid.pb.h.
const int proto::GeoGrid_Location::kProvinceFieldNumber = 3 static
Definition at line 847 of file geogrid.pb.h.
const int proto::GeoGrid_Location::kPopulationFieldNumber = 4 static
Definition at line 854 of file geogrid.pb.h.
::google::protobuf::internal::InternalMetadataWithArena proto::GeoGrid_Location::_internal_metadata_ private
Definition at line 874 of file geogrid.pb.h.
::google::protobuf::internal::HasBits<1> proto::GeoGrid_Location::_has_bits_ private
Definition at line 875 of file geogrid.pb.h.
int proto::GeoGrid_Location::_cached_size_ mutable private
Definition at line 876 of file geogrid.pb.h.
::google::protobuf::RepeatedPtrField< ::proto::GeoGrid_Location_ContactCenter > proto::GeoGrid_Location::contactcenters_ private
Definition at line 877 of file geogrid.pb.h.
::google::protobuf::RepeatedPtrField< ::proto::GeoGrid_Location_Commute > proto::GeoGrid_Location::commutes_ private
Definition at line 878 of file geogrid.pb.h.
::google::protobuf::RepeatedField< ::google::protobuf::int64 > proto::GeoGrid_Location::submunicipalities_ private
Definition at line 879 of file geogrid.pb.h.
::google::protobuf::internal::ArenaStringPtr proto::GeoGrid_Location::name_ private
Definition at line 880 of file geogrid.pb.h.
::proto::GeoGrid_Location_Coordinate* proto::GeoGrid_Location::coordinate_ private
Definition at line 881 of file geogrid.pb.h.
::google::protobuf::int64 proto::GeoGrid_Location::id_ private
Definition at line 882 of file geogrid.pb.h.
::google::protobuf::int64 proto::GeoGrid_Location::province_ private
Definition at line 883 of file geogrid.pb.h.
::google::protobuf::int64 proto::GeoGrid_Location::population_ private
Definition at line 884 of file geogrid.pb.h.
The documentation for this class was generated from the following file:
geogrid.pb.h