Stride Reference Manual: gengeopop::WorkplacePopulator Class Reference
gengeopop::WorkplacePopulator Class Reference
#include <WorkplacePopulator.h>
Public Member Functions
WorkplacePopulator (stride::util::RNManager &rn_manager, std::shared_ptr< spdlog::logger > logger)
void Apply (std::shared_ptr< GeoGrid > geogrid, GeoGridConfig &geoGridConfig) override
Public Member Functions inherited from gengeopop::PartialPopulator
PartialPopulator (stride::util::RNManager &rn_manager, std::shared_ptr< spdlog::logger > logger)
virtual ~PartialPopulator ()
Private Member Functions
void CalculateWorkplacesInCity ()
void CalculateFractionCommutingStudents ()
void CalculateCommutingLocations ()
void CalculateNearbyWorkspaces ()
void AssignActive (stride::Person *person)
Private Attributes
unsigned int m_assignedTo0 = 0
unsigned int m_assignedCommuting = 0
unsigned int m_assignedNotCommuting = 0
std::shared_ptr< Location > m_currentLoc
std::shared_ptr< GeoGrid > m_geoGrid
GeoGridConfig m_geoGridConfig
std::unordered_map
< std::shared_ptr< Location >
, std::pair< std::vector
< stride::ContactPool * >
, discreteDist > > m_workplacesInCity
double m_fractionCommutingStudents
std::vector
< stride::ContactPool * > m_nearByWorkplaces
discreteDist m_distNonCommuting
std::vector< std::shared_ptr
< Location > > m_commutingLocations
discreteDist m_disCommuting
Additional Inherited Members
Protected Member Functions inherited from gengeopop::PartialPopulator
template<typename T >
std::vector
< stride::ContactPool * > GetContactPoolInIncreasingRadius (const std::shared_ptr< GeoGrid > &geoGrid, const std::shared_ptr< Location > &start, double startRadius=10) const
bool MakeChoice (double fraction)
Protected Attributes inherited from gengeopop::PartialPopulator
stride::util::RNManager & m_rnManager
RnManager used by populators.
std::shared_ptr< spdlog::logger > m_logger
Logger used by populators.
Detailed Description
Definition at line 13 of file WorkplacePopulator.h.
Constructor & Destructor Documentation
gengeopop::WorkplacePopulator::WorkplacePopulator (stride::util::RNManager & rn_manager, std::shared_ptr< spdlog::logger > logger)
Definition at line 17 of file WorkplacePopulator.cpp.
Member Function Documentation
void gengeopop::WorkplacePopulator::CalculateWorkplacesInCity () private
Definition at line 87 of file WorkplacePopulator.cpp.
References gengeopop::ContactCenter::begin(), gengeopop::ContactCenter::end(), stride::util::RNManager::GetGenerator(), m_geoGrid, gengeopop::PartialPopulator::m_rnManager, and m_workplacesInCity.
Referenced by Apply().
void gengeopop::WorkplacePopulator::CalculateFractionCommutingStudents () private
Definition at line 79 of file WorkplacePopulator.cpp.
References gengeopop::GeoGridConfig::_1826_years_and_student, gengeopop::GeoGridConfig::_1865_and_years_active, gengeopop::GeoGridConfig::calculated, gengeopop::GeoGridConfig::fraction_active_commutingPeople, gengeopop::GeoGridConfig::fraction_student_commutingPeople, gengeopop::GeoGridConfig::input, m_fractionCommutingStudents, and m_geoGridConfig.
Referenced by Apply().
void gengeopop::WorkplacePopulator::CalculateCommutingLocations () private
Definition at line 126 of file WorkplacePopulator.cpp.
References ExcAssert(), stride::util::RNManager::GetGenerator(), m_commutingLocations, m_currentLoc, m_disCommuting, m_fractionCommutingStudents, and gengeopop::PartialPopulator::m_rnManager.
Referenced by Apply().
void gengeopop::WorkplacePopulator::CalculateNearbyWorkspaces () private
Definition at line 151 of file WorkplacePopulator.cpp.
References stride::util::RNManager::GetGenerator(), m_currentLoc, m_distNonCommuting, m_geoGrid, m_nearByWorkplaces, and gengeopop::PartialPopulator::m_rnManager.
Referenced by Apply().
void gengeopop::WorkplacePopulator::AssignActive (stride::Person * person) private
Definition at line 104 of file WorkplacePopulator.cpp.
References gengeopop::GeoGridConfig::fraction_active_commutingPeople, gengeopop::GeoGridConfig::input, m_assignedCommuting, m_assignedNotCommuting, m_commutingLocations, m_disCommuting, m_distNonCommuting, m_geoGridConfig, m_nearByWorkplaces, m_workplacesInCity, gengeopop::PartialPopulator::MakeChoice(), and stride::Person::SetWorkId().
Referenced by Apply().
void gengeopop::WorkplacePopulator::Apply (std::shared_ptr< GeoGrid > geogrid, GeoGridConfig & geoGridConfig) override virtual
Implements gengeopop::PartialPopulator.
Definition at line 24 of file WorkplacePopulator.cpp.
References AssignActive(), CalculateCommutingLocations(), CalculateFractionCommutingStudents(), CalculateNearbyWorkspaces(), CalculateWorkplacesInCity(), gengeopop::GeoGridConfig::fraction_1826_years_WhichAreStudents, gengeopop::GeoGridConfig::fraction_1865_years_active, gengeopop::GeoGridConfig::input, m_assignedCommuting, m_assignedNotCommuting, m_assignedTo0, m_commutingLocations, m_currentLoc, m_disCommuting, m_distNonCommuting, m_fractionCommutingStudents, m_geoGrid, m_geoGridConfig, gengeopop::PartialPopulator::m_logger, m_nearByWorkplaces, m_workplacesInCity, and gengeopop::PartialPopulator::MakeChoice().
Member Data Documentation
unsigned int gengeopop::WorkplacePopulator::m_assignedTo0 = 0 private
Definition at line 16 of file WorkplacePopulator.h.
Referenced by Apply().
unsigned int gengeopop::WorkplacePopulator::m_assignedCommuting = 0 private
Definition at line 17 of file WorkplacePopulator.h.
Referenced by Apply(), and AssignActive().
unsigned int gengeopop::WorkplacePopulator::m_assignedNotCommuting = 0 private
Definition at line 18 of file WorkplacePopulator.h.
Referenced by Apply(), and AssignActive().
std::shared_ptr<Location> gengeopop::WorkplacePopulator::m_currentLoc private
Definition at line 20 of file WorkplacePopulator.h.
Referenced by Apply(), CalculateCommutingLocations(), and CalculateNearbyWorkspaces().
std::shared_ptr<GeoGrid> gengeopop::WorkplacePopulator::m_geoGrid private
Definition at line 22 of file WorkplacePopulator.h.
Referenced by Apply(), CalculateNearbyWorkspaces(), and CalculateWorkplacesInCity().
GeoGridConfig gengeopop::WorkplacePopulator::m_geoGridConfig private
Definition at line 23 of file WorkplacePopulator.h.
Referenced by Apply(), AssignActive(), and CalculateFractionCommutingStudents().
std::unordered_map<std::shared_ptr<Location>, std::pair<std::vector<stride::ContactPool*>, discreteDist> > gengeopop::WorkplacePopulator::m_workplacesInCity private
Definition at line 26 of file WorkplacePopulator.h.
Referenced by Apply(), AssignActive(), and CalculateWorkplacesInCity().
double gengeopop::WorkplacePopulator::m_fractionCommutingStudents private
Definition at line 30 of file WorkplacePopulator.h.
Referenced by Apply(), CalculateCommutingLocations(), and CalculateFractionCommutingStudents().
std::vector<stride::ContactPool*> gengeopop::WorkplacePopulator::m_nearByWorkplaces private
Definition at line 33 of file WorkplacePopulator.h.
Referenced by Apply(), AssignActive(), and CalculateNearbyWorkspaces().
discreteDist gengeopop::WorkplacePopulator::m_distNonCommuting private
Definition at line 34 of file WorkplacePopulator.h.
Referenced by Apply(), AssignActive(), and CalculateNearbyWorkspaces().
std::vector<std::shared_ptr<Location> > gengeopop::WorkplacePopulator::m_commutingLocations private
Definition at line 38 of file WorkplacePopulator.h.
Referenced by Apply(), AssignActive(), and CalculateCommutingLocations().
discreteDist gengeopop::WorkplacePopulator::m_disCommuting private
Definition at line 39 of file WorkplacePopulator.h.
Referenced by Apply(), AssignActive(), and CalculateCommutingLocations().
The documentation for this class was generated from the following files:
WorkplacePopulator.h
WorkplacePopulator.cpp