Stride Reference Manual: stride::SimWorker Class Reference
stride::SimWorker Class Reference
A worker class used to perform 1 step of the simulation on a different thread.
#include <SimWorker.h>
Public Slots
void Work ()
Perform the actual step if we are not at the end of the sim.
Signals
void Worked (unsigned int infectedCount)
Let the caller know that the simulation was completely run and give the current infected count.
Public Member Functions
SimWorker (std::shared_ptr< SimRunner > runner)
Construct the Simworker with the SimRunner it has to perform a step for.
Private Attributes
std::shared_ptr< SimRunner > m_runner
The runner used to perform a step.
Detailed Description
A worker class used to perform 1 step of the simulation on a different thread.
Definition at line 11 of file SimWorker.h.
Constructor & Destructor Documentation
stride::SimWorker::SimWorker (std::shared_ptr< SimRunner > runner) explicit
Construct the Simworker with the SimRunner it has to perform a step for.
Definition at line 6 of file SimWorker.cpp.
Member Function Documentation
void stride::SimWorker::Work () slot
Perform the actual step if we are not at the end of the sim.
Definition at line 8 of file SimWorker.cpp.
References m_runner, and Worked().
Referenced by GuiControllerBackend::StepDay().
void stride::SimWorker::Worked (unsigned int infectedCount) signal
Let the caller know that the simulation was completely run and give the current infected count.
Referenced by GuiControllerBackend::StepDay(), and Work().
Member Data Documentation
std::shared_ptr<SimRunner> stride::SimWorker::m_runner private
The runner used to perform a step.
Definition at line 25 of file SimWorker.h.
Referenced by Work().
The documentation for this class was generated from the following files:
SimWorker.h
SimWorker.cpp