Stride Reference Manual: proto::GeoGrid_Location_Commute Class Reference
proto::GeoGrid_Location_Commute Class Reference
#include <geogrid.pb.h>
Public Member Functions
GeoGrid_Location_Commute ()
virtual ~GeoGrid_Location_Commute ()
GeoGrid_Location_Commute (const GeoGrid_Location_Commute &from)
GeoGrid_Location_Commute & operator= (const GeoGrid_Location_Commute &from)
const
::google::protobuf::UnknownFieldSet & unknown_fields () const
inline::google::protobuf::UnknownFieldSet * mutable_unknown_fields ()
void Swap (GeoGrid_Location_Commute *other)
GeoGrid_Location_Commute * New () const PROTOBUF_FINAL
GeoGrid_Location_Commute * New (::google::protobuf::Arena *arena) const PROTOBUF_FINAL
void CopyFrom (const ::google::protobuf::Message &from) PROTOBUF_FINAL
void MergeFrom (const ::google::protobuf::Message &from) PROTOBUF_FINAL
void CopyFrom (const GeoGrid_Location_Commute &from)
void MergeFrom (const GeoGrid_Location_Commute &from)
void Clear () PROTOBUF_FINAL
bool IsInitialized () const PROTOBUF_FINAL
size_t ByteSizeLong () const PROTOBUF_FINAL
bool MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream *input) PROTOBUF_FINAL
void SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream *output) const PROTOBUF_FINAL
::google::protobuf::uint8 * InternalSerializeWithCachedSizesToArray (bool deterministic,::google::protobuf::uint8 *target) const PROTOBUF_FINAL
int GetCachedSize () const PROTOBUF_FINAL
::google::protobuf::Metadata GetMetadata () const PROTOBUF_FINAL
bool has_to () const
void clear_to ()
::google::protobuf::int64 to () const
void set_to (::google::protobuf::int64 value)
bool has_proportion () const
void clear_proportion ()
double proportion () const
void set_proportion (double value)
Static Public Member Functions
static const
::google::protobuf::Descriptor * descriptor ()
static const
GeoGrid_Location_Commute & default_instance ()
static void InitAsDefaultInstance ()
static const
GeoGrid_Location_Commute * internal_default_instance ()
Static Public Attributes
static PROTOBUF_CONSTEXPR int const kIndexInFileMessages
static const int kToFieldNumber = 1
static const int kProportionFieldNumber = 2
Private Member Functions
void SharedCtor ()
void SharedDtor ()
void SetCachedSize (int size) const PROTOBUF_FINAL
void InternalSwap (GeoGrid_Location_Commute *other)
inline::google::protobuf::Arena * GetArenaNoVirtual () const
void * MaybeArenaPtr () const
void set_has_to ()
void clear_has_to ()
void set_has_proportion ()
void clear_has_proportion ()
size_t RequiredFieldsByteSizeFallback () const
friend void::protobuf_geogrid_2eproto::InitDefaultsGeoGrid_Location_CommuteImpl ()
Private Attributes
::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_
::google::protobuf::internal::HasBits< 1 > _has_bits_
int _cached_size_
::google::protobuf::int64 to_
double proportion_
Friends
struct ::protobuf_geogrid_2eproto::TableStruct
void swap (GeoGrid_Location_Commute &a, GeoGrid_Location_Commute &b)
Detailed Description
Definition at line 561 of file geogrid.pb.h.
Constructor & Destructor Documentation
proto::GeoGrid_Location_Commute::GeoGrid_Location_Commute ()
virtual proto::GeoGrid_Location_Commute::~GeoGrid_Location_Commute () virtual
proto::GeoGrid_Location_Commute::GeoGrid_Location_Commute (const GeoGrid_Location_Commute & from)
Member Function Documentation
GeoGrid_Location_Commute& proto::GeoGrid_Location_Commute::operator= (const GeoGrid_Location_Commute & from) inline
Definition at line 568 of file geogrid.pb.h.
References proto::GeoGrid_Location_Coordinate::CopyFrom().
const ::google::protobuf::UnknownFieldSet& proto::GeoGrid_Location_Commute::unknown_fields () const inline
Definition at line 587 of file geogrid.pb.h.
inline ::google::protobuf::UnknownFieldSet* proto::GeoGrid_Location_Commute::mutable_unknown_fields () inline
Definition at line 590 of file geogrid.pb.h.
static const ::google::protobuf::Descriptor* proto::GeoGrid_Location_Commute::descriptor () static
static const GeoGrid_Location_Commute& proto::GeoGrid_Location_Commute::default_instance () static
static void proto::GeoGrid_Location_Commute::InitAsDefaultInstance () static
static const GeoGrid_Location_Commute* proto::GeoGrid_Location_Commute::internal_default_instance () inline static
Definition at line 598 of file geogrid.pb.h.
References proto::_GeoGrid_Location_Commute_default_instance_.
void proto::GeoGrid_Location_Commute::Swap (GeoGrid_Location_Commute * other)
GeoGrid_Location_Commute* proto::GeoGrid_Location_Commute::New () const inline
Definition at line 612 of file geogrid.pb.h.
References New().
Referenced by New().
GeoGrid_Location_Commute* proto::GeoGrid_Location_Commute::New (::google::protobuf::Arena * arena) const
void proto::GeoGrid_Location_Commute::CopyFrom (const ::google::protobuf::Message & from)
void proto::GeoGrid_Location_Commute::MergeFrom (const ::google::protobuf::Message & from)
void proto::GeoGrid_Location_Commute::CopyFrom (const GeoGrid_Location_Commute & from)
void proto::GeoGrid_Location_Commute::MergeFrom (const GeoGrid_Location_Commute & from)
void proto::GeoGrid_Location_Commute::Clear ()
bool proto::GeoGrid_Location_Commute::IsInitialized () const
size_t proto::GeoGrid_Location_Commute::ByteSizeLong () const
bool proto::GeoGrid_Location_Commute::MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream * input)
void proto::GeoGrid_Location_Commute::SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream * output) const
::google::protobuf::uint8* proto::GeoGrid_Location_Commute::InternalSerializeWithCachedSizesToArray (bool deterministic, ::google::protobuf::uint8 * target) const
int proto::GeoGrid_Location_Commute::GetCachedSize () const inline
Definition at line 629 of file geogrid.pb.h.
References proto::GeoGrid_Location_Coordinate::_cached_size_.
void proto::GeoGrid_Location_Commute::SharedCtor () private
void proto::GeoGrid_Location_Commute::SharedDtor () private
void proto::GeoGrid_Location_Commute::SetCachedSize (int size) const private
void proto::GeoGrid_Location_Commute::InternalSwap (GeoGrid_Location_Commute * other) private
inline ::google::protobuf::Arena* proto::GeoGrid_Location_Commute::GetArenaNoVirtual () const inline private
Definition at line 636 of file geogrid.pb.h.
void* proto::GeoGrid_Location_Commute::MaybeArenaPtr () const inline private
Definition at line 639 of file geogrid.pb.h.
::google::protobuf::Metadata proto::GeoGrid_Location_Commute::GetMetadata () const
bool proto::GeoGrid_Location_Commute::has_to () const inline
Definition at line 1411 of file geogrid.pb.h.
void proto::GeoGrid_Location_Commute::clear_to () inline
Definition at line 1420 of file geogrid.pb.h.
google::protobuf::int64 proto::GeoGrid_Location_Commute::to () const inline
Definition at line 1424 of file geogrid.pb.h.
Referenced by gengeopop::GeoGridProtoReader::ParseLocation().
void proto::GeoGrid_Location_Commute::set_to (::google::protobuf::int64 value) inline
Definition at line 1428 of file geogrid.pb.h.
Referenced by gengeopop::GeoGridProtoWriter::WriteLocation().
bool proto::GeoGrid_Location_Commute::has_proportion () const inline
Definition at line 1435 of file geogrid.pb.h.
void proto::GeoGrid_Location_Commute::clear_proportion () inline
Definition at line 1444 of file geogrid.pb.h.
double proto::GeoGrid_Location_Commute::proportion () const inline
Definition at line 1448 of file geogrid.pb.h.
Referenced by gengeopop::GeoGridProtoReader::ParseLocation().
void proto::GeoGrid_Location_Commute::set_proportion (double value) inline
Definition at line 1452 of file geogrid.pb.h.
void proto::GeoGrid_Location_Commute::set_has_to () inline private
Definition at line 1414 of file geogrid.pb.h.
void proto::GeoGrid_Location_Commute::clear_has_to () inline private
Definition at line 1417 of file geogrid.pb.h.
void proto::GeoGrid_Location_Commute::set_has_proportion () inline private
Definition at line 1438 of file geogrid.pb.h.
void proto::GeoGrid_Location_Commute::clear_has_proportion () inline private
Definition at line 1441 of file geogrid.pb.h.
size_t proto::GeoGrid_Location_Commute::RequiredFieldsByteSizeFallback () const private
proto::GeoGrid_Location_Commute::void::protobuf_geogrid_2eproto::InitDefaultsGeoGrid_Location_CommuteImpl () private
Friends And Related Function Documentation
friend struct ::protobuf_geogrid_2eproto::TableStruct friend
Definition at line 679 of file geogrid.pb.h.
void swap (GeoGrid_Location_Commute & a, GeoGrid_Location_Commute & b) friend
Definition at line 606 of file geogrid.pb.h.
Member Data Documentation
PROTOBUF_CONSTEXPR int const proto::GeoGrid_Location_Commute::kIndexInFileMessages static
Initial value:
=
    3
Definition at line 602 of file geogrid.pb.h.
const int proto::GeoGrid_Location_Commute::kToFieldNumber = 1 static
Definition at line 653 of file geogrid.pb.h.
const int proto::GeoGrid_Location_Commute::kProportionFieldNumber = 2 static
Definition at line 660 of file geogrid.pb.h.
::google::protobuf::internal::InternalMetadataWithArena proto::GeoGrid_Location_Commute::_internal_metadata_ private
Definition at line 674 of file geogrid.pb.h.
::google::protobuf::internal::HasBits<1> proto::GeoGrid_Location_Commute::_has_bits_ private
Definition at line 675 of file geogrid.pb.h.
int proto::GeoGrid_Location_Commute::_cached_size_ mutable private
Definition at line 676 of file geogrid.pb.h.
::google::protobuf::int64 proto::GeoGrid_Location_Commute::to_ private
Definition at line 677 of file geogrid.pb.h.
double proto::GeoGrid_Location_Commute::proportion_ private
Definition at line 678 of file geogrid.pb.h.
The documentation for this class was generated from the following file:
geogrid.pb.h