Stride Reference Manual: gengeopop::geogrid_detail::KdTree2DPoint Class Reference
gengeopop::geogrid_detail::KdTree2DPoint Class Reference
#include <GeoGrid.h>
Classes
struct dimension_type
Public Member Functions
KdTree2DPoint (const std::shared_ptr< Location > &location)
KdTree2DPoint ()
KdTree2DPoint (double longt, double lat)
template<std::size_t D>
double Get () const
bool InBox (const AABB< KdTree2DPoint > &box) const
bool InRadius (const KdTree2DPoint &start, double radius) const
Does the point lie within radius km from start?
std::shared_ptr< Location > GetLocation () const
BoostPoint AsBoostPoint () const
Static Public Attributes
static constexpr std::size_t dim = 2
Private Member Functions
double Distance (const KdTree2DPoint &other) const
Distance in kilometers, following great circle distance on a speroid earth.
Private Attributes
BoostPoint m_pt
std::shared_ptr< Location > m_location
Detailed Description
Definition at line 28 of file GeoGrid.h.
Constructor & Destructor Documentation
gengeopop::geogrid_detail::KdTree2DPoint::KdTree2DPoint (const std::shared_ptr< Location > & location) inline explicit
Definition at line 31 of file GeoGrid.h.
gengeopop::geogrid_detail::KdTree2DPoint::KdTree2DPoint () inline
Definition at line 36 of file GeoGrid.h.
gengeopop::geogrid_detail::KdTree2DPoint::KdTree2DPoint (double longt, double lat) inline
Definition at line 38 of file GeoGrid.h.
Member Function Documentation
template<std::size_t D> double gengeopop::geogrid_detail::KdTree2DPoint::Get () const inline
Definition at line 43 of file GeoGrid.h.
References m_pt.
Referenced by gengeopop::RadiusPolicy::GetBoundingBox().
bool gengeopop::geogrid_detail::KdTree2DPoint::InBox (const AABB< KdTree2DPoint > & box) const inline
Definition at line 49 of file GeoGrid.h.
References gengeopop::AABB< P >::lower, m_pt, and gengeopop::AABB< P >::upper.
bool gengeopop::geogrid_detail::KdTree2DPoint::InRadius (const KdTree2DPoint & start, double radius) const inline
Does the point lie within radius km from start?
Definition at line 56 of file GeoGrid.h.
References Distance().
Referenced by gengeopop::RadiusPolicy::Contains().
std::shared_ptr<Location> gengeopop::geogrid_detail::KdTree2DPoint::GetLocation () const inline
Definition at line 58 of file GeoGrid.h.
References m_location.
Referenced by gengeopop::GeoAggregator< Policy >::operator()().
BoostPoint gengeopop::geogrid_detail::KdTree2DPoint::AsBoostPoint () const inline
Definition at line 66 of file GeoGrid.h.
References m_pt.
Referenced by gengeopop::PolygonPolicy::Contains().
double gengeopop::geogrid_detail::KdTree2DPoint::Distance (const KdTree2DPoint & other) const inline private
Distance in kilometers, following great circle distance on a speroid earth.
Definition at line 73 of file GeoGrid.h.
References m_pt.
Referenced by InRadius().
Member Data Documentation
constexpr std::size_t gengeopop::geogrid_detail::KdTree2DPoint::dim = 2 static
Definition at line 40 of file GeoGrid.h.
BoostPoint gengeopop::geogrid_detail::KdTree2DPoint::m_pt private
Definition at line 69 of file GeoGrid.h.
Referenced by AsBoostPoint(), Distance(), Get(), and InBox().
std::shared_ptr<Location> gengeopop::geogrid_detail::KdTree2DPoint::m_location private
Definition at line 70 of file GeoGrid.h.
Referenced by GetLocation().
The documentation for this class was generated from the following file:
GeoGrid.h