Stride Reference Manual: stride::TravellerIndex Class Reference
stride::TravellerIndex Class Reference
Stores the information about travels.
#include <TravellerIndex.h>
Classes
struct TravellerInfo
Information stored for a travel.
Public Member Functions
TravellerIndex ()
Default constructor.
void StartTravel (unsigned int from, ContactPool *to, Person *, std::size_t leaveDay, ContactPoolType::Id type)
Stores the information when the travel is started.
void ReturnTravelers (std::size_t currentDay)
Returns the travels at the given day.
Private Attributes
std::shared_ptr< spdlog::logger > m_travelLogger
Logger to which the travel information will be logged.
std::priority_queue
< TravellerInfo, std::vector
< TravellerInfo >
, std::greater<> > m_data
min-heap to efficiently store the persons which are travelling.
Detailed Description
Stores the information about travels.
One TravellerIndex stores information for a specific region. (i.e. all persons stored are from the same region). To have the code which handles the start and return of a person in the same location this class also handles that.
Definition at line 16 of file TravellerIndex.h.
Constructor & Destructor Documentation
stride::TravellerIndex::TravellerIndex ()
Default constructor.
Definition at line 8 of file TravellerIndex.cpp.
Member Function Documentation
void stride::TravellerIndex::StartTravel (unsigned int from, stride::ContactPool * to, stride::Person * person, std::size_t leaveDay, ContactPoolType::Id type)
Stores the information when the travel is started.
F from is the original contactPool (type is type) to is the foreign contactPool (same type as from) leaveDay is the day at which the person will return type is the type of the travel Work or PrimaryCommunity (i.e. recreational)
Definition at line 45 of file TravellerIndex.cpp.
References stride::ContactPool::AddExpat(), stride::TravellerIndex::TravellerInfo::from, stride::ContactPool::GetId(), stride::Person::GetId(), stride::ContactPoolType::IdList, m_data, stride::Person::m_in_pools, stride::Person::m_pool_ids, m_travelLogger, stride::ContactPoolType::PrimaryCommunity, stride::ContactPoolType::ToString(), and stride::ContactPoolType::Work.
void stride::TravellerIndex::ReturnTravelers (std::size_t currentDay)
Returns the travels at the given day.
Definition at line 10 of file TravellerIndex.cpp.
References stride::TravellerIndex::TravellerInfo::from, stride::ContactPool::GetId(), stride::Person::GetId(), stride::TravellerIndex::TravellerInfo::leaveDay, m_data, stride::Person::m_in_pools, stride::Person::m_isTravelling, stride::Person::m_pool_ids, m_travelLogger, stride::TravellerIndex::TravellerInfo::original_in_pools, stride::TravellerIndex::TravellerInfo::person, stride::ContactPool::RemoveExpat(), stride::TravellerIndex::TravellerInfo::to, stride::ContactPoolType::ToString(), and stride::TravellerIndex::TravellerInfo::type.
Member Data Documentation
std::shared_ptr<spdlog::logger> stride::TravellerIndex::m_travelLogger private
Logger to which the travel information will be logged.
Definition at line 47 of file TravellerIndex.h.
Referenced by ReturnTravelers(), and StartTravel().
std::priority_queue<TravellerInfo, std::vector<TravellerInfo>, std::greater<> > stride::TravellerIndex::m_data private
min-heap to efficiently store the persons which are travelling.
Indexed by the day they return (lowest first).
Definition at line 51 of file TravellerIndex.h.
Referenced by ReturnTravelers(), and StartTravel().
The documentation for this class was generated from the following files:
TravellerIndex.h
TravellerIndex.cpp