Stride Reference Manual: stride::TravellerProfile Class Reference
stride::TravellerProfile Class Reference
Holds the information about travels.
#include <TravellerProfile.h>
Public Member Functions
TravellerProfile (std::size_t amountOfRegions, double amountOfTravel, double fractionWork, util::RNManager &rnManager, std::size_t maxDays)
AmountOfTravel is a fraction 0-1 which indicates the change for a person to travel fractionWork indicates the amount of work travel.
TravellerProfile (util::RNManager &rnManager)
void AddTravelRecreation (std::size_t from, std::size_t to, double relativePopulation)
Add a travel record to the recreation profile.
void AddTravelWork (std::size_t from, std::size_t to, double relativePopulation)
Add a travel record to the work profile.
bool PersonWillTravel (size_t currentRegion, std::shared_ptr< Population > ptr, Person *person, std::size_t currentDay)
Based on the profile determines if a person will travel and handle when it effectively travels.
Private Member Functions
bool MakeChoice (double fraction)
Helper function to make a random choice based on a fraction.
Private Attributes
std::vector< std::vector
< double > > m_data_recreation
Holds the actual travelling profile used to "generate" trips From region, to region, relative amount of people.
std::vector< std::vector
< double > > m_data_work
Holds the actual travelling profile used to "generate" trips From region, to region, relative amount of people.
double m_amountOfTravel
A fraction 0-1 which indicates the change for a person to travel.
double m_fractionWork
A fraction 0-1 which indicates whether it's work travel or recreation.
util::RNManager & m_rnManager
std::size_t m_maxDays
Maximum amount of days to travel.
Detailed Description
Holds the information about travels.
Definition at line 15 of file TravellerProfile.h.
Constructor & Destructor Documentation
stride::TravellerProfile::TravellerProfile (std::size_t amountOfRegions, double amountOfTravel, double fractionWork, util::RNManager & rnManager, std::size_t maxDays)
AmountOfTravel is a fraction 0-1 which indicates the change for a person to travel fractionWork indicates the amount of work travel.
Definition at line 9 of file TravellerProfile.cpp.
References m_data_recreation, and m_data_work.
stride::TravellerProfile::TravellerProfile (util::RNManager & rnManager) inline explicit
Definition at line 23 of file TravellerProfile.h.
Member Function Documentation
void stride::TravellerProfile::AddTravelRecreation (std::size_t from, std::size_t to, double relativePopulation)
Add a travel record to the recreation profile.
Definition at line 20 of file TravellerProfile.cpp.
References m_data_recreation.
Referenced by stride::TravellerProfileBuilder::Build().
void stride::TravellerProfile::AddTravelWork (std::size_t from, std::size_t to, double relativePopulation)
Add a travel record to the work profile.
Definition at line 25 of file TravellerProfile.cpp.
References m_data_work.
Referenced by stride::TravellerProfileBuilder::Build().
bool stride::TravellerProfile::PersonWillTravel (size_t currentRegion, std::shared_ptr< Population > ptr, Person * person, std::size_t currentDay)
Based on the profile determines if a person will travel and handle when it effectively travels.
Definition at line 30 of file TravellerProfile.cpp.
References stride::util::RNManager::GetGenerator(), stride::Person::GetWorkId(), m_amountOfTravel, m_data_recreation, m_data_work, m_fractionWork, m_maxDays, m_rnManager, MakeChoice(), stride::ContactPoolType::PrimaryCommunity, and stride::ContactPoolType::Work.
bool stride::TravellerProfile::MakeChoice (double fraction) private
Helper function to make a random choice based on a fraction.
Definition at line 74 of file TravellerProfile.cpp.
References stride::util::RNManager::GetGenerator(), and m_rnManager.
Referenced by PersonWillTravel().
Member Data Documentation
std::vector<std::vector<double> > stride::TravellerProfile::m_data_recreation private
Holds the actual travelling profile used to "generate" trips From region, to region, relative amount of people.
Definition at line 40 of file TravellerProfile.h.
Referenced by AddTravelRecreation(), PersonWillTravel(), and TravellerProfile().
std::vector<std::vector<double> > stride::TravellerProfile::m_data_work private
Holds the actual travelling profile used to "generate" trips From region, to region, relative amount of people.
Definition at line 44 of file TravellerProfile.h.
Referenced by AddTravelWork(), PersonWillTravel(), and TravellerProfile().
double stride::TravellerProfile::m_amountOfTravel private
A fraction 0-1 which indicates the change for a person to travel.
Definition at line 47 of file TravellerProfile.h.
Referenced by PersonWillTravel().
double stride::TravellerProfile::m_fractionWork private
A fraction 0-1 which indicates whether it's work travel or recreation.
Definition at line 50 of file TravellerProfile.h.
Referenced by PersonWillTravel().
util::RNManager& stride::TravellerProfile::m_rnManager private
Definition at line 52 of file TravellerProfile.h.
Referenced by MakeChoice(), and PersonWillTravel().
std::size_t stride::TravellerProfile::m_maxDays private
Maximum amount of days to travel.
Definition at line 55 of file TravellerProfile.h.
Referenced by PersonWillTravel().
The documentation for this class was generated from the following files:
TravellerProfile.h
TravellerProfile.cpp