Stride Reference Manual: gengeopop::GenGeoPopController Class Reference
gengeopop::GenGeoPopController Class Reference
Controls the complete generation and population of a GeoGrid.
#include <GenGeoPopController.h>
Public Member Functions
GenGeoPopController (std::shared_ptr< spdlog::logger > logger, GeoGridConfig &geoGridConfig, stride::util::RNManager &rnManager, std::string citiesFileName, std::string commutingFileName, std::string householdFileName, std::string subMunicipalitiesFileName, std::string regionName)
Create a GenGeoPopController.
void ReadDataFiles ()
Reads the data files.
void GenGeo ()
Generate and store the Geo part of the GeoGrid.
void GenPop ()
Populate and store the Pop part of the GeoGrid.
std::shared_ptr< GeoGrid > GetGeoGrid ()
Get the generated GeoGrid.
void UsePopulation (std::shared_ptr< stride::Population > pop, std::size_t regionId)
Use the given Population storage during generation.
Private Attributes
GeoGridConfig & m_geoGridConfig
The GeoGridConfig used to generate.
stride::util::RNManager & m_rnManager
The RNManager used.
std::shared_ptr< GeoGrid > m_geoGrid
The generated GeoGrid.
std::shared_ptr
< stride::Population > m_population
The generated GeoGrid.
std::shared_ptr< CitiesReader > m_citiesReader
The CitiesReader.
std::shared_ptr< CommutesReader > m_commutesReader
The CommutesReader.
std::shared_ptr< HouseholdReader > m_householdsReader
The HouseholdsReader.
std::shared_ptr
< SubMunicipalitiesReader > m_subMunicipalitiesReader
The SubMunicipalitiesReader.
std::shared_ptr< spdlog::logger > m_logger
The logger used.
std::string m_citiesFileName
Filename of the file which stores information about the cities.
std::string m_commutingFileName
Filename of the file which stores information about the commutes.
std::string m_householdsFileName
Filename of the file which stores information about the households.
std::string m_subMunicipalitiesFileName
Filename of the file which stores information about the submunicipalities.
std::size_t m_regionId
RegionId, used to create persons.
std::string m_regionName
RegionName.
Detailed Description
Controls the complete generation and population of a GeoGrid.
Definition at line 14 of file GenGeoPopController.h.
Constructor & Destructor Documentation
gengeopop::GenGeoPopController::GenGeoPopController (std::shared_ptr< spdlog::logger > logger, GeoGridConfig & geoGridConfig, stride::util::RNManager & rnManager, std::string citiesFileName, std::string commutingFileName, std::string householdFileName, std::string subMunicipalitiesFileName, std::string regionName)
Create a GenGeoPopController.
Definition at line 20 of file GenGeoPopController.cpp.
Member Function Documentation
void gengeopop::GenGeoPopController::ReadDataFiles ()
Reads the data files.
Definition at line 32 of file GenGeoPopController.cpp.
References gengeopop::GeoGridConfig::Calculate(), gengeopop::ReaderFactory::CreateCitiesReader(), gengeopop::ReaderFactory::CreateCommutesReader(), gengeopop::ReaderFactory::CreateHouseholdReader(), gengeopop::ReaderFactory::CreateSubMunicipalitiesReader(), m_citiesFileName, m_citiesReader, m_commutesReader, m_commutingFileName, m_geoGrid, m_geoGridConfig, m_householdsFileName, m_householdsReader, m_population, m_regionId, m_regionName, m_subMunicipalitiesFileName, and m_subMunicipalitiesReader.
Referenced by stride::GenPopBuilder::Build(), and main().
void gengeopop::GenGeoPopController::GenGeo ()
Generate and store the Geo part of the GeoGrid.
Definition at line 78 of file GenGeoPopController.cpp.
References gengeopop::GeoGridGenerator::AddPartialGenerator(), gengeopop::GeoGridGenerator::GenerateGeoGrid(), m_geoGrid, m_geoGridConfig, m_logger, and m_rnManager.
Referenced by stride::GenPopBuilder::Build().
void gengeopop::GenGeoPopController::GenPop ()
Populate and store the Pop part of the GeoGrid.
Definition at line 89 of file GenGeoPopController.cpp.
References gengeopop::GeoGridPopulator::AddPartialPopulator(), m_geoGrid, m_geoGridConfig, m_logger, m_rnManager, and gengeopop::GeoGridPopulator::PopulateGeoGrid().
Referenced by stride::GenPopBuilder::Build().
std::shared_ptr< GeoGrid > gengeopop::GenGeoPopController::GetGeoGrid ()
Get the generated GeoGrid.
Definition at line 101 of file GenGeoPopController.cpp.
References m_geoGrid.
Referenced by stride::GenPopBuilder::Build().
void gengeopop::GenGeoPopController::UsePopulation (std::shared_ptr< stride::Population > pop, std::size_t regionId)
Use the given Population storage during generation.
Definition at line 103 of file GenGeoPopController.cpp.
References m_population, and m_regionId.
Referenced by stride::GenPopBuilder::Build().
Member Data Documentation
GeoGridConfig& gengeopop::GenGeoPopController::m_geoGridConfig private
The GeoGridConfig used to generate.
Definition at line 39 of file GenGeoPopController.h.
Referenced by GenGeo(), GenPop(), and ReadDataFiles().
stride::util::RNManager& gengeopop::GenGeoPopController::m_rnManager private
The RNManager used.
Definition at line 41 of file GenGeoPopController.h.
Referenced by GenGeo(), and GenPop().
std::shared_ptr<GeoGrid> gengeopop::GenGeoPopController::m_geoGrid private
The generated GeoGrid.
Definition at line 43 of file GenGeoPopController.h.
Referenced by GenGeo(), GenPop(), GetGeoGrid(), and ReadDataFiles().
std::shared_ptr<stride::Population> gengeopop::GenGeoPopController::m_population private
The generated GeoGrid.
Definition at line 45 of file GenGeoPopController.h.
Referenced by ReadDataFiles(), and UsePopulation().
std::shared_ptr<CitiesReader> gengeopop::GenGeoPopController::m_citiesReader private
The CitiesReader.
Definition at line 47 of file GenGeoPopController.h.
Referenced by ReadDataFiles().
std::shared_ptr<CommutesReader> gengeopop::GenGeoPopController::m_commutesReader private
The CommutesReader.
Definition at line 48 of file GenGeoPopController.h.
Referenced by ReadDataFiles().
std::shared_ptr<HouseholdReader> gengeopop::GenGeoPopController::m_householdsReader private
The HouseholdsReader.
Definition at line 49 of file GenGeoPopController.h.
Referenced by ReadDataFiles().
std::shared_ptr<SubMunicipalitiesReader> gengeopop::GenGeoPopController::m_subMunicipalitiesReader private
The SubMunicipalitiesReader.
Definition at line 50 of file GenGeoPopController.h.
Referenced by ReadDataFiles().
std::shared_ptr<spdlog::logger> gengeopop::GenGeoPopController::m_logger private
The logger used.
Definition at line 51 of file GenGeoPopController.h.
Referenced by GenGeo(), and GenPop().
std::string gengeopop::GenGeoPopController::m_citiesFileName private
Filename of the file which stores information about the cities.
Definition at line 53 of file GenGeoPopController.h.
Referenced by ReadDataFiles().
std::string gengeopop::GenGeoPopController::m_commutingFileName private
Filename of the file which stores information about the commutes.
Definition at line 54 of file GenGeoPopController.h.
Referenced by ReadDataFiles().
std::string gengeopop::GenGeoPopController::m_householdsFileName private
Filename of the file which stores information about the households.
Definition at line 55 of file GenGeoPopController.h.
Referenced by ReadDataFiles().
std::string gengeopop::GenGeoPopController::m_subMunicipalitiesFileName private
Filename of the file which stores information about the submunicipalities.
Definition at line 57 of file GenGeoPopController.h.
Referenced by ReadDataFiles().
std::size_t gengeopop::GenGeoPopController::m_regionId private
RegionId, used to create persons.
Definition at line 58 of file GenGeoPopController.h.
Referenced by ReadDataFiles(), and UsePopulation().
std::string gengeopop::GenGeoPopController::m_regionName private
RegionName.
Definition at line 59 of file GenGeoPopController.h.
Referenced by ReadDataFiles().
The documentation for this class was generated from the following files:
GenGeoPopController.h
GenGeoPopController.cpp