Stride Reference Manual: gengeopop::Location Class Reference
gengeopop::Location Class Reference
A location for use within the GeoGrid Contains useful information, both spatial and administrative.
#include <Location.h>
Public Types
using iterator = std::vector< std::shared_ptr< ContactCenter >>::iterator
Public Member Functions
Location (unsigned int id, unsigned int province, Coordinate coordinate=Coordinate(0.0, 0.0), std::string name="")
Location (unsigned int id, unsigned int province, unsigned int population, Coordinate coordinate=Coordinate(0.0, 0.0), std::string name="")
template<typename T >
void AddContactCenter (std::shared_ptr< T > contactCenter)
Add a ContactCenter.
template<typename T >
std::vector< std::shared_ptr
< ContactCenter > > GetContactCentersOfType ()
Gets the Contact Centers of a specific type T.
std::string GetName () const
Gets the name.
unsigned int GetProvince () const
Gets the province.
unsigned int GetID () const
Gets the ID.
unsigned int GetPopulation () const
Gets the absolute population.
unsigned int GetSimulationPopulation () const
Gets the population amount used in the simulation.
double GetInfectedRatio () const
Gets the ratio of infected persons in all contactPools of this location.
double GetInfectedCount () const
Gets the amount of people infected in the contactpools of this location.
double GetInfectedRatioOfSubmunicipalities () const
Gets the ratio of infected persons in all contactPools of this location's subMunicipalities.
void CalculatePopulation (unsigned int totalPopulation)
Given the total population calculates this location's population using the relative population of this location.
void SetRelativePopulation (double relativePopulation)
Sets the relative population, which will be later used by.
double GetRelativePopulationSize () const
Gets the relative population.
unsigned int GetPopulationOfSubmunicipalities () const
const std::vector< std::pair
< std::shared_ptr< Location >
, double > > & GetIncomingCommuningCities () const
Gets a vector with the outgoing cities which people are commuting to + the proportion.
void AddIncomingCommutingLocation (std::shared_ptr< Location > location, double proportion)
Adds a Location and a proportion to the incoming commutng vector I.e.
const std::vector< std::pair
< std::shared_ptr< Location >
, double > > & GetOutgoingCommuningCities () const
void AddOutgoingCommutingLocation (std::shared_ptr< Location > location, double proportion)
Adds a Location and a proportion to the incoming commuting vector I.e.
int OutGoingCommutingPeople (double fractionOfPopulationCommuting) const
Gets the absolute amount of poeple leaving from this location.
int IncomingCommutingPeople (double fractionOfPopulationCommuting) const
Gets the absolute amount of people going to this location.
void AddSubMunicipality (std::shared_ptr< Location > location)
Add a sub-municipality to this location.
const std::set
< std::shared_ptr< Location > > & GetSubMunicipalities () const
Gets the sub-municipalities of this location.
void SetParent (const std::shared_ptr< Location > &location)
Sets the parent of this sub-municipality, requires that this location doesn't have any sub-municipality.
std::shared_ptr< Location > GetParent () const
Gets the parent of this sub-municipality.
const Coordinate & GetCoordinate () const
Gets the Coordinate of this location.
void SetCoordinate (const Coordinate &coordinate)
iterator begin ()
Gets iterator to the first location.
iterator end ()
const std::vector
< std::shared_ptr
< ContactCenter > > & GetContactCenters () const
Gets all contact centers at this location.
bool operator== (const Location &other) const
Perform a full compare of the given locations.
Private Attributes
unsigned int m_id = 0
Id.
std::string m_name
Name.
unsigned int m_province
Province id.
unsigned int m_population
The absolute population.
double m_relativePopulation
The relative population (relative against whole population)
Coordinate m_coordinate
Coordinate.
std::vector< std::shared_ptr
< ContactCenter > > m_contactCenters
All contactCenters.
std::vector< std::pair
< std::shared_ptr< Location >
, double > > m_incomingCommutingLocations
Incomming commutes stored as pair of location and proportion relative to the given location.
std::vector< std::pair
< std::shared_ptr< Location >
, double > > m_outgoingCommutingLocations
std::set< std::shared_ptr
< Location > > m_subMunicipalities
Set of sub-municipalties, must be empty when m_parent is set.
std::shared_ptr< Location > m_parent
Parent of this sub-municipality, must be nullptr when m_subMunicipalities is et.
std::unordered_map
< std::type_index, std::vector
< std::shared_ptr
< ContactCenter > > > m_contactCenterByType
Stores the contact centers indexed by their type.
Detailed Description
A location for use within the GeoGrid Contains useful information, both spatial and administrative.
Definition at line 23 of file Location.h.
Member Typedef Documentation
using gengeopop::Location::iterator = std::vector<std::shared_ptr<ContactCenter>>::iterator
Definition at line 26 of file Location.h.
Constructor & Destructor Documentation
gengeopop::Location::Location (unsigned int id, unsigned int province, Coordinate coordinate = Coordinate(0.0, 0.0), std::string name = "")
Definition at line 7 of file Location.cpp.
gengeopop::Location::Location (unsigned int id, unsigned int province, unsigned int population, Coordinate coordinate = Coordinate(0.0, 0.0), std::string name = "")
Definition at line 14 of file Location.cpp.
References m_population.
Member Function Documentation
template<typename T > void gengeopop::Location::AddContactCenter (std::shared_ptr< T > contactCenter) inline
Add a ContactCenter.
Definition at line 36 of file Location.h.
References m_contactCenterByType, and m_contactCenters.
template<typename T > std::vector<std::shared_ptr<ContactCenter> > gengeopop::Location::GetContactCentersOfType () inline
Gets the Contact Centers of a specific type T.
Definition at line 44 of file Location.h.
References m_contactCenterByType.
std::string gengeopop::Location::GetName () const
Gets the name.
Definition at line 21 of file Location.cpp.
References m_name.
Referenced by operator==().
unsigned int gengeopop::Location::GetProvince () const
Gets the province.
Definition at line 23 of file Location.cpp.
References m_province.
Referenced by operator==().
unsigned int gengeopop::Location::GetID () const
Gets the ID.
Definition at line 25 of file Location.cpp.
References m_id.
Referenced by operator==().
unsigned int gengeopop::Location::GetPopulation () const
Gets the absolute population.
Definition at line 27 of file Location.cpp.
References m_population.
Referenced by GetInfectedRatio(), and operator==().
unsigned int gengeopop::Location::GetSimulationPopulation () const
Gets the population amount used in the simulation.
Definition at line 61 of file Location.cpp.
References m_contactCenters.
double gengeopop::Location::GetInfectedRatio () const
Gets the ratio of infected persons in all contactPools of this location.
Definition at line 29 of file Location.cpp.
References GetPopulation(), and m_contactCenters.
double gengeopop::Location::GetInfectedCount () const
Gets the amount of people infected in the contactpools of this location.
Definition at line 49 of file Location.cpp.
References m_contactCenters.
double gengeopop::Location::GetInfectedRatioOfSubmunicipalities () const
Gets the ratio of infected persons in all contactPools of this location's subMunicipalities.
Definition at line 73 of file Location.cpp.
References m_subMunicipalities.
void gengeopop::Location::CalculatePopulation (unsigned int totalPopulation)
Given the total population calculates this location's population using the relative population of this location.
Definition at line 165 of file Location.cpp.
References m_population, and m_relativePopulation.
void gengeopop::Location::SetRelativePopulation (double relativePopulation)
Sets the relative population, which will be later used by.
See Also
CalculatePopulation
Definition at line 169 of file Location.cpp.
References m_relativePopulation.
double gengeopop::Location::GetRelativePopulationSize () const
Gets the relative population.
Definition at line 170 of file Location.cpp.
References m_relativePopulation.
unsigned int gengeopop::Location::GetPopulationOfSubmunicipalities () const
Definition at line 192 of file Location.cpp.
References m_subMunicipalities.
const std::vector< std::pair< std::shared_ptr< Location >, double > > & gengeopop::Location::GetIncomingCommuningCities () const
Gets a vector with the outgoing cities which people are commuting to + the proportion.
Definition at line 102 of file Location.cpp.
References m_incomingCommutingLocations.
Referenced by operator==().
void gengeopop::Location::AddIncomingCommutingLocation (std::shared_ptr< Location > location, double proportion)
Adds a Location and a proportion to the incoming commutng vector I.e.
proportion of the commuting population in location are commuting to this
Definition at line 107 of file Location.cpp.
References m_incomingCommutingLocations.
const std::vector< std::pair< std::shared_ptr< Location >, double > > & gengeopop::Location::GetOutgoingCommuningCities () const
Returns
a vector with the outgoing cities which people are commuting to + the proportion
Definition at line 112 of file Location.cpp.
References m_outgoingCommutingLocations.
Referenced by operator==().
void gengeopop::Location::AddOutgoingCommutingLocation (std::shared_ptr< Location > location, double proportion)
Adds a Location and a proportion to the incoming commuting vector I.e.
proportion of the commuting population in this are commuting to location
Definition at line 117 of file Location.cpp.
References m_outgoingCommutingLocations.
int gengeopop::Location::OutGoingCommutingPeople (double fractionOfPopulationCommuting) const
Gets the absolute amount of poeple leaving from this location.
Definition at line 133 of file Location.cpp.
References m_outgoingCommutingLocations, and m_population.
int gengeopop::Location::IncomingCommutingPeople (double fractionOfPopulationCommuting) const
Gets the absolute amount of people going to this location.
Definition at line 122 of file Location.cpp.
References m_incomingCommutingLocations.
void gengeopop::Location::AddSubMunicipality (std::shared_ptr< Location > location)
Add a sub-municipality to this location.
Definition at line 172 of file Location.cpp.
References m_parent, and m_subMunicipalities.
const std::set< std::shared_ptr< Location > > & gengeopop::Location::GetSubMunicipalities () const
Gets the sub-municipalities of this location.
Definition at line 180 of file Location.cpp.
References m_subMunicipalities.
Referenced by operator==().
void gengeopop::Location::SetParent (const std::shared_ptr< Location > & location)
Sets the parent of this sub-municipality, requires that this location doesn't have any sub-municipality.
Definition at line 184 of file Location.cpp.
References m_parent, and m_subMunicipalities.
std::shared_ptr< Location > gengeopop::Location::GetParent () const
Gets the parent of this sub-municipality.
Definition at line 182 of file Location.cpp.
References m_parent.
Referenced by operator==().
const Coordinate & gengeopop::Location::GetCoordinate () const
Gets the Coordinate of this location.
Definition at line 94 of file Location.cpp.
References m_coordinate.
Referenced by operator==().
void gengeopop::Location::SetCoordinate (const Coordinate & coordinate)
Definition at line 96 of file Location.cpp.
References m_coordinate.
Location::iterator gengeopop::Location::begin ()
Gets iterator to the first location.
Definition at line 98 of file Location.cpp.
References m_contactCenters.
Location::iterator gengeopop::Location::end ()
Definition at line 100 of file Location.cpp.
References m_contactCenters.
const std::vector< std::shared_ptr< ContactCenter > > & gengeopop::Location::GetContactCenters () const
Gets all contact centers at this location.
Definition at line 92 of file Location.cpp.
References m_contactCenters.
Referenced by operator==().
bool gengeopop::Location::operator== (const Location & other) const
Perform a full compare of the given locations.
Definition at line 144 of file Location.cpp.
References GetContactCenters(), GetCoordinate(), GetID(), GetIncomingCommuningCities(), GetName(), GetOutgoingCommuningCities(), GetParent(), GetPopulation(), GetProvince(), and GetSubMunicipalities().
Member Data Documentation
unsigned int gengeopop::Location::m_id = 0 private
Id.
Definition at line 139 of file Location.h.
Referenced by GetID().
std::string gengeopop::Location::m_name private
Name.
Definition at line 140 of file Location.h.
Referenced by GetName().
unsigned int gengeopop::Location::m_province private
Province id.
Definition at line 141 of file Location.h.
Referenced by GetProvince().
unsigned int gengeopop::Location::m_population private
The absolute population.
Definition at line 142 of file Location.h.
Referenced by CalculatePopulation(), GetPopulation(), Location(), and OutGoingCommutingPeople().
double gengeopop::Location::m_relativePopulation private
The relative population (relative against whole population)
Definition at line 143 of file Location.h.
Referenced by CalculatePopulation(), GetRelativePopulationSize(), and SetRelativePopulation().
Coordinate gengeopop::Location::m_coordinate private
Coordinate.
Definition at line 144 of file Location.h.
Referenced by GetCoordinate(), and SetCoordinate().
std::vector<std::shared_ptr<ContactCenter> > gengeopop::Location::m_contactCenters private
All contactCenters.
Definition at line 145 of file Location.h.
Referenced by AddContactCenter(), begin(), end(), GetContactCenters(), GetInfectedCount(), GetInfectedRatio(), and GetSimulationPopulation().
std::vector<std::pair<std::shared_ptr<Location>, double> > gengeopop::Location::m_incomingCommutingLocations private
Incomming commutes stored as pair of location and proportion relative to the given location.
Outgoing commutes stored as pair of location and proportion relative to the this location
Definition at line 147 of file Location.h.
Referenced by AddIncomingCommutingLocation(), GetIncomingCommuningCities(), and IncomingCommutingPeople().
std::vector<std::pair<std::shared_ptr<Location>, double> > gengeopop::Location::m_outgoingCommutingLocations private
Definition at line 149 of file Location.h.
Referenced by AddOutgoingCommutingLocation(), GetOutgoingCommuningCities(), and OutGoingCommutingPeople().
std::set<std::shared_ptr<Location> > gengeopop::Location::m_subMunicipalities private
Set of sub-municipalties, must be empty when m_parent is set.
Definition at line 151 of file Location.h.
Referenced by AddSubMunicipality(), GetInfectedRatioOfSubmunicipalities(), GetPopulationOfSubmunicipalities(), GetSubMunicipalities(), and SetParent().
std::shared_ptr<Location> gengeopop::Location::m_parent private
Parent of this sub-municipality, must be nullptr when m_subMunicipalities is et.
Definition at line 153 of file Location.h.
Referenced by AddSubMunicipality(), GetParent(), and SetParent().
std::unordered_map<std::type_index, std::vector<std::shared_ptr<ContactCenter> > > gengeopop::Location::m_contactCenterByType private
Stores the contact centers indexed by their type.
Definition at line 155 of file Location.h.
Referenced by AddContactCenter(), and GetContactCentersOfType().
The documentation for this class was generated from the following files:
Location.h
Location.cpp