Stride Reference Manual: stride::BaseController Class Reference
stride::BaseController Class Reference abstract
#include <BaseController.h>
Public Member Functions
BaseController (const boost::property_tree::ptree &configPt)
Straight initialization.
virtual ~BaseController ()=default
Virtual desctructor for overloading.
virtual void Control ()=0
Actual run of the simulator.
virtual std::shared_ptr
< SimRunner > GetSimRunner ()
Returns the SimRunner that is used.
template<typename T , typename... Targs>
void RegisterViewer (Targs &&...args)
virtual void RegisterViewers ()
Register the viewers of the SimRunner.
virtual std::shared_ptr
< spdlog::logger > GetLogger () const
Returns the logger.
virtual std::string GetOutputPrefix ()
Protected Member Functions
BaseController ()
Empty controller: used as taget for delegation.
virtual void CheckEnv ()
Check install environment.
virtual void CheckOutputPrefix ()
virtual void LogSetup ()
Logs info on setup for cli environment to stride_logger.
virtual void MakeLogger ()
Make the appropriate logger for cli environment and register as stride_logger.
void PatchConfig ()
Patch run configuration with cli overrides and defaults.
void ReadConfigFile ()
Read configuration file.
Protected Attributes
boost::property_tree::ptree m_config_pt
Main configuration for run and sim.
std::string m_output_prefix
Prefix to output (name prefix or prefix dir)
util::Stopwatch m_run_clock
Stopwatch for timing the computation.
std::shared_ptr< spdlog::logger > m_stride_logger
General logger.
bool m_use_install_dirs
Working dir or install dir mode.
std::shared_ptr< SimRunner > m_runner
util::RNManager m_rn_manager
Detailed Description
Definition at line 33 of file BaseController.h.
Constructor & Destructor Documentation
stride::BaseController::BaseController (const boost::property_tree::ptree & configPt) explicit
Straight initialization.
virtual stride::BaseController::~BaseController () virtual default
Virtual desctructor for overloading.
stride::BaseController::BaseController () explicit protected
Empty controller: used as taget for delegation.
Definition at line 47 of file BaseController.cpp.
References stride::Population::Create(), stride::util::RNManager::Initialize(), m_config_pt, m_rn_manager, and m_runner.
Member Function Documentation
virtual void stride::BaseController::Control () pure virtual
Actual run of the simulator.
Implemented in stride::CliController, and stride::GuiController.
Referenced by Launcher::Launch(), and main().
std::shared_ptr< SimRunner > stride::BaseController::GetSimRunner () virtual
Returns the SimRunner that is used.
Definition at line 168 of file BaseController.cpp.
References m_runner.
template<typename T , typename... Targs> void stride::BaseController::RegisterViewer (Targs &&... args) inline
Definition at line 49 of file BaseController.h.
References m_runner.
Referenced by Launcher::Launch(), and main().
void stride::BaseController::RegisterViewers () virtual
Register the viewers of the SimRunner.
Definition at line 112 of file BaseController.cpp.
References m_config_pt, m_output_prefix, m_runner, m_stride_logger, and stride::viewers::CliViewer::Update().
Referenced by main().
std::shared_ptr< spdlog::logger > stride::BaseController::GetLogger () const virtual
Returns the logger.
Definition at line 166 of file BaseController.cpp.
References m_stride_logger.
Referenced by Launcher::Launch(), and main().
std::string stride::BaseController::GetOutputPrefix () virtual
Definition at line 170 of file BaseController.cpp.
References m_output_prefix.
Referenced by Launcher::Launch().
void stride::BaseController::CheckEnv () protected virtual
Check install environment.
Definition at line 80 of file BaseController.cpp.
References stride::util::FileSys::CheckInstallEnv().
void stride::BaseController::CheckOutputPrefix () protected virtual
Definition at line 90 of file BaseController.cpp.
References stride::util::FileSys::IsDirectoryString(), and m_output_prefix.
void stride::BaseController::LogSetup () protected virtual
Logs info on setup for cli environment to stride_logger.
Definition at line 144 of file BaseController.cpp.
References stride::util::FileSys::GetConfigDir(), stride::util::FileSys::GetCurrentDir(), stride::util::FileSys::GetDataDir(), stride::util::FileSys::GetExecPath(), stride::util::FileSys::GetRootDir(), stride::util::ConfigInfo::GitRevision(), stride::util::ConfigInfo::HaveOpenMP(), m_config_pt, m_output_prefix, m_stride_logger, stride::util::ConfigInfo::NumberAvailableThreads(), and stride::ContactLogMode::ToString().
void stride::BaseController::MakeLogger () protected virtual
Make the appropriate logger for cli environment and register as stride_logger.
Definition at line 102 of file BaseController.cpp.
References stride::util::FileSys::BuildPath(), stride::util::LogUtils::CreateCliLogger(), m_config_pt, m_output_prefix, and m_stride_logger.
void stride::BaseController::PatchConfig () protected
Patch run configuration with cli overrides and defaults.
void stride::BaseController::ReadConfigFile () protected
Read configuration file.
Member Data Documentation
boost::property_tree::ptree stride::BaseController::m_config_pt protected
Main configuration for run and sim.
Definition at line 86 of file BaseController.h.
Referenced by BaseController(), LogSetup(), MakeLogger(), and RegisterViewers().
std::string stride::BaseController::m_output_prefix protected
Prefix to output (name prefix or prefix dir)
Definition at line 87 of file BaseController.h.
Referenced by CheckOutputPrefix(), GetOutputPrefix(), LogSetup(), MakeLogger(), and RegisterViewers().
util::Stopwatch stride::BaseController::m_run_clock protected
Stopwatch for timing the computation.
Definition at line 88 of file BaseController.h.
std::shared_ptr<spdlog::logger> stride::BaseController::m_stride_logger protected
General logger.
Definition at line 89 of file BaseController.h.
Referenced by stride::CliController::Control(), GetLogger(), LogSetup(), MakeLogger(), and RegisterViewers().
bool stride::BaseController::m_use_install_dirs protected
Working dir or install dir mode.
Definition at line 90 of file BaseController.h.
std::shared_ptr<SimRunner> stride::BaseController::m_runner protected
Definition at line 91 of file BaseController.h.
Referenced by BaseController(), stride::CliController::Control(), GetSimRunner(), stride::GuiController::GuiController(), RegisterViewer(), and RegisterViewers().
util::RNManager stride::BaseController::m_rn_manager protected
Definition at line 92 of file BaseController.h.
Referenced by BaseController().
The documentation for this class was generated from the following files:
BaseController.h
BaseController.cpp