Stride Reference Manual: gengeopop::College Class Reference
gengeopop::College Class Reference
Models a College as ContactCenter.
#include <College.h>
Public Member Functions
College (unsigned int id)
std::string GetType () const override
Get the name of the type of contact center (e.g. College)
unsigned int GetPoolSize () const override
Get the size of a pool.
unsigned int GetMaxPools () const override
Get the maximal number of pools for this center.
void Fill (const std::shared_ptr< GeoGrid > &geoGrid) override
Apply this ContactCenter to the GeoGrid.
Public Member Functions inherited from gengeopop::ContactCenter
ContactCenter (unsigned int id)
Constructor.
unsigned int GetId () const
Get the ID back.
std::pair< unsigned int,
unsigned int > GetPopulationAndInfectedCount () const
Get a count of total population (first) and total number of infections (second)
void AddPool (stride::ContactPool *pool)
Add a ContactPool.
const std::vector
< stride::ContactPool * > & GetPools () const
Get the pools.
iterator begin ()
Allow range-based iteration.
iterator end ()
Allow range-based iteration.
virtual ~ContactCenter ()=default
Default destructor, but virtual.
Additional Inherited Members
Public Types inherited from gengeopop::ContactCenter
using iterator = std::vector< stride::ContactPool * >::iterator
Allow range-based iteration.
Protected Attributes inherited from gengeopop::ContactCenter
std::vector
< stride::ContactPool * > m_pools
Our pools.
unsigned int m_id
The id of this ContactCenter.
Detailed Description
Models a College as ContactCenter.
Definition at line 8 of file College.h.
Constructor & Destructor Documentation
gengeopop::College::College (unsigned int id) explicit
Definition at line 8 of file College.cpp.
Member Function Documentation
std::string gengeopop::College::GetType () const override virtual
Get the name of the type of contact center (e.g. College)
Implements gengeopop::ContactCenter.
Definition at line 10 of file College.cpp.
unsigned int gengeopop::College::GetPoolSize () const override virtual
Get the size of a pool.
Implements gengeopop::ContactCenter.
Definition at line 14 of file College.cpp.
unsigned int gengeopop::College::GetMaxPools () const override virtual
Get the maximal number of pools for this center.
Implements gengeopop::ContactCenter.
Definition at line 12 of file College.cpp.
Referenced by Fill().
void gengeopop::College::Fill (const std::shared_ptr< GeoGrid > & geoGrid) override virtual
Apply this ContactCenter to the GeoGrid.
Implements gengeopop::ContactCenter.
Definition at line 16 of file College.cpp.
References gengeopop::ContactCenter::AddPool(), and GetMaxPools().
The documentation for this class was generated from the following files:
College.h
College.cpp