Stride Reference Manual: calibration::CalibrationRunner Class Reference
calibration::CalibrationRunner Class Reference
A runner for the Calibration.
#include <CalibrationRunner.h>
Public Member Functions
CalibrationRunner ()
Setup.
void Run (unsigned int count, bool single)
Run the Calibrator.
void WriteResults (std::string filename)
Write the results to their respective files (based on testcase name)
void WriteBoxplots ()
Write the boxplots to their respective files (based on testcase name)
void DisplayBoxplots (unsigned int step)
Display the generated boxplots for step 'step' in the simulation to the screen.
void DisplayBoxplots ()
Display the generated boxplots for the last step in the simulation to the screen.
Protected Attributes
std::vector< std::pair
< boost::property_tree::ptree,
std::string > > configs
The configs for the testcases.
std::map< std::string,
std::vector< std::vector
< unsigned int > > > multipleResults
Results from RunMultiple.
std::map< std::string,
std::vector< unsigned int > > singleResults
Results from RunSingle.
Calibrator calibrator
The Calibrator to use for calibrating the testcases.
Detailed Description
A runner for the Calibration.
Definition at line 13 of file CalibrationRunner.h.
Constructor & Destructor Documentation
calibration::CalibrationRunner::CalibrationRunner ()
Setup.
Definition at line 13 of file CalibrationRunner.cpp.
Member Function Documentation
void calibration::CalibrationRunner::Run (unsigned int count, bool single)
Run the Calibrator.
Definition at line 15 of file CalibrationRunner.cpp.
References calibrator, configs, multipleResults, calibration::Calibrator::PrintMultipleResults(), calibration::Calibrator::PrintSingleResults(), calibration::Calibrator::RunMultiple(), calibration::Calibrator::RunSingle(), and singleResults.
void calibration::CalibrationRunner::WriteResults (std::string filename)
Write the results to their respective files (based on testcase name)
Definition at line 29 of file CalibrationRunner.cpp.
References calibrator, multipleResults, singleResults, calibration::Calibrator::WriteMultipleResults(), calibration::Calibrator::WriteResults(), and calibration::Calibrator::WriteSingleResults().
void calibration::CalibrationRunner::WriteBoxplots ()
Write the boxplots to their respective files (based on testcase name)
Definition at line 40 of file CalibrationRunner.cpp.
References calibration::Boxplot::Calculate(), multipleResults, and calibration::BoxplotGenerator::WriteToFile().
void calibration::CalibrationRunner::DisplayBoxplots (unsigned int step)
Display the generated boxplots for step 'step' in the simulation to the screen.
Definition at line 48 of file CalibrationRunner.cpp.
References calibration::Boxplot::Calculate(), calibration::BoxplotGenerator::Display(), and multipleResults.
void calibration::CalibrationRunner::DisplayBoxplots ()
Display the generated boxplots for the last step in the simulation to the screen.
Definition at line 56 of file CalibrationRunner.cpp.
References calibration::Boxplot::CalculateLastStep(), calibration::BoxplotGenerator::Display(), and multipleResults.
Member Data Documentation
std::vector<std::pair<boost::property_tree::ptree, std::string> > calibration::CalibrationRunner::configs protected
The configs for the testcases.
Definition at line 35 of file CalibrationRunner.h.
Referenced by calibration::ConfigFileCalibrationRunner::ConfigFileCalibrationRunner(), Run(), and calibration::TestCalibrationRunner::TestCalibrationRunner().
std::map<std::string, std::vector<std::vector<unsigned int> > > calibration::CalibrationRunner::multipleResults protected
Results from RunMultiple.
Definition at line 36 of file CalibrationRunner.h.
Referenced by DisplayBoxplots(), Run(), WriteBoxplots(), and WriteResults().
std::map<std::string, std::vector<unsigned int> > calibration::CalibrationRunner::singleResults protected
Results from RunSingle.
Definition at line 37 of file CalibrationRunner.h.
Referenced by Run(), and WriteResults().
Calibrator calibration::CalibrationRunner::calibrator protected
The Calibrator to use for calibrating the testcases.
Definition at line 38 of file CalibrationRunner.h.
Referenced by Run(), and WriteResults().
The documentation for this class was generated from the following files:
CalibrationRunner.h
CalibrationRunner.cpp