Stride Reference Manual: stride::util::CSV Class Reference
stride::util::CSV Class Reference
A collection of CSVRow elements.
#include <CSV.h>
Public Member Functions
CSV (const boost::filesystem::path &path, std::initializer_list< std::string > optLabels={})
Initialize from file.
CSV (std::istream &inputStream)
Constructor that uses a stream as input.
CSV (std::initializer_list< std::string > labels)
Initialize with header.
CSV ()=default
Default constructor. Mainly used for swig.
size_t GetColumnCount () const
Amount of columns in the CSV.
bool operator== (const CSV &other) const
Compare operator.
template<typename... T>
void AddRow (const T &...values)
Add row of values. Will all be converted to string with StringUtils::ToString.
void AddRow (std::vector< std::string > values)
Add row of string values.
void AddRows (std::vector< std::vector< std::string >> &rows)
Add a collection of rows.
void Write (const boost::filesystem::path &path) const
Write CSV to file.
size_t GetIndexForLabel (const std::string &label) const
Convert label to index for more user friendly and robust implementation.
const std::vector< std::string > & GetLabels () const
Protected Attributes
std::vector< std::string > labels
size_t columnCount = 0
Private Member Functions
void ReadFromStream (std::istream &inputStream)
Detailed Description
A collection of CSVRow elements.
Iterate with begin and end like STL containers.
Definition at line 37 of file CSV.h.
Constructor & Destructor Documentation
stride::util::CSV::CSV (const boost::filesystem::path & path, std::initializer_list< std::string > optLabels = {}) explicit
Initialize from file.
If optLabels not specifed, the file is required. Otherwise initialize like second constructor.
Definition at line 51 of file CSV.cpp.
References columnCount, labels, and ReadFromStream().
stride::util::CSV::CSV (std::istream & inputStream) explicit
Constructor that uses a stream as input.
Definition at line 74 of file CSV.cpp.
References ReadFromStream().
stride::util::CSV::CSV (std::initializer_list< std::string > labels)
Initialize with header.
Definition at line 76 of file CSV.cpp.
stride::util::CSV::CSV () default
Default constructor. Mainly used for swig.
Member Function Documentation
size_t stride::util::CSV::GetColumnCount () const inline
Amount of columns in the CSV.
Definition at line 59 of file CSV.h.
References columnCount.
Referenced by stride::util::CSVRow::CSVRow(), and gengeopop::CommutesCSVReader::FillGeoGrid().
bool stride::util::CSV::operator== (const CSV & other) const
Compare operator.
Definition at line 78 of file CSV.cpp.
References labels.
template<typename... T> void stride::util::CSV::AddRow (const T &... values) inline
Add row of values. Will all be converted to string with StringUtils::ToString.
Definition at line 92 of file CSV.h.
References stride::util::ToString().
Referenced by AddRows(), and ReadFromStream().
void stride::util::CSV::AddRow (std::vector< std::string > values)
Add row of string values.
Definition at line 147 of file CSV.cpp.
void stride::util::CSV::AddRows (std::vector< std::vector< std::string >> & rows)
Add a collection of rows.
Definition at line 83 of file CSV.cpp.
References AddRow().
void stride::util::CSV::Write (const boost::filesystem::path & path) const
Write CSV to file.
Definition at line 99 of file CSV.cpp.
References labels.
size_t stride::util::CSV::GetIndexForLabel (const std::string & label) const
Convert label to index for more user friendly and robust implementation.
This level of indirection does introduce a performance trade-off.
Definition at line 90 of file CSV.cpp.
References labels.
const std::vector< std::string > & stride::util::CSV::GetLabels () const
Definition at line 153 of file CSV.cpp.
References labels.
Referenced by gengeopop::CommutesCSVReader::FillGeoGrid().
void stride::util::CSV::ReadFromStream (std::istream & inputStream) private
Definition at line 123 of file CSV.cpp.
References AddRow(), columnCount, labels, stride::util::Split(), and stride::util::Trim().
Referenced by CSV().
Member Data Documentation
std::vector<std::string> stride::util::CSV::labels protected
Definition at line 87 of file CSV.h.
Referenced by CSV(), GetIndexForLabel(), GetLabels(), operator==(), ReadFromStream(), and Write().
size_t stride::util::CSV::columnCount = 0 protected
Definition at line 88 of file CSV.h.
Referenced by CSV(), GetColumnCount(), and ReadFromStream().
The documentation for this class was generated from the following files:
CSV.h
CSV.cpp