Stride Reference Manual: calibration::Calibrator Class Reference
calibration::Calibrator Class Reference
A calibration tool used to calibrate the Stride scenario tests.
#include <Calibrator.h>
Public Member Functions
Calibrator ()
Setup the Calibrator.
std::map< std::string,
std::vector< unsigned int > > RunSingle (const std::vector< std::pair< boost::property_tree::ptree, std::string >> &configs) const
Run one simulation for each config and return the infected counts after each timestep.
std::map< std::string,
std::vector< std::vector
< unsigned int > > > RunMultiple (unsigned int count, const std::vector< std::pair< boost::property_tree::ptree, std::string >> &configs) const
Run count simulations for each config by varying the seed and return the infected counts after each timestep.
void PrintMultipleResultsAtStep (const std::map< std::string, std::vector< std::vector< unsigned int >>> &results, unsigned int step) const
Print the mean and standard deviation for each step in the results obtained by RunMultiple to the Logger.
void PrintMultipleResults (const std::map< std::string, std::vector< std::vector< unsigned int >>> &results) const
Print the mean and standard deviation for the last step in the results obtained by RunMultiple to the Logger.
void PrintSingleResultsAtStep (const std::map< std::string, std::vector< unsigned int >> &results, unsigned int step) const
Print the exact results obtained at step 'step' by RunSingle to the Logger.
void PrintSingleResults (const std::map< std::string, std::vector< unsigned int >> &results) const
Print the exact results obtained at the last step by RunSingle to the Logger.
void WriteMultipleResults (const std::map< std::string, std::vector< std::vector< unsigned int >>> &results, std::string filename) const
Write the mean and standard deviation for each step in the results obtained by RunMultiple to a file.
void WriteSingleResults (const std::map< std::string, std::vector< unsigned int >> &results, std::string filename) const
Write the exact results obtained by RunSingle to a file.
void WriteResults (const std::map< std::string, std::vector< unsigned int >> &single, const std::map< std::string, std::vector< std::vector< unsigned int >>> &multiple, std::string filename) const
Combines the content of the two other write functions.
Private Member Functions
void PrintStep (const std::vector< unsigned int > &results, std::string name, unsigned int step) const
Print the mean and standard deviation of the given numbers, name and step.
std::pair< double, double > FindMeanStdev (std::vector< unsigned int > results) const
Compute the mean and standard deviation of the given numbers and return (mean, stdev).
stride::util::RNManager CreateRNManager (const boost::property_tree::ptree &config) const
Private Attributes
std::shared_ptr< spdlog::logger > logger
Logger to use for this class.
Detailed Description
A calibration tool used to calibrate the Stride scenario tests.
Definition at line 13 of file Calibrator.h.
Constructor & Destructor Documentation
calibration::Calibrator::Calibrator ()
Setup the Calibrator.
Definition at line 17 of file Calibrator.cpp.
Member Function Documentation
std::map< std::string, std::vector< unsigned int > > calibration::Calibrator::RunSingle (const std::vector< std::pair< boost::property_tree::ptree, std::string >> & configs) const
Run one simulation for each config and return the infected counts after each timestep.
Definition at line 19 of file Calibrator.cpp.
References stride::Population::Create(), CreateRNManager(), logger, and stride::viewers::InfectedViewer::Update().
Referenced by calibration::CalibrationRunner::Run().
std::map< std::string, std::vector< std::vector< unsigned int > > > calibration::Calibrator::RunMultiple (unsigned int count, const std::vector< std::pair< boost::property_tree::ptree, std::string >> & configs) const
Run count simulations for each config by varying the seed and return the infected counts after each timestep.
Definition at line 42 of file Calibrator.cpp.
References stride::Population::Create(), CreateRNManager(), logger, and stride::viewers::InfectedViewer::Update().
Referenced by calibration::CalibrationRunner::Run().
void calibration::Calibrator::PrintMultipleResultsAtStep (const std::map< std::string, std::vector< std::vector< unsigned int >>> & results, unsigned int step) const
Print the mean and standard deviation for each step in the results obtained by RunMultiple to the Logger.
Definition at line 106 of file Calibrator.cpp.
References logger, and PrintStep().
void calibration::Calibrator::PrintMultipleResults (const std::map< std::string, std::vector< std::vector< unsigned int >>> & results) const
Print the mean and standard deviation for the last step in the results obtained by RunMultiple to the Logger.
Definition at line 138 of file Calibrator.cpp.
References PrintStep().
Referenced by calibration::CalibrationRunner::Run().
void calibration::Calibrator::PrintSingleResultsAtStep (const std::map< std::string, std::vector< unsigned int >> & results, unsigned int step) const
Print the exact results obtained at step 'step' by RunSingle to the Logger.
Definition at line 129 of file Calibrator.cpp.
References logger.
void calibration::Calibrator::PrintSingleResults (const std::map< std::string, std::vector< unsigned int >> & results) const
Print the exact results obtained at the last step by RunSingle to the Logger.
Definition at line 122 of file Calibrator.cpp.
References logger.
Referenced by calibration::CalibrationRunner::Run().
void calibration::Calibrator::WriteMultipleResults (const std::map< std::string, std::vector< std::vector< unsigned int >>> & results, std::string filename) const
Write the mean and standard deviation for each step in the results obtained by RunMultiple to a file.
Definition at line 208 of file Calibrator.cpp.
References WriteResults().
Referenced by calibration::CalibrationRunner::WriteResults().
void calibration::Calibrator::WriteSingleResults (const std::map< std::string, std::vector< unsigned int >> & results, std::string filename) const
Write the exact results obtained by RunSingle to a file.
Definition at line 214 of file Calibrator.cpp.
References WriteResults().
Referenced by calibration::CalibrationRunner::WriteResults().
void calibration::Calibrator::WriteResults (const std::map< std::string, std::vector< unsigned int >> & single, const std::map< std::string, std::vector< std::vector< unsigned int >>> & multiple, std::string filename) const
Combines the content of the two other write functions.
Definition at line 153 of file Calibrator.cpp.
References FindMeanStdev(), and logger.
Referenced by WriteMultipleResults(), calibration::CalibrationRunner::WriteResults(), and WriteSingleResults().
void calibration::Calibrator::PrintStep (const std::vector< unsigned int > & results, std::string name, unsigned int step) const private
Print the mean and standard deviation of the given numbers, name and step.
Definition at line 86 of file Calibrator.cpp.
References FindMeanStdev(), and logger.
Referenced by PrintMultipleResults(), and PrintMultipleResultsAtStep().
std::pair< double, double > calibration::Calibrator::FindMeanStdev (std::vector< unsigned int > results) const private
Compute the mean and standard deviation of the given numbers and return (mean, stdev).
Definition at line 93 of file Calibrator.cpp.
Referenced by PrintStep(), and WriteResults().
stride::util::RNManager calibration::Calibrator::CreateRNManager (const boost::property_tree::ptree & config) const private
Definition at line 220 of file Calibrator.cpp.
References stride::util::RNManager::Initialize().
Referenced by RunMultiple(), and RunSingle().
Member Data Documentation
std::shared_ptr<spdlog::logger> calibration::Calibrator::logger private
Logger to use for this class.
Definition at line 59 of file Calibrator.h.
Referenced by PrintMultipleResultsAtStep(), PrintSingleResults(), PrintSingleResultsAtStep(), PrintStep(), RunMultiple(), RunSingle(), and WriteResults().
The documentation for this class was generated from the following files:
Calibrator.h
Calibrator.cpp