Stride Reference Manual: gengeopop::GeoGridJSONReader Class Reference
gengeopop::GeoGridJSONReader Class Reference
An implementation of the GeoGridReader using JSON This class is used to read a GeoGrid from a JSON file.
#include <GeoGridJSONReader.h>
Public Member Functions
GeoGridJSONReader (std::unique_ptr< std::istream > inputStream)
Construct the GeoGridJSONReader with the istream which contains the JSON.
std::shared_ptr< GeoGrid > Read ()
Actually perform the read and return the GeoGrid.
Public Member Functions inherited from gengeopop::GeoGridReader
GeoGridReader (std::unique_ptr< std::istream > inputStream)
Construct the GeoGridReader with the istream containing the contents of the file.
virtual ~GeoGridReader ()=default
Default destructor.
void UsePopulation (const std::shared_ptr< stride::Population > &pop, std::size_t regionId, std::string regionName)
Use the given information in the constructor of the GeoGrid, if not set the default constructor is used.
Private Member Functions
std::shared_ptr< Location > ParseLocation (boost::property_tree::ptree &location)
Create a Location based on the information stored in the provided boost property tree.
Coordinate ParseCoordinate (boost::property_tree::ptree &coordinate)
Create a Coordinate based on the information stored in the provided boost property tree.
std::shared_ptr< ContactCenter > ParseContactCenter (boost::property_tree::ptree &contactCenter)
Create a ContactCenter based on the information stored in the provided boost property tree.
stride::ContactPool * ParseContactPool (boost::property_tree::ptree &contactPool, stride::ContactPoolType::Id typeId)
Create a ContactCenter based on the information stored in the provided boost property tree.
stride::Person * ParsePerson (boost::property_tree::ptree &person)
Create a Person based on the information stored in the provided boost property tree.
Private Attributes
std::shared_ptr< GeoGrid > m_geoGrid
The GeoGrid which is being built.
Additional Inherited Members
Protected Member Functions inherited from gengeopop::GeoGridReader
void AddSubMunicipalities (std::shared_ptr< GeoGrid > geoGrid)
Add the SubMunicipalities that were found while looping of the Locations to their parent municipality.
void AddCommutes (std::shared_ptr< GeoGrid > geoGrid)
Add the commutes that were found to their respective Locations symmetrically.
Protected Attributes inherited from gengeopop::GeoGridReader
std::map< unsigned int,
stride::Person * > m_people
Store the persons (id->person) that were found while loping over the ContactPools.
std::vector< std::tuple
< unsigned int, unsigned int,
double > > m_commutes
from, to, amount
std::vector< std::pair
< unsigned int, unsigned int > > m_subMunicipalities
std::size_t m_regionId
RegionId, used to create persons.
std::string m_regionName
RegionName, region name passed to GeoGrid.
std::unique_ptr< std::istream > m_inputStream
file to read
std::shared_ptr
< stride::Population > m_population {nullptr}
population to use in the GeoGrid may be nullptr
Detailed Description
An implementation of the GeoGridReader using JSON This class is used to read a GeoGrid from a JSON file.
Definition at line 12 of file GeoGridJSONReader.h.
Constructor & Destructor Documentation
gengeopop::GeoGridJSONReader::GeoGridJSONReader (std::unique_ptr< std::istream > inputStream)
Construct the GeoGridJSONReader with the istream which contains the JSON.
Definition at line 17 of file GeoGridJSONReader.cpp.
Member Function Documentation
std::shared_ptr< GeoGrid > gengeopop::GeoGridJSONReader::Read () virtual
Actually perform the read and return the GeoGrid.
Implements gengeopop::GeoGridReader.
Definition at line 22 of file GeoGridJSONReader.cpp.
References gengeopop::GeoGridReader::AddCommutes(), gengeopop::GeoGridReader::AddSubMunicipalities(), stride::Person::GetId(), gengeopop::GeoGridReader::m_commutes, m_geoGrid, gengeopop::GeoGridReader::m_inputStream, gengeopop::GeoGridReader::m_people, gengeopop::GeoGridReader::m_population, gengeopop::GeoGridReader::m_regionId, gengeopop::GeoGridReader::m_regionName, gengeopop::GeoGridReader::m_subMunicipalities, ParseLocation(), and ParsePerson().
std::shared_ptr< Location > gengeopop::GeoGridJSONReader::ParseLocation (boost::property_tree::ptree & location) private
Create a Location based on the information stored in the provided boost property tree.
Definition at line 79 of file GeoGridJSONReader.cpp.
References gengeopop::GeoGridReader::m_commutes, gengeopop::GeoGridReader::m_subMunicipalities, ParseContactCenter(), and ParseCoordinate().
Referenced by Read().
Coordinate gengeopop::GeoGridJSONReader::ParseCoordinate (boost::property_tree::ptree & coordinate) private
Create a Coordinate based on the information stored in the provided boost property tree.
Definition at line 128 of file GeoGridJSONReader.cpp.
Referenced by ParseLocation().
std::shared_ptr< ContactCenter > gengeopop::GeoGridJSONReader::ParseContactCenter (boost::property_tree::ptree & contactCenter) private
Create a ContactCenter based on the information stored in the provided boost property tree.
Definition at line 135 of file GeoGridJSONReader.cpp.
References stride::ContactPoolType::College, stride::ContactPoolType::Household, stride::ContactPoolType::K12School, ParseContactPool(), stride::ContactPoolType::PrimaryCommunity, stride::ContactPoolType::SecondaryCommunity, and stride::ContactPoolType::Work.
Referenced by ParseLocation().
stride::ContactPool * gengeopop::GeoGridJSONReader::ParseContactPool (boost::property_tree::ptree & contactPool, stride::ContactPoolType::Id typeId) private
Create a ContactCenter based on the information stored in the provided boost property tree.
Definition at line 187 of file GeoGridJSONReader.cpp.
References m_geoGrid, and gengeopop::GeoGridReader::m_people.
Referenced by ParseContactCenter().
stride::Person * gengeopop::GeoGridJSONReader::ParsePerson (boost::property_tree::ptree & person) private
Create a Person based on the information stored in the provided boost property tree.
Definition at line 206 of file GeoGridJSONReader.cpp.
References m_geoGrid.
Referenced by Read().
Member Data Documentation
std::shared_ptr<GeoGrid> gengeopop::GeoGridJSONReader::m_geoGrid private
The GeoGrid which is being built.
Definition at line 38 of file GeoGridJSONReader.h.
Referenced by ParseContactPool(), ParsePerson(), and Read().
The documentation for this class was generated from the following files:
GeoGridJSONReader.h
GeoGridJSONReader.cpp