Stride Reference Manual: Backend Class Reference
Backend Class Reference
The backend for the MapViewer qml.
#include <backend.h>
Signals
void LocationsSelected (std::set< std::shared_ptr< gengeopop::Location >> locations)
Emits the locations that are selected. Other components can connect to this to be notified.
void UpdateInfected ()
Emits a signal that the infected count should be updated.
Public Member Functions
Backend (QObject *parent=nullptr)
Backend (const Backend &b)
Backend & operator= (const Backend &b)
Q_INVOKABLE void LoadGeoGridFromFile (const QString &file, QObject *errorDialog)
Loads a GeoGrid from JSON file.
Q_INVOKABLE void SetGeoGrids (std::vector< std::shared_ptr< gengeopop::GeoGrid >> grids)
Changes the geogrid to the given one.
Q_INVOKABLE void LoadGeoGridFromCommandLine (const QStringList &args)
Load a GeoGrid from JSON file, specified in the command line arguments.
Q_INVOKABLE void OnMarkerClicked (int region, unsigned int idOfClicked)
Handles a click on a marker.
Q_INVOKABLE void OnExtraMarkerClicked (int region, unsigned int idOfClicked)
Adds the location of the marker to the selection.
Q_INVOKABLE void OnMarkerHovered (int region, unsigned int idOfHover)
Handles the action that is needed when a marker is hovered over.
Q_INVOKABLE void OnMarkerHoveredOff (int region, unsigned int idOfHover)
Handles the action that is needed when a marker is no longer hovered over.
Q_INVOKABLE void ClearSelection ()
Removes all locations from selection and unselection but don't re-render the map.
Q_INVOKABLE void SelectArea (double slat, double slong, double elat, double elong)
Selects all locations in between.
Q_INVOKABLE void SelectExtraInArea (double slat, double slong, double elat, double elong)
The Same as SelectArea but does not clear selection first.
Q_INVOKABLE void SelectAll ()
Adds all locations of the grid to the selection and updates the visual appearance of these locations.
Q_INVOKABLE void SetShowCommutes (bool value)
Q_INVOKABLE void UpdateAllHealthColors ()
Updates all the health colors of the locations to match the current infection rate.
Q_INVOKABLE void SetObjects (QObject *map)
Places the locations of the current GeoGrid on the map.
Q_INVOKABLE void SaveGeoGridToFile (const QString &fileLoc, QObject *errorDialog)
Saves the current GeoGrid to a JSON file.
Private Member Functions
void PlaceMarker (gengeopop::Coordinate coordinate, int region, int id, unsigned int population, bool selected, bool specialmarker)
Places a marker at the given coordinate specialmarker Whether or not to display a special marker.
void PlaceMarkers ()
Places the markers on the map, according to the current checked boxes.
Q_INVOKABLE void ClearSelectionAndRender ()
Removes all locations from selection and unselection + re-render the map.
Q_INVOKABLE void SaveMarker (int region, int id, QObject *marker)
Saves the CustomMarker QObject of a specific location so we can modify it later.
void UpdateColorOfMarkers ()
Update colors of Markers based on the value of m_selection and m_unselection.
void EmitLocations ()
Sends a signal with the currently selected locations.
void ToggleSelectionOfLocation (int region, std::shared_ptr< gengeopop::Location > loc)
Adds the location to the selection if it is not yet in the list.
QObject * AddCommuteLine (gengeopop::Coordinate from, gengeopop::Coordinate to, double amount)
Add a line on the map for the given commute info.
void HideCommuteLine (QObject *obj)
Hides the commute line on the map.
void HideCommuteBetween (int region, const std::shared_ptr< gengeopop::Location > &loc1, const std::shared_ptr< gengeopop::Location > &loc2)
Hides the commutes between the given 2 locations on the map.
void ShowCommute (int region, const std::shared_ptr< gengeopop::Location > &loc1, const std::shared_ptr< gengeopop::Location > &)
Shows the commute from loc1 to loc2 on the map.
void SetHealthColorOf (int region, const std::shared_ptr< gengeopop::Location > &loc)
Updates the health color of the location on the map so it represents the current situation.
std::shared_ptr
< gengeopop::Location > GetLocationInRegion (std::pair< int, int > ids)
Return the requested location.
Private Attributes
double m_colorExponent = 0.1
We use this exponent to make the color change not linear.
QObject * m_map = nullptr
The QML Map the info is displayed on.
std::vector< std::shared_ptr
< gengeopop::GeoGrid > > m_grids
std::map< std::tuple< int, int >
, QObject * > m_markers
Reference to the markers so we do not need to search.
std::map< std::tuple< int,
unsigned int, unsigned int >
, QObject * > m_commutes
The first entry of the tuple is the region, second entry is the id of the location The corresponding marker is the marker of that location if it is currently on the map.
bool m_showCommutes = false
std::set< std::pair< int, int > > m_selection
The currently selected locations (id of region, id of location)
std::set< std::pair< int, int > > m_unselection
Items which must be unselected until the next UpdateColorOfMarkres call.
Detailed Description
The backend for the MapViewer qml.
Definition at line 12 of file backend.h.
Constructor & Destructor Documentation
Backend::Backend (QObject * parent = nullptr) explicit
Definition at line 27 of file backend.cpp.
Backend::Backend (const Backend & b)
Definition at line 32 of file backend.cpp.
Member Function Documentation
Backend & Backend::operator= (const Backend & b)
Definition at line 34 of file backend.cpp.
References m_grids, and m_selection.
void Backend::LoadGeoGridFromFile (const QString & file, QObject * errorDialog)
Loads a GeoGrid from JSON file.
Parameters
file The path to the JSON file that contains a valid GeoGrid description.
Definition at line 41 of file backend.cpp.
References gengeopop::GeoGridReaderFactory::CreateReader(), and SetGeoGrids().
void Backend::SetGeoGrids (std::vector< std::shared_ptr< gengeopop::GeoGrid >> grids)
Changes the geogrid to the given one.
Redraws the markers on the map.
Parameters
grid The grid we want to change to.
Definition at line 55 of file backend.cpp.
References m_commutes, m_grids, m_selection, m_unselection, and PlaceMarkers().
Referenced by LoadGeoGridFromFile(), and Map::SetGeoGrids().
void Backend::LoadGeoGridFromCommandLine (const QStringList & args)
Load a GeoGrid from JSON file, specified in the command line arguments.
Definition at line 67 of file backend.cpp.
References gengeopop::GeoGridReaderFactory::CreateReader(), m_grids, and PlaceMarkers().
void Backend::OnMarkerClicked (int region, unsigned int idOfClicked)
Handles a click on a marker.
Will emit a locationSelected signal with the correct location that correspons to the clicked marker.
Parameters
idOfClicked The id of the marker that was clicked.
Definition at line 122 of file backend.cpp.
References ClearSelection(), EmitLocations(), m_grids, ToggleSelectionOfLocation(), and UpdateColorOfMarkers().
void Backend::OnExtraMarkerClicked (int region, unsigned int idOfClicked)
Adds the location of the marker to the selection.
Parameters
idOfClicked
Definition at line 208 of file backend.cpp.
References EmitLocations(), m_grids, ToggleSelectionOfLocation(), and UpdateColorOfMarkers().
void Backend::OnMarkerHovered (int region, unsigned int idOfHover)
Handles the action that is needed when a marker is hovered over.
Parameters
idOfHover id of marker we hover over
Definition at line 412 of file backend.cpp.
References m_grids, and m_selection.
void Backend::OnMarkerHoveredOff (int region, unsigned int idOfHover)
Handles the action that is needed when a marker is no longer hovered over.
Parameters
idOfHover id of marker we hovered over
Definition at line 432 of file backend.cpp.
References m_grids, and m_selection.
void Backend::ClearSelection ()
Removes all locations from selection and unselection but don't re-render the map.
Definition at line 173 of file backend.cpp.
References m_selection, m_unselection, and UpdateColorOfMarkers().
Referenced by OnMarkerClicked(), and SelectArea().
void Backend::SelectArea (double slat, double slong, double elat, double elong)
Selects all locations in between.
Parameters
slat
slong
elat
elong
Definition at line 241 of file backend.cpp.
References ClearSelection(), and SelectExtraInArea().
void Backend::SelectExtraInArea (double slat, double slong, double elat, double elong)
The Same as SelectArea but does not clear selection first.
Definition at line 247 of file backend.cpp.
References EmitLocations(), m_grids, m_selection, m_unselection, and UpdateColorOfMarkers().
Referenced by SelectArea().
void Backend::SelectAll ()
Adds all locations of the grid to the selection and updates the visual appearance of these locations.
Definition at line 315 of file backend.cpp.
References EmitLocations(), m_grids, m_selection, m_unselection, and UpdateColorOfMarkers().
void Backend::SetShowCommutes (bool value)
Parameters
value If commutes need to be shown
Definition at line 337 of file backend.cpp.
References ClearSelectionAndRender(), m_showCommutes, and PlaceMarkers().
void Backend::UpdateAllHealthColors ()
Updates all the health colors of the locations to match the current infection rate.
Definition at line 379 of file backend.cpp.
References m_grids, SetHealthColorOf(), and UpdateInfected().
Referenced by Map::ForceUpdateMarkers().
void Backend::SetObjects (QObject * map)
Places the locations of the current GeoGrid on the map.
Parameters
map Instance of the Map QObject
Definition at line 133 of file backend.cpp.
References m_map, and PlaceMarkers().
void Backend::SaveGeoGridToFile (const QString & fileLoc, QObject * errorDialog)
Saves the current GeoGrid to a JSON file.
Parameters
fileLoc File to save the JSON to.
Definition at line 151 of file backend.cpp.
References gengeopop::GeoGridWriterFactory::CreateWriter(), and m_grids.
void Backend::LocationsSelected (std::set< std::shared_ptr< gengeopop::Location >> locations) signal
Emits the locations that are selected. Other components can connect to this to be notified.
Referenced by EmitLocations().
void Backend::UpdateInfected () signal
Emits a signal that the infected count should be updated.
Referenced by UpdateAllHealthColors().
void Backend::PlaceMarker (gengeopop::Coordinate coordinate, int region, int id, unsigned int population, bool selected, bool specialmarker) private
Places a marker at the given coordinate specialmarker Whether or not to display a special marker.
Definition at line 139 of file backend.cpp.
References m_map, and m_markers.
Referenced by PlaceMarkers().
void Backend::PlaceMarkers () private
Places the markers on the map, according to the current checked boxes.
: m_map is initialized correctly and holds the map we want to place markers on
Definition at line 91 of file backend.cpp.
References AddCommuteLine(), GetLocationInRegion(), m_commutes, m_grids, m_map, m_selection, m_showCommutes, and PlaceMarker().
Referenced by LoadGeoGridFromCommandLine(), SetGeoGrids(), SetObjects(), and SetShowCommutes().
void Backend::ClearSelectionAndRender () private
Removes all locations from selection and unselection + re-render the map.
Definition at line 182 of file backend.cpp.
References EmitLocations(), m_markers, m_selection, m_unselection, and UpdateColorOfMarkers().
Referenced by SetShowCommutes().
void Backend::SaveMarker (int region, int id, QObject * marker) private
Saves the CustomMarker QObject of a specific location so we can modify it later.
Parameters
region the region of the location
id the id of the location
Definition at line 377 of file backend.cpp.
References m_markers.
void Backend::UpdateColorOfMarkers () private
Update colors of Markers based on the value of m_selection and m_unselection.
Won't loop over every marker or location.
Definition at line 275 of file backend.cpp.
References GetLocationInRegion(), HideCommuteBetween(), m_grids, m_markers, m_selection, m_showCommutes, m_unselection, and ShowCommute().
Referenced by ClearSelection(), ClearSelectionAndRender(), OnExtraMarkerClicked(), OnMarkerClicked(), SelectAll(), and SelectExtraInArea().
void Backend::EmitLocations () private
Sends a signal with the currently selected locations.
Definition at line 199 of file backend.cpp.
References GetLocationInRegion(), LocationsSelected(), and m_selection.
Referenced by ClearSelectionAndRender(), OnExtraMarkerClicked(), OnMarkerClicked(), SelectAll(), and SelectExtraInArea().
void Backend::ToggleSelectionOfLocation (int region, std::shared_ptr< gengeopop::Location > loc) private
Adds the location to the selection if it is not yet in the list.
If it is already in the selection, it will be removed.
Definition at line 220 of file backend.cpp.
References m_selection, and m_unselection.
Referenced by OnExtraMarkerClicked(), and OnMarkerClicked().
QObject * Backend::AddCommuteLine (gengeopop::Coordinate from, gengeopop::Coordinate to, double amount) private
Add a line on the map for the given commute info.
Parameters
fromLatitude
fromLongitude
toLatitude
toLongitude
Definition at line 305 of file backend.cpp.
References m_map.
Referenced by PlaceMarkers(), and ShowCommute().
void Backend::HideCommuteLine (QObject * obj) private
Hides the commute line on the map.
Parameters
obj The commute line QObject
Definition at line 331 of file backend.cpp.
Referenced by HideCommuteBetween().
void Backend::HideCommuteBetween (int region, const std::shared_ptr< gengeopop::Location > & loc1, const std::shared_ptr< gengeopop::Location > & loc2) private
Hides the commutes between the given 2 locations on the map.
Parameters
loc1
loc2
Definition at line 345 of file backend.cpp.
References HideCommuteLine(), and m_commutes.
Referenced by UpdateColorOfMarkers().
void Backend::ShowCommute (int region, const std::shared_ptr< gengeopop::Location > & loc1, const std::shared_ptr< gengeopop::Location > & loc2) private
Shows the commute from loc1 to loc2 on the map.
Parameters
loc1
Definition at line 361 of file backend.cpp.
References AddCommuteLine(), and m_commutes.
Referenced by UpdateColorOfMarkers().
void Backend::SetHealthColorOf (int region, const std::shared_ptr< gengeopop::Location > & loc) private
Updates the health color of the location on the map so it represents the current situation.
Parameters
region the id of the region the location is in
loc The location we want to update on the map.
Definition at line 391 of file backend.cpp.
References m_colorExponent, and m_markers.
Referenced by UpdateAllHealthColors().
std::shared_ptr< gengeopop::Location > Backend::GetLocationInRegion (std::pair< int, int > ids) private
Return the requested location.
Parameters
ids (region id, location id)
Definition at line 456 of file backend.cpp.
References m_grids.
Referenced by EmitLocations(), PlaceMarkers(), and UpdateColorOfMarkers().
Member Data Documentation
double Backend::m_colorExponent = 0.1 private
We use this exponent to make the color change not linear.
Definition at line 127 of file backend.h.
Referenced by SetHealthColorOf().
QObject* Backend::m_map = nullptr private
The QML Map the info is displayed on.
Definition at line 128 of file backend.h.
Referenced by AddCommuteLine(), PlaceMarker(), PlaceMarkers(), and SetObjects().
std::vector<std::shared_ptr<gengeopop::GeoGrid> > Backend::m_grids private
Definition at line 129 of file backend.h.
Referenced by GetLocationInRegion(), LoadGeoGridFromCommandLine(), OnExtraMarkerClicked(), OnMarkerClicked(), OnMarkerHovered(), OnMarkerHoveredOff(), operator=(), PlaceMarkers(), SaveGeoGridToFile(), SelectAll(), SelectExtraInArea(), SetGeoGrids(), UpdateAllHealthColors(), and UpdateColorOfMarkers().
std::map<std::tuple<int, int>, QObject*> Backend::m_markers private
Reference to the markers so we do not need to search.
Definition at line 130 of file backend.h.
Referenced by ClearSelectionAndRender(), PlaceMarker(), SaveMarker(), SetHealthColorOf(), and UpdateColorOfMarkers().
std::map<std::tuple<int, unsigned int, unsigned int>, QObject*> Backend::m_commutes private
The first entry of the tuple is the region, second entry is the id of the location The corresponding marker is the marker of that location if it is currently on the map.
The commute lines that are shown on the map, KEY is the id of the city the commutes go to
Definition at line 135 of file backend.h.
Referenced by HideCommuteBetween(), PlaceMarkers(), SetGeoGrids(), and ShowCommute().
bool Backend::m_showCommutes = false private
Definition at line 136 of file backend.h.
Referenced by PlaceMarkers(), SetShowCommutes(), and UpdateColorOfMarkers().
std::set<std::pair<int, int> > Backend::m_selection private
The currently selected locations (id of region, id of location)
Definition at line 137 of file backend.h.
Referenced by ClearSelection(), ClearSelectionAndRender(), EmitLocations(), OnMarkerHovered(), OnMarkerHoveredOff(), operator=(), PlaceMarkers(), SelectAll(), SelectExtraInArea(), SetGeoGrids(), ToggleSelectionOfLocation(), and UpdateColorOfMarkers().
std::set<std::pair<int, int> > Backend::m_unselection private
Items which must be unselected until the next UpdateColorOfMarkres call.
Definition at line 139 of file backend.h.
Referenced by ClearSelection(), ClearSelectionAndRender(), SelectAll(), SelectExtraInArea(), SetGeoGrids(), ToggleSelectionOfLocation(), and UpdateColorOfMarkers().
The documentation for this class was generated from the following files:
backend.h
backend.cpp