Stride Reference Manual: gengeopop::PartialGenerator Class Reference
gengeopop::PartialGenerator Class Reference abstract
An interface for generators that provide a partial solution.
#include <PartialGenerator.h>
Public Member Functions
PartialGenerator (stride::util::RNManager &rn_manager, std::shared_ptr< spdlog::logger > logger)
Constructor with a RNManager and a logger.
virtual void Apply (std::shared_ptr< GeoGrid > geogrid, GeoGridConfig &geoGridConfig)=0
Apply this PartialGenerator to the given geogrid, generating ContactCenters.
virtual ~PartialGenerator ()=default
Virtual destructor for inheritance.
Protected Member Functions
void CheckWeight (const std::string &func, double weight)
Make sure we're using a valid weight for random numbers.
Protected Attributes
stride::util::RNManager & m_rnManager
RnManager used by generators.
std::shared_ptr< spdlog::logger > m_logger
Logger used by generators.
Detailed Description
An interface for generators that provide a partial solution.
They generate some data and apply it onto the GeoGrid.
Definition at line 13 of file PartialGenerator.h.
Constructor & Destructor Documentation
gengeopop::PartialGenerator::PartialGenerator (stride::util::RNManager & rn_manager, std::shared_ptr< spdlog::logger > logger) explicit
Constructor with a RNManager and a logger.
Definition at line 5 of file PartialGenerator.cpp.
virtual gengeopop::PartialGenerator::~PartialGenerator () virtual default
Virtual destructor for inheritance.
Member Function Documentation
virtual void gengeopop::PartialGenerator::Apply (std::shared_ptr< GeoGrid > geogrid, GeoGridConfig & geoGridConfig) pure virtual
Apply this PartialGenerator to the given geogrid, generating ContactCenters.
Implemented in gengeopop::CollegeGenerator, gengeopop::CommunityGenerator, gengeopop::HouseholdGenerator, gengeopop::K12SchoolGenerator, and gengeopop::WorkplaceGenerator.
void gengeopop::PartialGenerator::CheckWeight (const std::string & func, double weight) inline protected
Make sure we're using a valid weight for random numbers.
Definition at line 30 of file PartialGenerator.h.
References ExcAssert().
Referenced by gengeopop::CollegeGenerator::Apply(), gengeopop::WorkplaceGenerator::Apply(), and gengeopop::CommunityGenerator::Apply().
Member Data Documentation
stride::util::RNManager& gengeopop::PartialGenerator::m_rnManager protected
RnManager used by generators.
Definition at line 26 of file PartialGenerator.h.
Referenced by gengeopop::CollegeGenerator::Apply(), gengeopop::WorkplaceGenerator::Apply(), gengeopop::K12SchoolGenerator::Apply(), gengeopop::HouseholdGenerator::Apply(), and gengeopop::CommunityGenerator::Apply().
std::shared_ptr<spdlog::logger> gengeopop::PartialGenerator::m_logger protected
Logger used by generators.
Definition at line 27 of file PartialGenerator.h.
The documentation for this class was generated from the following files:
PartialGenerator.h
PartialGenerator.cpp