Stride Reference Manual: gengeopop::HouseholdPopulator Class Reference
gengeopop::HouseholdPopulator Class Reference
Populate Households.
#include <HouseholdPopulator.h>
Public Member Functions
void Apply (std::shared_ptr< GeoGrid > geogrid, GeoGridConfig &geoGridConfig) override
Populate the given geogrid.
Public Member Functions inherited from gengeopop::PartialPopulator
PartialPopulator (stride::util::RNManager &rn_manager, std::shared_ptr< spdlog::logger > logger)
Construct with a RNManager and a logger.
virtual ~PartialPopulator ()=default
Virtual destructor for inheritance.
Additional Inherited Members
Protected Member Functions inherited from gengeopop::PartialPopulator
template<typename T >
std::vector
< stride::ContactPool * > GetContactPoolInIncreasingRadius (const std::shared_ptr< GeoGrid > &geoGrid, const std::shared_ptr< Location > &start, double startRadius=10) const
Find contactpools in geoGrid in an exponentially increasing radius, starting at startRadius, around start As soon as at least one pool is found, all pools within the current radius are returned May return an empty vector when there are no pools to be found.
bool MakeChoice (double fraction)
Convenience wrapper around m_rnManager.
Protected Attributes inherited from gengeopop::PartialPopulator
stride::util::RNManager & m_rnManager
RnManager used by populators.
std::shared_ptr< spdlog::logger > m_logger
Logger used by populators.
Detailed Description
Populate Households.
Definition at line 9 of file HouseholdPopulator.h.
Member Function Documentation
void gengeopop::HouseholdPopulator::Apply (std::shared_ptr< GeoGrid > geogrid, GeoGridConfig & geoGridConfig) override virtual
Populate the given geogrid.
Implements gengeopop::PartialPopulator.
Definition at line 12 of file HouseholdPopulator.cpp.
References stride::ContactPool::AddMember(), gengeopop::GeoGridConfig::generated, stride::util::RNManager::GetGenerator(), stride::ContactPool::GetId(), gengeopop::GeoGridConfig::household_types, gengeopop::PartialPopulator::m_logger, and gengeopop::PartialPopulator::m_rnManager.
The documentation for this class was generated from the following files:
HouseholdPopulator.h
HouseholdPopulator.cpp